### ISSUE TITLE
hf 15 sim not working

### ISSUE THREAD

**Issue by will-caruana** [RfidResearchGroup/proxmark3#1029]
Describe the bug
Can't simulate a hf 15 card keep getting a HEX symbols error

To Reproduce
hf 15 sim -u E011223344556677

Expected behavior
Proxmark would start simulating an 8byte UID

Screenshots
```
[usb] pm3 -->     hf 15 sim -u E011223344556677 
[!] ⚠  UID must include 16 HEX symbols
[usb] pm3 --> hf 15 sim -u 0xE011223344556677
Parameter error: Invalid HEX value

```

Desktop (please complete the following information):

[usb] pm3 --> hw version

  [ Proxmark3 RFID instrument ]

 [ CLIENT ]
  client: RRG/Iceman/master/v4.9237-1842-gceb709a5 2020-10-22 20:41:48
  compiled with GCC 9.3.0 OS:Linux ARCH:x86_64

 [ PROXMARK3 ]
  firmware.................. PM3RDV4
  external flash............ present
  smartcard reader.......... present
  FPC USART for BT add-on... present

 [ ARM ]
  bootrom: RRG/Iceman/master/v4.9237-1842-gceb709a5 2020-10-22 20:42:08
       os: RRG/Iceman/master/v4.9237-1842-gceb709a5 2020-10-22 20:42:20
  compiled with GCC 8.3.1 20190703 (release) [gcc-8-branch revision 273027]

 [ FPGA ] 
  LF image built for 2s30vq100 on 2020-07-08 at 23: 8: 7
  HF image built for 2s30vq100 on 2020-07-08 at 23: 8:19
  HF FeliCa image built for 2s30vq100 on 2020-07-08 at 23: 8:30

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev A
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 296368 bytes (57%) Free: 227920 bytes (43%)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

**Comment by iceman1001** [comment]
Thanks!
I pushed a fix.
