### ISSUE TITLE
hf mf rdsc zeroing out A key in result

### ISSUE THREAD

**Issue by danyhm** [RfidResearchGroup/proxmark3#1030]
**Describe the bug**
hf mf rdsc result is zeroing out the A key on output
(Last line of result)

**To Reproduce**
Read any block on a mifare classic card using the hf mf rdsc command

**Expected behavior**
The result should include the key 

**Desktop (please complete the following information):**
 - hw version
 - hw status
 Are the latest

**Comment by iceman1001** [comment]
That is the expect behavior of  a MIFARE Classic card.  I suggest you read up on the datasheets.
