### ISSUE TITLE
Arch Linux based development environment for Proxmark3

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#1031]
Your Fluxbb data base has **corrupted**, it droped all of my messages.
I understand thst's this is an open source project and you have no a normal SQL server.

**The Ultimate compilation solution – Arch Space was successful developed.**

_Arch Linux based development environment for Proxmark3. Made as class A for development.
Have a fun with pull requests to the repo._

**Comment by iceman1001** [comment]
Since you are banned,  this will be deleted.
