### ISSUE TITLE
Like a bug for "hf mfu restore"

### ISSUE THREAD

**Issue by xianglin1998** [RfidResearchGroup/proxmark3#1035]
Hi guys, today i use "hf mfu dump" to read a `ul` tag, and place a `ul-gen2` tag to write by "hf mfu restore s f xxxx.bin".
Redump after restored, i have some problem found, i always lost last 2 block no write, i try to use `ul-c` and other mfu tag,  but it's a pity that this problem is occur on all mfu tag with i found...

As usual, I read the source code and found something I didn't understand.
Pic:
![image](https://user-images.githubusercontent.com/23152044/97254611-bac3b780-1849-11eb-8002-4189810d659b.png)

In the `write_special`,  the `blocks` no defind last page `from x - end`, always `from x - end - 2`.

**Comment by xianglin1998** [comment]
@iceman1001 
@doegox

**Comment by iceman1001** [comment]
I would say its because the two last blocks is password and pack. We don't wanna set those of mistake

**Comment by xianglin1998** [comment]
OK, that is pack and pwd for ul-ev1, thanks.
