### ISSUE TITLE
[BUG] The restore bug for "hf 15 restore"

### ISSUE THREAD

**Issue by xianglin1998** [RfidResearchGroup/proxmark3#1036]
If we use cmd "hf 15 restore f xxx" to restore a tag, we can get a wrong data write result,

![image](https://user-images.githubusercontent.com/23152044/97546154-02437280-1a07-11eb-8417-26b1ca214035.png)

Because data offset not increment of block size, only data address + 1.

![image](https://user-images.githubusercontent.com/23152044/97545970-bbee1380-1a06-11eb-84c6-9963c8c68244.png)

**Comment by xianglin1998** [comment]
@iceman1001 This may be a bug, because it broke my imagination of block.

**Comment by xianglin1998** [comment]
If it is confirmed to be a bug, then I will new a PR to fix it.

**Comment by iceman1001** [comment]
Are you talking about `hf 15 restore`   or are you talking about `hf 15 write` 
restore calls write underneath.   Messy, messy.

restore:
it seems to be dependent of block size.    Which should default to 4,   or user-specified to N.

write:
.....


I am missing output in your pictures,  I don't see your restore command among others.
Can you run it again with the debug on turned on?
```
data setd 2
hf 15 restore
```

**Comment by iceman1001** [comment]
Good catch!  I confirmed it.  Fix pushed.

**Comment by xianglin1998** [comment]
HaHaHa, Thanks PR, I will continue to find bugs, which is one of my hobbies.

**Comment by iceman1001** [comment]
Find bugs is good.   Refactor bad stuff is even better !
