### ISSUE TITLE
PIN of sim card

### ISSUE THREAD

**Issue by ictmehrdad** [RfidResearchGroup/proxmark3#104]
How can we able to clone or read the pin of A sim card with RDV4?!
Thanks

**Comment by RfidResearchGroup** [comment]
Time to hit the datasheets for ISO7816 and EMV  :)   Think there is some pin&code  functions inside the repo already by @merlokk  but I haven't gotten around to look at it

**Comment by ictmehrdad** [comment]
I can’t find anything especial!!!
Could you please tell me that why there is the sim card extension for RDV4?!what can I do with that!?
Thanks

**Comment by merlokk** [comment]
http://rebelsimcard.com/sim-commands.html

**Comment by ictmehrdad** [comment]
Dear Oleg
It means that these commands work in RDV4?! Does the Frimware of RDV4 support it?!
Great, thanks

**Comment by iceman1001** [comment]
looke into the new pm3 command **EMV**

**Comment by ictmehrdad** [comment]
Thanks
Okay I will check it
