### ISSUE TITLE
Reader Attack

### ISSUE THREAD

**Issue by ictmehrdad** [RfidResearchGroup/proxmark3#105]
1- How can we have a reader attack with RDV4!?Is it like Rebooted!?
2- Is there any way to add a battery to the RDV4 like rebooted or chameleon REV-G!?
3- Dose a Reader Attack is just for Mifire card or we can have a same attack for ultralight or etc!?

**Comment by iceman1001** [comment]
1) there is a reader attack implemented.  read your helptexts / forum.  hint:  hf mf sim
2) yes,  just connect it via FPC connecter
3) there is alternativs for mifare ultralight type of cards.  hint: hf mfu commands

None of these questions is about this firmware. You should go to proxmark forum and look for your answers.
