### ISSUE TITLE
[idea] 15693 two subcarrier

### ISSUE THREAD

**Issue by nemanjan00** [RfidResearchGroup/proxmark3#1183]
**Is your feature request related to a problem? Please describe.**
I am unable to sniff or send raw commands  that require two subcarriers. 

From what I see, this is a well known issue and missing feature, but is not documented in issues

**Describe the solution you'd like**
Implementation of two subcarrier support

**Describe alternatives you've considered**
As far as I know, there are no alternatives, to achieve what I want

**Additional context**

https://github.com/RfidResearchGroup/proxmark3/blob/master/armsrc/iso15693.c#L51

**Comment by iceman1001** [comment]
There is no active development in this area,  so if you are not thinking of adding support I am afraid it will a lost wish.
I add it to the https://github.com/RfidResearchGroup/proxmark3/wiki/Wishlist  and close this issue.
