### ISSUE TITLE
Creation of symlink for OS X - location ?

### ISSUE THREAD

**Issue by TomHarkness** [RfidResearchGroup/proxmark3#12]
As the title suggests. In either install.sh or update.sh, I want to create a symlink that points the /dev/cu.usbmodem*** to /dev/pm3.

Where should this function be placed?

**Comment by RfidResearchGroup** [comment]
LIke we do for linux in the udev?

**Comment by TomHarkness** [comment]
Yes same thing as for udev. I just want to make sure its run at a time when the user will definitely have the pm3 plugged in. Preferably the first time.

**Comment by TomHarkness** [comment]
So far my reading suggests that this is not possible on OS X in the same way. Haven’t had much time for this one due to organising some other things but I’ll dig in to it over the course of today and report back.

**Comment by RfidResearchGroup** [comment]
if its not possible,  just close this one.

**Comment by TomHarkness** [comment]
Closing for now - may find a solution eventually.
