### ISSUE TITLE
Proxmark3 easy issue

### ISSUE THREAD

**Issue by koszyk1980** [RfidResearchGroup/proxmark3#1245]
Hi, I starting fun with this amazing device . I did all steps from this video and when I press FLASH - all.bat  I get this message on screen ? I using proxmark3 easy bought  on AliExpress . Any advice?? I would like using proxmark3 on windows 10 

Link video : https://youtu.be/ROIplLNklpo
Screenshot: https://www.dropbox.com/s/40hgsqia1sisq06/screen.jpg?dl=0

**Comment by iceman1001** [comment]
Have you followed the installation instructions on this repo ?  
The instructions here is up-to-date and proven to work.

**Comment by koszyk1980** [comment]
> Have you followed the installation instructions on this repo ?  
> 
> The instructions here is up-to-date and proven to work.   
> 
> 
> 
> 

I did everything like on video on YouTube https://youtu.be/ROIplLNklpo

Can you send me link with instructions up to date . I will try again 🤔

**Comment by iceman1001** [comment]
So you didn't follow the instructions on this repo.  ok.  
You find all relevant links in the readme / first page of this repo.
