### ISSUE TITLE
hf legic dump / restore de-/obfuscation command confusion

### ISSUE THREAD

**Issue by maichai** [RfidResearchGroup/proxmark3#1255]
**Describe the bug**

hf legic dump with and without --deobfuscate do the opposite of what is documented in the help text

**To Reproduce**
1. hf legic info
2. hf legic dump -f origdump1.bin
3. inspect the binary dump file, you will see it equals the content of hf legic info, and the help text of hf legic info states that the output is already obfuscated (which is true, as I have a valid legic MIM256 card that contains all zeroes except for in block 0. hf legic  info will show the content is all zero and according to the help it is already deobfuscated, which must be true, as the MCC is not zero. If MCC is non-zero, the payload would have to equal the MCC if it would be still obfuscated.
 
4. hf legic dump -f origdump2.bin --deobfuscate
5. inspect the binary dump file, you will see it is actually obfuscated, not deobfuscated. For my "all zeroes" card all blocks contains MCC value only (except for block 0).

6. put an empty MIM256 legic card on the PM3 and hf legic restore -f origdump1.bin
7. hf legic dump -f copydump1.bin
8. compare origdump1.bin and copydump1.bin: block 0 differs in the expected first bytes, the rest of block 0 is equal for both cards. all other blocks are shown as all zero for both cards. By deduction, if hf legic info already deobfuscates the content of the card, the restored card must be properly obfuscated with the MCC value of the previously blank MIM256 card. Ergo, hf legic restore (without --obfuscate) actually obfuscates the origdump1.bin before writing it to the card (remember: origdump1.bin contains the deobfuscated card content).

9. put an empty MIM256 legic card on the PM3 and hf legic restore -f origdump1.bin --obfuscate
10. hf legic dump -f copydump2.bin
12. compare origdump1.bin and copydump2.bin:  block 0 differs in the expected first bytes, the rest of block 0 is equal for both cards. the first bytes of block 1 also contains zeroes (non-obfuscated area), but the rest of block 1 and all other blocks contain the MCC of the original card! This means that hf legic restore -f file --obfuscate actually obfuscates the dump twice! Firstly with the MCC from the dump, secondly with the MCC of the blank card. hf legic dump then deobfuscated with MCC from the copied/formerly blank card, so in the dump the content is still obfuscated with the MCC of the original card.

**Expected behavior**

The actual behavior of the commands should be coherent with the help text. If there is a --deobfuscate option, teh command should actually write the deobfuscated content to the dump file. By deduction, without the --deobfuscate option the dump content should be non-deobfuscated, e.g. 1:1 as is present on the card (so normally obfuscated).

Likewise using -- obfuscate should obfuscate the dump file content before writing it to the card, and without the option --obfuscate, it should write the dump file content 1:1 as is in the file to the card. 

If you have intended the commands to do something different, please correct the behavior and the help info to be coherent with the behavior.

**Desktop (please complete the following information):**
client: RRG/Iceman/master/0d04c14be 2021-04-24 20:27:30
  compiled with Clang/LLVM Apple LLVM 12.0.0 (clang-1200.0.32.29) OS:OSX ARCH:x86_64

**Comment by iceman1001** [comment]
Indeed,
I pushed a minor fix for aborting if the xoring fails,  sinec I am guess thats where your problems arise.
Hard to replicate your specific issue since I don't have your cards to play with.

Anyway,  pull and see if it gives you a better textual output,   and if you are not happy,  feel free to contribute with a fix!
