### ISSUE TITLE
Cloning an anti-dup card?

### ISSUE THREAD

**Issue by Unhackablerip** [RfidResearchGroup/proxmark3#1268]
dormakaba. com/resource/blob/634014/281ec557010b55531d487f2f5933fb81/kkt2040-k-secure-03-19-web-pdf-data.pdf

Trying to clone this anti-dup card with no success for 2 months now, how should I proceed? Do I need a special FUID card or something?

[usb] pm3 --> hf search
[|] Searching for ISO14443-A tag...
[+]  UID: B2 CC 00 81
[+] ATQA: 00 02
[+]  SAK: 18 [2]
[+] Possible types:
[+]    MIFARE Classic 4K
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: hard
[#] Auth error
[?] Hint: try `hf mf` commands

[usb] pm3 --> hf mf autopwn
[!] no known key was supplied, key recovery might fail
[+] loaded 23 keys from hardcoded default array
[=] running strategy 1
[=] Chunk: 0.8s | found 29/32 keys (23)
[=] running strategy 2
[=] Chunk: 0.7s | found 29/32 keys (23)
[+] target sector   0 key type A -- found valid key [ FFFFFFFFFFFF ] (used for nested / hardnested attack)
[+] target sector   2 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   2 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   3 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   3 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   4 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   4 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   5 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   5 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   6 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   6 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   7 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   7 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   8 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   8 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   9 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   9 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  10 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  10 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  11 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  11 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  12 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  12 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  13 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  13 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  14 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  14 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  15 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  15 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] Using AVX2 SIMD core.

 time    | #nonces | Activity                                                | expected to brute force
         |         |                                                         | #states         | time
------------------------------------------------------------------------------------------------------
       0 |       0 | Start using 16 threads and AVX2 SIMD core               |                 |
       0 |       0 | Brute force benchmark: 3310 million (2^31.6) keys/s     | 140737488355328 |   12h
       4 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |   12h
       7 |     112 | Apply bit flip properties                               |     13246673920 |    4s
       8 |     223 | Apply bit flip properties                               |      1655716224 |    1s
       9 |     335 | Apply bit flip properties                               |      1366097664 |    0s
      10 |     446 | Apply bit flip properties                               |      1366097664 |    0s
      10 |     557 | Apply bit flip properties                               |      1341938688 |    0s
      11 |     668 | Apply bit flip properties                               |      1341938688 |    0s
      12 |     780 | Apply bit flip properties                               |      1341938688 |    0s
      12 |     890 | Apply bit flip properties                               |      1341938688 |    0s
      13 |    1001 | Apply bit flip properties                               |      1341938688 |    0s
      14 |    1111 | Apply bit flip properties                               |      1341938688 |    0s
      15 |    1221 | Apply bit flip properties                               |      1341938688 |    0s
      16 |    1331 | Apply bit flip properties                               |      1341938688 |    0s
      17 |    1442 | Apply Sum property. Sum(a0) = 112                       |        55588016 |    0s
      17 |    1442 | (Ignoring Sum(a8) properties)                           |        55588016 |    0s
      18 |    1442 | Brute force phase completed.  Key found: 34aed43006e1   |               0 |    0s
[+] target sector   0 key type B -- found valid key [ 34AED43006E1 ]
[+] Using AVX2 SIMD core.

 time    | #nonces | Activity                                                | expected to brute force
         |         |                                                         | #states         | time
------------------------------------------------------------------------------------------------------
       0 |       0 | Start using 16 threads and AVX2 SIMD core               |                 |
       0 |       0 | Brute force benchmark: 2954 million (2^31.5) keys/s     | 140737488355328 |   13h
       4 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |   13h
       7 |     112 | Apply bit flip properties                               |    732695166976 |  4min
       8 |     224 | Apply bit flip properties                               |    564743503872 |  3min
       9 |     336 | Apply bit flip properties                               |    453997363200 |  3min
      10 |     447 | Apply bit flip properties                               |    422850789376 |  2min
      11 |     558 | Apply bit flip properties                               |    372561018880 |  2min
      12 |     670 | Apply bit flip properties                               |    372024573952 |  2min
      12 |     780 | Apply bit flip properties                               |    372024573952 |  2min
      13 |     891 | Apply bit flip properties                               |    372024573952 |  2min
      14 |    1003 | Apply bit flip properties                               |    372024573952 |  2min
      15 |    1115 | Apply Sum property. Sum(a0) = 128                       |     31060455424 |   11s
      16 |    1224 | Apply bit flip properties                               |     65814482944 |   22s
      17 |    1333 | Apply bit flip properties                               |     65814482944 |   22s
      17 |    1442 | Apply bit flip properties                               |     65814482944 |   22s
      18 |    1550 | Apply bit flip properties                               |     39811289088 |   13s
      19 |    1661 | Apply bit flip properties                               |     39811289088 |   13s
      20 |    1769 | Apply bit flip properties                               |     23286155264 |    8s
      21 |    1875 | Apply bit flip properties                               |     23286155264 |    8s
      22 |    1984 | Apply bit flip properties                               |     11270637568 |    4s
      22 |    2092 | Apply bit flip properties                               |     11270637568 |    4s
      23 |    2199 | Apply bit flip properties                               |     11669176320 |    4s
      24 |    2306 | Apply bit flip properties                               |      5640838656 |    2s
      25 |    2306 | (1. guess: Sum(a8) = 0)                                 |      5640838656 |    2s
      25 |    2306 | Apply Sum(a8) and all bytes bitflip properties          |      5329988608 |    2s
      25 |    2306 | Brute force phase completed.  Key found: 98669f3dc004   |               0 |    0s
[+] target sector   1 key type A -- found valid key [ 98669F3DC004 ]
[+] Using AVX2 SIMD core.

 time    | #nonces | Activity                                                | expected to brute force
         |         |                                                         | #states         | time
------------------------------------------------------------------------------------------------------
       0 |       0 | Start using 16 threads and AVX2 SIMD core               |                 |
       0 |       0 | Brute force benchmark: 2866 million (2^31.4) keys/s     | 140737488355328 |   14h
       4 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |   14h
       7 |     112 | Apply bit flip properties                               |   2111823282176 | 12min
       8 |     224 | Apply bit flip properties                               |    853705687040 |  5min
       9 |     336 | Apply bit flip properties                               |    601920831488 |  4min
      10 |     447 | Apply bit flip properties                               |    580338057216 |  3min
      11 |     558 | Apply bit flip properties                               |    580338057216 |  3min
      11 |     669 | Apply bit flip properties                               |    580338057216 |  3min
      12 |     780 | Apply bit flip properties                               |    580338057216 |  3min
      13 |     889 | Apply bit flip properties                               |    580338057216 |  3min
      13 |     999 | Apply bit flip properties                               |    580338057216 |  3min
      14 |    1109 | Apply bit flip properties                               |    580338057216 |  3min
      15 |    1221 | Apply bit flip properties                               |    580338057216 |  3min
      17 |    1331 | Apply Sum property. Sum(a0) = 192                       |     17584320512 |    6s
      17 |    1439 | Apply bit flip properties                               |     17584320512 |    6s
      18 |    1548 | Apply bit flip properties                               |     17584320512 |    6s
      19 |    1657 | Apply bit flip properties                               |     12307929088 |    4s
      19 |    1657 | (1. guess: Sum(a8) = 256)                               |     12307929088 |    4s
      19 |    1657 | Apply Sum(a8) and all bytes bitflip properties          |     10340759552 |    4s
      19 |    1657 | (2. guess: Sum(a8) = 192)                               |     88161214464 |   31s
      20 |    1657 | Apply Sum(a8) and all bytes bitflip properties          |     70511386624 |   25s
      22 |    1657 | Brute force phase completed.  Key found: 5feedca1a129   |               0 |    0s
[+] target sector   1 key type B -- found valid key [ 5FEEDCA1A129 ]

[+] found keys:

[+] |-----|----------------|---|----------------|---|
[+] | Sec | key A          |res| key B          |res|
[+] |-----|----------------|---|----------------|---|
[+] | 000 | ffffffffffff   | D | 34aed43006e1   | H |
[+] | 001 | 98669f3dc004   | H | 5feedca1a129   | H |
[+] | 002 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 003 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 004 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 005 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 006 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 007 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 008 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 009 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 010 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 011 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 012 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 013 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 014 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 015 | ffffffffffff   | D | ffffffffffff   | D |
[+] |-----|----------------|---|----------------|---|
[=] ( D:Dictionary / S:darkSide / U:User / R:Reused / N:Nested / H:Hardnested / C:statiCnested / A:keyA )

[+] Generating binary key file
[+] Found keys have been dumped to hf-mf-B2CC0081-key-16.bin
[=] FYI! --> 0xFFFFFFFFFFFF <-- has been inserted for unknown keys where res is 0
[+] transferring keys to simulator memory (Cmd Error: 04 can occur)
[=] downloading the card content from emulator memory
[+] saved 1024 bytes to binary file hf-mf-B2CC0081-dump-22.bin
[+] saved 64 blocks to text file hf-mf-B2CC0081-dump-22.eml
[+] saved to json file hf-mf-B2CC0081-dump-22.json
[=] autopwn execution time: 70 seconds

**Comment by iceman1001** [comment]
You should ask usage related questions on the Proxmark3 forum or the discord server.
This is issues for the source code,.
