### ISSUE TITLE
Hitag sanity check checks for wrong length

### ISSUE THREAD

**Issue by henry-delaruelle** [RfidResearchGroup/proxmark3#1286]
The Hitag sanity check checks for wrong length, it checks for 6 bytes in pasword mode and 8 bytes in crypto mode, this should be 4 in password mode and 6 in crypto mode.
 
the command "lf hitag reader --21 -k 4D494B52" returns 
Wrong KEY len expected 0 or 6, got 4

The keylength 4 is correct, so the sanity check is wrong 
the same error happends with the command "lf hitag reader --23 -k 4F4E4D494B52"

Wrong KEY len expected 0 or 8, got 6

in the file cmdlfhitag.c the code should be :

// sanity checks
    if (keylen != 0 && keylen != 4) {
        PrintAndLogEx(WARNING, "Wrong KEY len expected 0 or 4, got %d", keylen);
        return PM3_EINVARG;
    }

    if (nalen != 0 && nalen != 6) {
        PrintAndLogEx(WARNING, "Wrong NR/AR len expected 0 or 6, got %d", nalen);
        return PM3_EINVARG;
    }

**Comment by iceman1001** [comment]
fixed  https://github.com/RfidResearchGroup/proxmark3/commit/59b86af1a8665250592f0f1deb03f20398125fa0  

Thanks!
