### ISSUE TITLE
Windows 10 ANSI color not working

### ISSUE THREAD

**Issue by Gator96100** [RfidResearchGroup/proxmark3#1296]
I created this issue to help me track down the reason why ANSI color support fails on some Windows 10 PCs. As I am not able to replicate this issue, I do require the help of users who have this issue.

This issue only affects people using Windows 10 with ProxSpace. WSL users are not affected.

**Symptoms:**
- No colors in the Proxmark3 client
- “strange” symbols at the start of every line, see screenshot
![grafik](https://user-images.githubusercontent.com/1360042/120214951-752ef900-c235-11eb-94f5-d83be5620267.png)

### How to help me find the cause of this issue:
I do need a lot of information about your system to find why some people are affected and others aren’t. To do this, I did create a script to automatically collect information about your: system, environment, processes, software and updates, as well as registry entries that affect your terminal. I do know that is a lot of information to share and if you are not comfortable with sharing it feel free to remove some lines of `collectinfo.txt`, just tell me if you did modify it. 

#### If you do have this issue and want to help do the following:
1. Run this command within ProxSpace:
`bash <(wget -O - 'https://www.proxmarkbuilds.org/experimental/collectinfo.sh')`
2. Make a screenshot of the output.
3. Upload the file `collectinfo.txt` somewhere (e.g. https://pastebin.com/, or attach it to this issue) or send it to me directly over Discord (Gator96100#2719).

**Comment by PercyJax** [comment]
I’ve experienced this issue as well. It seems to correlate with window maximizing and snapping, though not 100%.

**Comment by Gator96100** [comment]
> 
> 
> I’ve experienced this issue as well. It seems to correlate with window maximizing and snapping, though not 100%.

Thank you so much! Resizing is the problem. I can replicate the issue now.

**Comment by Gator96100** [comment]
#1297 should fix it
