### ISSUE TITLE
H10302 not decoding properly

### ISSUE THREAD

**Issue by SpeedGP** [RfidResearchGroup/proxmark3#1302]
Hi, having some issues decoding a tag. Is there a way to force pm3 wiegand to decode to a specific format? The card number is 18822 and I believe the encoding is H10302.

[+] [C15001 ] HID KeyScan 36-bit FC: 129 CN: 9752 OEM: 704 parity ( fail )
[+] [S12906 ] HID Simplex 36-bit FC: 176 CN: 8463896 Issue: 0 parity ( fail )
[+] [Sie36 ] HID 36-bit Siemens FC: 180353 CN: 9752 parity ( fail )
[=] found 3 matching formats
[+] DemodBuffer:
[+] 1D555AA69556555965A55A55

[=] raw: 000000000000003d81024c30

Thanks for the help!

**Comment by iceman1001** [comment]
Closing since its a use question.  Use the rfid hacking discord to ask questions or PM3 forum.
