### ISSUE TITLE
unable to program badge numbers 

### ISSUE THREAD

**Issue by jithan10** [RfidResearchGroup/proxmark3#1308]
Things to try before submitting bug report
read the troubleshooting guide

Compilation problems
Try compiling with verbose. make VERBOSE=1 with main makefile or make V=1 with cmake.

flashing problems
Have you followed the instructions properly? ie, flashed bootrom seperately first if you are going from Offical repo to RRG/Iceman repo.

Last login: Thu Jun 10 11:22:45 on ttys002
jy@jts-MacBook-Pro ~ % brew tap RfidResearchGroup/proxmark3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
maturin tmuxp
==> Updated Formulae
Updated 45 formulae.

jy@jts-MacBook-Pro ~ % export HOMEBREW_PROXMARK3_PLATFORM=xxxxxx
jy@jts-MacBook-Pro ~ % brew install proxmark3
Warning: rfidresearchgroup/proxmark3/proxmark3 4.9237 is already installed and up-to-date.
To reinstall 4.9237, run:
brew reinstall proxmark3
jy@jts-MacBook-Pro ~ % brew reinstall proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/v4.9237.t
Already downloaded: /Users/jy/Library/Caches/Homebrew/downloads/8d6348999984c4412e8cb081c1b3fa53b78eb10062c506ff1d8e16344dd22763--proxmark3-4.9237.tar.gz
==> Reinstalling rfidresearchgroup/proxmark3/proxmark3
==> make clean
==> make all BREW_PREFIX=/usr/local PLATFORM=PM3RDV4
==> make install PREFIX=/usr/local/Cellar/proxmark3/4.9237 BREW_PREFIX=/usr/loca
==> Install success!
==> The latest bootloader and firmware binaries are ready and waiting in the cur
🍺 /usr/local/Cellar/proxmark3/4.9237: 582 files, 16.5MB, built in 1 minute 22 seconds
jy@jts-MacBook-Pro ~ % brew upgrade --fetch-HEAD proxmark3

Warning: rfidresearchgroup/proxmark3/proxmark3 4.9237 already installed
jy@jts-MacBook-Pro ~ % pm3-flash-all

[=] Session log /Users/jy/.proxmark3/log_20210610.txt
[=] Loading Preferences...
[+] loaded from JSON file /Users/jy/.proxmark3/preferences.json
[+] About to use the following files:
[+] /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/bootrom.elf
[+] /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/fullimage.elf
[+] Waiting for Proxmark3 to appear on /dev/tty.usbmodemiceman1
🕑 59 found
[=] Available memory on this board: 512K bytes

[=] Permitted flash range: 0x00100000-0x00180000
[+] Loading ELF file /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/bootrom.elf
[+] Loading usable ELF segments:
[+] 0: V 0x00100000 P 0x00100000 (0x00000200->0x00000200) [R X] @0x94
[+] 1: V 0x00200000 P 0x00100200 (0x00000d50->0x00000d50) [R X] @0x298

[+] Loading ELF file /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/fullimage.elf
[+] Loading usable ELF segments:
[+] 0: V 0x00102000 P 0x00102000 (0x00043430->0x00043430) [R X] @0x94
[+] 1: V 0x00200000 P 0x00145430 (0x00001314->0x00001314) [RW ] @0x434c4
[=] Note: Extending previous segment from 0x43430 to 0x44744 bytes

[+] Flashing...
[+] Writing segments for file: /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/bootrom.elf
[+] 0x00100000..0x001001ff [0x200 / 1 blocks]
. OK
[+] 0x00100200..0x00100f4f [0xd50 / 7 blocks]
....... OK

[+] Writing segments for file: /usr/local/Cellar/proxmark3/4.9237/bin/../share/proxmark3/firmware/fullimage.elf
[+] 0x00102000..0x00146743 [0x44744 / 548 blocks]
...................................................................
@@@ @@@@@@@ @@@@@@@@ @@@@@@@@@@ @@@@@@ @@@ @@@
@@! !@@ @@! @@! @@! @@! @@! @@@ @@!@!@@@
!!@ !@! @!!!:! @!! !!@ @!@ @!@!@!@! @!@@!!@!
!!: :!! !!: !!: !!: !!: !!! !!: !!!
: :: :: : : :: ::: : : : : : :: :
. .. .. . . .. ... . . . . . .. .
...................................................................
........................................... OK

[+] All done

Have a nice day!
jy@jts-MacBook-Pro ~ % pm3
[=] Session log /Users/jy/.proxmark3/log_20210610.txt
[=] Loading Preferences...
[+] loaded from JSON file /Users/jy/.proxmark3/preferences.json
[=] Using UART port /dev/tty.usbmodemiceman1
[=] Communicating with PM3 over USB-CDC

██████╗ ███╗ ███╗█████╗
██╔══██╗████╗ ████║╚═══██╗
██████╔╝██╔████╔██║ ████╔╝
██╔═══╝ ██║╚██╔╝██║ ╚══██╗ ❄️ iceman@icesql.net
██║ ██║ ╚═╝ ██║█████╔╝ https://github.com/rfidresearchgroup/proxmark3/
╚═╝ ╚═╝ ╚═╝╚════╝ Release v4.9237 - Ice Coffee ☕

[ Proxmark3 RFID instrument ]

[ CLIENT ]
client: RRG/Iceman/master/release (git)
compiled with Clang/LLVM Apple LLVM 12.0.5 (clang-1205.0.22.9) OS:OSX ARCH:x86_64

[ PROXMARK3 RDV4 ]
external flash: present
smartcard reader: present

[ PROXMARK3 RDV4 Extras ]
FPC USART for BT add-on support: absent

[ ARM ]
bootrom: RRG/Iceman/master/release (git)
os: RRG/Iceman/master/release (git)
compiled with GCC 10.2.1 20201103 (release)

[ FPGA ]
LF image built for 2s30vq100 on 2020-02-22 at 12:51:14
HF image built for 2s30vq100 on 2020-01-12 at 15:31:16

[ Hardware ]
--= uC: AT91SAM7S512 Rev A
--= Embedded Processor: ARM7TDMI
--= Nonvolatile Program Memory Size: 512K bytes, Used: 288579 bytes (55%) Free: 235709 bytes (45%)
--= Second Nonvolatile Program Memory Size: None
--= Internal SRAM Size: 64K bytes
--= Architecture Identifier: AT91SAM7Sxx Series
--= Nonvolatile Program Memory Type: Embedded Flash Memory

[usb] pm3 --> hid clone -w H10301 --fc 118 --cn 1603
help This help. Use ' help' for details of a particular command.
auto Automated detection process for unknown tags
analyse { Analyse utils... }
data { Plot window / data buffer manipulation... }
emv { EMV ISO-14443 / ISO-7816... }
hf { High frequency commands... }
hw { Hardware commands... }
lf { Low frequency commands... }
mem { Flash Memory manipulation... }
reveng { CRC calculations from RevEng software }
sc { Smart card ISO-7816 commands... }
script { Scripting commands }
trace { Trace manipulation... }
wiegand { Wiegand format manipulation... }

hints Turn hints on / off
pref Edit preferences
msleep Add a pause in milliseconds
rem Add a text line in log file
quit
exit Exit program
[usb] pm3 --> hid clone -w H10301 --fc 118 --cn 160
help This help. Use ' help' for details of a particular command.
auto Automated detection process for unknown tags
analyse { Analyse utils... }
data { Plot window / data buffer manipulation... }
emv { EMV ISO-14443 / ISO-7816... }
hf { High frequency commands... }
hw { Hardware commands... }
lf { Low frequency commands... }
mem { Flash Memory manipulation... }
reveng { CRC calculations from RevEng software }
sc { Smart card ISO-7816 commands... }
script { Scripting commands }
trace { Trace manipulation... }
wiegand { Wiegand format manipulation... }

hints Turn hints on / off
pref Edit preferences
msleep Add a pause in milliseconds
rem Add a text line in log file
quit
exit Exit program
[usb] pm3 --> lf hid clone
Clone HID to T55x7. Tag must be on antenna!

Usage: lf hid clone [h] [l] ID
Options:
h - This help
l - 84bit ID
ID - HID id
Examples:
lf hid clone 2006ec0c86
lf hid clone l 2006ec0c86
[usb] pm3 --> lf hid clone -w H10301 --fc 118 --cn 1603
[=] Preparing to clone HID tag with ID: 000000000
[+] Done
[usb] pm3 --> Usage: lf hid clone [h] [l] ID
help This help. Use ' help' for details of a particular command.
auto Automated detection process for unknown tags
analyse { Analyse utils... }
data { Plot window / data buffer manipulation... }
emv { EMV ISO-14443 / ISO-7816... }
hf { High frequency commands... }
hw { Hardware commands... }
lf { Low frequency commands... }
mem { Flash Memory manipulation... }
reveng { CRC calculations from RevEng software }
sc { Smart card ISO-7816 commands... }
script { Scripting commands }
trace { Trace manipulation... }
wiegand { Wiegand format manipulation... }

hints Turn hints on / off
pref Edit preferences
msleep Add a pause in milliseconds
rem Add a text line in log file
quit
exit Exit program
[usb] pm3 --> Usage: lf hid clone [1] [1] [1]
help This help. Use ' help' for details of a particular command.
auto Automated detection process for unknown tags
analyse { Analyse utils... }
data { Plot window / data buffer manipulation... }
emv { EMV ISO-14443 / ISO-7816... }
hf { High frequency commands... }
hw { Hardware commands... }
lf { Low frequency commands... }
mem { Flash Memory manipulation... }
reveng { CRC calculations from RevEng software }
sc { Smart card ISO-7816 commands... }
script { Scripting commands }
trace { Trace manipulation... }
wiegand { Wiegand format manipulation... }

hints Turn hints on / off
pref Edit preferences
msleep Add a pause in milliseconds
rem Add a text line in log file
quit
exit Exit program
[usb] pm3 --> lf hid clone -w H10301 --fc 118 --cn 1603
[=] Preparing to clone HID tag with ID: 000000000
[+] Done
[usb] pm3 --> hid clone
help This help. Use ' help' for details of a particular command.
auto Automated detection process for unknown tags
analyse { Analyse utils... }
data { Plot window / data buffer manipulation... }
emv { EMV ISO-14443 / ISO-7816... }
hf { High frequency commands... }
hw { Hardware commands... }
lf { Low frequency commands... }
mem { Flash Memory manipulation... }
reveng { CRC calculations from RevEng software }
sc { Smart card ISO-7816 commands... }
script { Scripting commands }
trace { Trace manipulation... }
wiegand { Wiegand format manipulation... }

hints Turn hints on / off
pref Edit preferences
msleep Add a pause in milliseconds
rem Add a text line in log file
quit
exit Exit program
[usb] pm3 --> lf hid clone
Clone HID to T55x7. Tag must be on antenna!

Usage: lf hid clone [h] [l] ID
Options:
h - This help
l - 84bit ID
ID - HID id
Examples:
lf hid clone 2006ec0c86
lf hid clone l 2006ec0c86
[usb] pm3 --> hints
[=] Hints are OFF
[usb] pm3 --> hints
[=] Hints are OFF
[usb] pm3 --> hints
[=] Hints are OFF
[usb] pm3 --> lf hid clone
Clone HID to T55x7. Tag must be on antenna!

Usage: lf hid clone [h] [l] ID
Options:
h - This help
l - 84bit ID
ID - HID id
Examples:
lf hid clone 2006ec0c86
lf hid clone l 2006ec0c86
[usb] pm3 --> lf hid clonepm3-flash-all

Describe the bug

missing commands 

lf hid clone -r 2006ec0c86 -> write raw value (HID 10301 26 bit)
lf hid clone -r 2e0ec00c87 -> write raw value (HID Corporate 35 bit)
lf hid clone -r 01f0760643c3 -> write raw value (HID P10001 40 bit)
lf hid clone -r 01400076000c86 -> write raw value (HID Corporate 48 bit)
lf hid clone -w H10301 --fc 118 --cn 1603 -> write raw value (HID 10301 26 bit)
lf hid clone -w H10301 --fc 118 --cn 1603 --q5 -> HID 10301 26 bit, encode for Q5/T5555 tag
lf hid clone -w H10301 --fc 118 --cn 1603 --em -> HID 10301 26 bit, encode for EM4305/4469

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

usb] pm3 --> lf hid clone -w H10301 --fc 118 --cn 1603
[=] Preparing to clone HID tag
[+] [H10301] - HID H10301 26-bit; FC: 118 CN: 1603 parity: valid
[=] Done

Screenshots

Additional context

I used the same procedure a few months ago, and it worked fine. I'm unsure if my device is missing repositories or if I'm doing something wrong. it looks like something is missing. I v reinstalled everything multiple times yesterday.

**Comment by iceman1001** [comment]
This sounds like a issue for the https://github.com/RfidResearchGroup/homebrew-proxmark3 repo.
Did you follow the instructions there?

You seem to have done a brew install of the release which is a year old.

**Comment by jithan10** [comment]
yes, I followed the instructions from  https://github.com/RfidResearchGroup/homebrew-proxmark3 I repeated it still not working

**Comment by mwalker33** [comment]
It look like your client is an old client.

your command of :  lf hid clone -w H10301 --fc 118 --cn 1603
is correct, but your output from "lf hid clone" help is old.
it should look more like
```
usage:
    lf hid clone [-h] [-w <format>] [--fc <dec>] [--cn <dec>] [-i <dec>] [-o <dec>] [-r <hex>]... [--q5] [--em]
                    [--bin <bin>]

options:
    -h, --help                     This help
    -w, --wiegand <format>         see `wiegand list` for available formats
    --fc <dec>                     facility code
    --cn <dec>                     card number
    -i <dec>                       issue level
    -o, --oem <dec>                OEM code
    -r, --raw <hex>                raw bytes
    --q5                           optional - specify writing to Q5/T5555 tag
    --em                           optional - specify writing to EM4305/4469 tag
    --bin <bin>                    Binary string i.e 0001001001

examples/notes:
    lf hid clone -r 2006ec0c86                           -> write raw value (HID 10301 26 bit)
    lf hid clone -r 2e0ec00c87                           -> write raw value (HID Corporate 35 bit)
    lf hid clone -r 01f0760643c3                         -> write raw value (HID P10001 40 bit)
    lf hid clone -r 01400076000c86                       -> write raw value (HID Corporate 48 bit)
    lf hid clone -w H10301 --fc 118 --cn 1603            -> write raw value (HID 10301 26 bit)
    lf hid clone -w H10301 --fc 118 --cn 1603 --q5       -> HID 10301 26 bit, encode for Q5/T5555 tag
    lf hid clone -w H10301 --fc 118 --cn 1603 --em       -> HID 10301 26 bit, encode for EM4305/4469
```

Any chance you are somehow running an older proxmark client ?

**Comment by iceman1001** [comment]
I suggest you ask your question on how to install latest master using homebrew on OSX on discord.   

You need to install latest master.  Look into `--HEAD`  instructions is the referenced repo

Closing.
