### ISSUE TITLE
iClass global HID key missing in wordlist?

### ISSUE THREAD

**Issue by Ten0** [RfidResearchGroup/proxmark3#1311]
It looks like the HID global iClass key (https://ss23.github.io/hid-iclass-key/) is not present in the `client/dictionaries/iclass_default_keys.dic` file, although it is present in the documentation: https://github.com/RfidResearchGroup/proxmark3/blob/899f269a99fe8dce5321d082f88c742ff529566d/doc/cheatsheet.md#iclass

However a very similar key is in there: https://github.com/RfidResearchGroup/proxmark3/blob/899f269a99fe8dce5321d082f88c742ff529566d/client/dictionaries/iclass_default_keys.dic#L6

I suspect this is intentional, but just wanted to make sure and understand why :)

Thanks,

**Comment by iceman1001** [comment]
it is intentional,  and you would need to read the paper _"heart of darkness"_ to understand why
