### ISSUE TITLE
make style

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#132]
**Describe the bug**
running _make style_  will generate lots of rows "no such file or directory".

**To Reproduce**
1. make style

**Expected behavior**
No repeating lines

**Screenshots**
```
find . \( -name "*.[ch]" -or -name "*.cpp" \) -exec astyle --formatted --mode=c --suffix=none \
            --indent=spaces=4 --indent-switches --indent-preprocessor \
            --keep-one-line-blocks --max-instatement-indent=60 \
            --style=google --pad-oper --unpad-paren --pad-header \
            --align-pointer=name {} \;
find: astyle: No such file or directory
find: astyle: No such file or directory
find: astyle: No such file or directory
find: astyle: No such file or directory
```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional context**

**Comment by iceman1001** [comment]
ok,  missing package..
https://www.howtoinstall.co/en/ubuntu/trusty/astyle/

**Comment by doegox** [comment]
https://github.com/RfidResearchGroup/proxmark3/commit/d21302d39c309a3aadda27cb9f6ddf66b05ebf02

**Comment by merlokk** [comment]
needs to add astyle to proxspace)

**Comment by vratiskol** [comment]
**For proxspace user:**
`pacman -S mingw-w64-x86_64-astyle`
