### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform

### ISSUE THREAD

**Issue by BA7LWN** [RfidResearchGroup/proxmark3#1399]
D:\Program Files\RRG\client>proxmark3.exe
[=] Session log D:/Program Files/RRG/client/.proxmark3/logs/log_20210729.txt
[=] Running in OFFLINE mode. Check "proxmark3.exe -h" if it's not what you want.

  圹圹圹?圹刍   圹刍圹圹刍
  圹赏哇刍圹圹?圹圹喝屯哇刍
  圹圹圹杉圹邵圹凵圹?圹圹杉
  圹赏屯?圹喝圹杉圹?韧哇刍
  圹?    圹?韧?圹痕圹圹杉       Iceman
  韧?    韧?    韧既屯屯?    bleeding edge

  https://github.com/rfidresearchgroup/proxmark3/

[=] Creating initial preferences file
[=] Saving preferences...
[+] saved to json file D:/Program Files/RRG/client/.proxmark3/preferences.json
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

D:\Program Files\RRG\client>

**Comment by iceman1001** [comment]
Looks like you downloaded some kind of pre-compiled binary distribution.  You need to ask there about what they did or not did. 

You can follow the instructions in this repo to build it yourself.
