### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by ikarus23** [RfidResearchGroup/proxmark3#140]
![screenshot_2019-03-19_08-57-26](https://user-images.githubusercontent.com/1389516/54589151-249c9e00-4a25-11e9-9a52-17b9f9a538b5.png)

Also: rdv4.0 vs. Rdv4.0 vs. RDV40 vs. RDV4? I think I've seen all.

**Comment by RfidResearchGroup** [comment]
well spotted

**Comment by iceman1001** [comment]
The offical name on pcb is  **RDV4.0**  
RDV40 vs RDV4 is more of lazy shortcuts in a sense.   The capital letters vs Camelcase alt lowcase is ppl who doesn't want to scream?
