### ISSUE TITLE
[idea] Make hardnested the same as nested

### ISSUE THREAD

**Issue by ikarus23** [RfidResearchGroup/proxmark3#141]
From an users perspective, I would really like if the hardnested command works as same as the nested. Just run the command, get all the keys and additional options to dump them into a file or write them to the emulator memory, etc.

**Comment by iceman1001** [comment]
Feel free to add it. 
I already have my hard_autopwn script so my needs are fulfilled.

**Comment by ikarus23** [comment]
> Feel free to add it.

I'm not sure if I will find the time to. It's not request, it's just an idea to improve the proxmark.

> I already have my hard_autopwn script so my needs are fulfilled.

I'm happy for you.
Sharing is caring ;) (also not a request)

**Comment by doegox** [comment]
`hf mf autopwn` is filling this void now

**Comment by ikarus23** [comment]
Thank you! I love where this project is going!

**Comment by iceman1001** [comment]
I think we all feel the love.  There is a good feeling going on here.
