### ISSUE TITLE
ATS have crc bytes at the end

### ISSUE THREAD

**Issue by merlokk** [RfidResearchGroup/proxmark3#1421]
```
[usb] pm3 --> hf 14a read
[+]  UID: 04 xx xx xx xx xx xx
[+] ATQA: 03 44
[+]  SAK: 20 [1]
[+]  ATS: 08 75 77 81 02 63 72 64 A1 F4
```
A1 F4 - crc

**Comment by iceman1001** [comment]
yeah,   other commands printing ATS has that marked.  Like `sc info` etc.
Not super important but for consistency around the pm3 client it would be nice to unify it.
