### ISSUE TITLE
cppcheck cmdhfmfhard.c redundant assignment

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#1496]
In cmdhfmfhard.c
```c
        if (!initialize) {
            uint16_t num_sampled_nonces = resp.oldarg[2];
            uint8_t *bufp = resp.data.asBytes;
            for (uint16_t i = 0; i < num_sampled_nonces; i += 2) {
```
![image](https://user-images.githubusercontent.com/60773/132072523-c5245b28-bfaf-43c4-91b0-fb7ec3c9d1b4.png)

Indeed resp is declared but not initialized.
Even memsetting it doesn't fix the logic as we're looping on it.
I don't know what should be the logic here...

**Comment by iceman1001** [comment]
:) can we make a NULL check for it?

Ps.
  @pwpiwi  would be better at it
