### ISSUE TITLE
ISO15693 Restore Not Working

### ISSUE THREAD

**Issue by msoose** [RfidResearchGroup/proxmark3#1499]
**Describe the bug**
When using `hf 15 restore`, none of the blocks nor the UID are written

**To Reproduce**
1. Dump existing card
2. Restore to new card
3. Dump or read a block of new card
4. No block data has changed

**Expected behavior**
Block data and UID should match the restored file

**Additional context**
Impacts latest master and previous tagged release

EDIT: Another source indicating issue @ http://www.proxmark.org/forum/viewtopic.php?id=9651

**Comment by iceman1001** [comment]
... A bit too little context and data to be useful.

outputs,  which card,  which device,  etc etc

**Comment by doegox** [comment]
should be fixed, please test

**Comment by msoose** [comment]
For posterity, confirming this is resolved.
