### ISSUE TITLE
[idea] iCopy-X Support

### ISSUE THREAD

**Issue by chrisrock1984** [RfidResearchGroup/proxmark3#1536]
**Is your feature request related to a problem? Please describe.**
Support for the new release iCopy-X

**Describe the solution you'd like**
Using this repos for the iCopy-X would be nice. There are many bugs in the existing iCopy-X firmware

**Describe alternatives you've considered**
using the original firmware is not an alternative as it is really unstable and not usable

**Additional context**

**Comment by doegox** [comment]
iCopy-X internal proxmark3 is already supported by the current repo, but the problem is that there is currently no alternative to the proprietary GUI, which is made for an older pm3 fw with the older command syntax.
