### ISSUE TITLE
FPC - adapt timeout

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#159]
Project FPC comms
https://github.com/RfidResearchGroup/proxmark3/projects/5

Adapt timeout in current code so it can be adjusted for the slower speed or higher speeds without recompiling.

**Comment by iceman1001** [comment]
ok,  fast search for **WaitForResponseTimeout(CMD_**   gives 166hits.
The timeouts is kind of random or a expected execution time on device side before returning a ACK.
random in the sense, "_if it takes more than 2 seconds, we failed_".  Like a guess.  The client usually doesn't know any reason for failures.

**Comment by doegox** [comment]
I think we sorted out all timing problems now, let's close it
