### ISSUE TITLE
[!!] No port found

### ISSUE THREAD

**Issue by elijahlimas123** [RfidResearchGroup/proxmark3#1609]
***Things to try before submitting bug report***
read the [troubleshooting guide](/doc/md/Installation_Instructions/Troubleshooting.md)

***Compilation problems***
Try compiling with verbose.  `make VERBOSE=1` with main makefile or `make V=1` with cmake.

***flashing problems***
Have you followed the instructions properly?  ie,  flashed bootrom seperately first if you are going from Offical repo to RRG/Iceman repo.

-

**Describe the bug**
running Proxmark3 Easy on a MacBook air. the MacBook will only detect the Proxmark3 mark when the Proxmark is in boot loader mode, and even then it is hit or miss. the command "pm3 --list" returns "[!!] No port found"

**To Reproduce**
hold proxmark3 button as you plug it in to MacBook Air to enter boot loader mode.
make sure it is detected with system_profiler SPUSBDataType 
once detected use command "pm3-flash-all"
it returns what is shown in the screenshot.

**Expected behavior**
I expected to run the "pm3-flash-all" command and have the Proxmark3 Easy be detected at /dev/tty.usbmodemiceman1

**Screenshots**

![Screen Shot 2022-02-24 at 4 46 17 PM](https://user-images.githubusercontent.com/100377134/155613213-bae4250b-a69e-40e0-81b6-865f1f1c0467.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur version 11.6.4
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version
 - hw status
 - data tune

**Additional context**

**Comment by iceman1001** [comment]
... which device do you have vs which compiled version of the firmware you flashed?

**Comment by elijahlimas123** [comment]
I have the Proxmark3 Easy from dangerous things I ordered it a week ago (beyond that I don't know how to tell which device I have), I flashed Release v4.14831 - Frostbit
thanks for the quick response

**Comment by iceman1001** [comment]
My guess you didn't follow instructions and didn't compile a firmware/client for your device.
That would be a user-issue and not a issue for this repo.  Ask questions in the Pm3 forum or the discord.

**Comment by elijahlimas123** [comment]
thank you!
