### ISSUE TITLE
Dumps go to working directory, dispite `prefs set savepaths`

### ISSUE THREAD

**Issue by non-bin** [RfidResearchGroup/proxmark3#1624]
## Description
The `savepaths` preference has no effect, and all dumps, etc. are saved to the working directory.

## Reproduce
1. Set a save path (eg. `prefs set savepaths --dump ~/pm3/saves -c`)
2. Generate a file (eg. `lf t5 dump`)
3. Check where it ended up (probably in the wd)

## Expected Behavior
Files should be saved in the path specified with the `prefs` command

## Environment
 - Windows 11 with Proxspace (They claim it's a pm3 client bug)
 - PM3 Easy from dngr.us/pm3 (can post more if relavent)

## Additional Context
[Issue posted to the proxspace repo](https://github.com/Gator96100/ProxSpace/issues/49)

**Comment by iceman1001** [comment]
not implemented,   feel free to contribute!
