### ISSUE TITLE
Mifare Classic 1K  Magic Gen 1a card bricked after writing with `hf mf cload

### ISSUE THREAD

**Issue by uspilot** [RfidResearchGroup/proxmark3#1656]
**Describe the bug**
Mifare Classic 1K Magic Gen 1a card bricked after writing with `hf mf cload`
**To Reproduce**
1. Place working Magic Gen1 card on PM3 device:  `pm3 --> hf search`
2. Write card: `pm3 --> hf mf cload -f hf-mf-2F64EF3E-dump-1`
3. No error
4. Check card: `pm3 --> hf search`
5. Can't read card

**Expected behavior**
Card must be working

**Screenshots**
`[usb] pm3 --> hf search`
 🕐  Searching for ISO14443-A tag...          
[+]  UID: 1A B6 F8 16 
[+] ATQA: 00 04
[+]  SAK: 08 [2]
[+] Possible types:
[+]    MIFARE Classic 1K
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Magic capabilities : Gen 1a
[+] Prng detection: weak
[#] Auth error

[+] Valid ISO 14443-A tag found

`[usb] pm3 --> hf mf cload -f hf-mf-2F64EF3E-dump-1`
[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-1
[=] Copying to magic gen1a card
[=] .................................................................

[+] Card loaded 64 blocks from file
[=] Done!

`[usb] pm3 --> hf search`
 🕕  Searching for ISO14443-A tag...[#] BCC0 incorrect, got 0x00, expected 0x33
[#] Aborting
[!] ⚠️  No known/supported 13.56 MHz tags found

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version: 10.15.6 (19G2021)
`[usb] pm3 --> hw version`

 [ Proxmark3 RFID instrument ]

 [ CLIENT ]
  RRG/Iceman/master/v4.14831-2-g4e78034a6 2022-01-11 22:33:23
  compiled with............. Clang/LLVM Apple LLVM 12.0.0 (clang-1200.0.32.29)
  platform.................. OSX / x86_64
  Readline support.......... present
  QT GUI support............ present
  native BT support......... absent
  Python script support..... present
  Lua SWIG support.......... present
  Python SWIG support....... present

 [ PROXMARK3 ]
  firmware.................. PM3 GENERIC

 [ ARM ]
  bootrom: RRG/Iceman/master/v4.14831-2-g4e78034a6 2022-01-11 22:34:09
       os: RRG/Iceman/master/v4.14831-2-g4e78034a6 2022-01-11 22:34:30
  compiled with GCC 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

 [ FPGA ] 
  LF image built for 2s30vq100 on 2020-07-08 at 23:08:07
  HF image built for 2s30vq100 on 2020-07-08 at 23:08:19
  HF FeliCa image built for 2s30vq100 on 2020-07-08 at 23:08:30

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Internal SRAM size: 64K bytes
  --= Architecture identifier: AT91SAM7Sxx Series
  --= Embedded flash memory 512K bytes ( 53% used )

`[usb] pm3 --> hw status`
[#] Memory
[#]   BigBuf_size............. 44344
[#]   Available memory........ 44084
[#] Tracing
[#]   tracing ................ 0
[#]   traceLen ............... 200
[#] Current FPGA image
[#]   mode.................... HF FeliCa image built for 2s30vq100 on 2020-07-08 at 23:08:30
[#] LF Sampling config
[#]   [q] divisor............. 95 ( 125.00 kHz )
[#]   [b] bits per sample..... 8
[#]   [d] decimation.......... 1
[#]   [a] averaging........... yes
[#]   [t] trigger threshold... 0
[#]   [s] samples to skip..... 0 
[#] 
[#] LF T55XX config
[#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
[#]            mode            |start|write|write|write| read|write|write
[#]                            | gap | gap |  0  |  1  | gap |  2  |  3
[#] ---------------------------+-----+-----+-----+-----+-----+-----+------
[#] fixed bit length (default) |  31 |  20 |  18 |  50 |  15 | N/A | N/A | 
[#]     long leading reference |  31 |  20 |  18 |  50 |  15 | N/A | N/A | 
[#]               leading zero |  31 |  20 |  18 |  40 |  15 | N/A | N/A | 
[#]    1 of 4 coding reference |  31 |  20 |  18 |  34 |  15 |  50 |  66 | 
[#] 
[#] HF 14a config
[#]   [a] Anticol override.... std    ( follow standard )
[#]   [b] BCC override........ std    ( follow standard )
[#]   [2] CL2 override........ std    ( follow standard )
[#]   [3] CL3 override........ std    ( follow standard )
[#]   [r] RATS override....... std    ( follow standard )
[#] Transfer Speed
[#]   Sending packets to client...
[#]   Time elapsed................... 500ms
[#]   Bytes transferred.............. 262144
[#]   Transfer Speed PM3 -> Client... 524288 bytes/s
[#] Various
[#]   Max stack usage......... 4944 / 8480 bytes
[#]   Debug log level......... 1 ( error )
[#]   ToSendMax............... 10
[#]   ToSend BUFFERSIZE....... 2308
[#]   Slow clock.............. 31330 Hz
[#] Installed StandAlone Mode
[#]   LF HID ProxII bruteforce - aka Proxbrute (Brad Antoniewicz)
[#] 

`[usb] pm3 --> data tune`
[=] ---------- Reminder ------------------------
[=] `hw tune` doesn't actively tune your antennas,
[=] it's only informative.
[=] Measuring antenna characteristics, please wait...
 🕓   9
[=] ---------- LF Antenna ----------
[+] LF antenna: 19.40 V - 125.00 kHz
[+] LF antenna: 13.72 V - 134.83 kHz
[+] LF optimal: 23.38 V - 115.38 kHz
[+] Approx. Q factor (*): 5.6 by frequency bandwidth measurement
[+] Approx. Q factor (*): 6.8 by peak voltage measurement
[+] LF antenna is OK
[=] ---------- HF Antenna ----------
[+] HF antenna: 25.34 V - 13.56 MHz
[+] Approx. Q factor (*): 7.4 by peak voltage measurement
[+] HF antenna is OK

(*) Q factor must be measured without tag on the antenna

[+] Displaying LF tuning graph. Divisor 88 (blue) is 134.83 kHz, 95 (red) is 125.00 kHz.

**Additional context**
I tried this procedure with 3 different Gen1 card and got the same result with each card. All of them seems to be bricked.

`[usb] pm3 --> hf mf view -f hf-mf-2F64EF3E-dump-1`
[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-1

[=] ----+-------------------------------------------------+-----------------
[=] blk | data                                            | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 34 00 07 00 00 D1 82 BB 53 00 00 00 00 00 07 00 | 4.......S.......
[=]   1 | 01 00 F4 71 09 67 64 15 07 13 00 1B 30 2E 02 15 | ...q.gd.....0... 
[=]   2 | 00 DD B7 42 88 8D D4 01 A2 B1 25 A4 F7 4A 6F B0 | ...B......%..Jo. 
[=]   3 | A0 A1 A2 A3 A4 A5 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......
[=]   4 | 25 53 9A 91 AC 02 15 00 A0 B0 A1 ED A8 AD BA 1A | %S.............. 
[=]   5 | 92 E4 13 C7 CF 56 A5 9F BF 42 0B D4 FF FF FF FF | .....V...B...... 
[=]   6 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   7 | A0 A1 A2 A3 A4 A5 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......
[=]   8 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   9 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  11 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  12 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  13 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  14 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  15 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  16 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  17 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  18 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  19 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  21 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  22 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  23 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  24 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  25 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  26 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  27 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  28 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  29 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  31 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  32 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  33 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  34 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  35 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  36 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  37 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  38 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  39 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  41 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  42 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  43 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  44 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  45 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  46 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  47 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  48 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  49 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  50 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  51 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  52 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  53 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  54 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  55 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  56 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  57 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  58 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  59 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  61 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  62 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  63 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=] ----+-------------------------------------------------+-----------------

**Comment by mwalker33** [comment]
A few questions.
1. Given that its a magic gen1a card, is it really bricked, or just not working.  
I made a gen1a card with that data and got an error on normal commands, but could write a valid block 0 back and the card still works.

2. There seems to be something wrong with the block 0 data.
While I have only had a very quick look... the error I got was 
```
[usb] pm3 --> hf 14a info
[#] BCC0 incorrect, got 0x00, expected 0x33
[#] Aborting
```
So I change the 5th byte in block 0 to 0x33
```
original : hf mf csetblk --blk 0 -d 3400070000D182BB5300000000000700
updated  : hf mf csetblk --blk 0 -d 3400070033D182BB5300000000000700
```
Which then allows the info to work
```
[usb] pm3 --> hf 14a info

[+]  UID: 34 00 07 00
[+] ATQA: BB 82
[+]  SAK: D1 [2]
[+] Possible types:
[+]    MIFARE Plus 4K in SL2
[=] proprietary non iso14443-4 card found, RATS not supported
```
But there could be more not 100% correct with that block 0.
Was the original card a 4 byte or 7 Byte UID ?

**Comment by uspilot** [comment]
```
[usb] pm3 --> hf 14a info

[+]  UID: 2F 64 EF 3E 
[+] ATQA: 00 44
[+]  SAK: 08 [2]
[+] Possible types:
[+]    MIFARE Classic 1K CL2
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: hard
[#] Auth error
```

Dump has been generated with `hf mf autopwn` command

```
[usb] pm3 --> hf mf autopwn

[!] ⚠️  no known key was supplied, key recovery might fail
[+] loaded 42 keys from hardcoded default array
[=] running strategy 1
[=] Chunk 0.6s | found 32/32 keys (42)
[+] target sector   0 key type A -- found valid key [ A0A1A2A3A4A5 ] (used for nested / hardnested attack)
[+] target sector   0 key type B -- found valid key [ B0B1B2B3B4B5 ]
[+] target sector   1 key type A -- found valid key [ A0A1A2A3A4A5 ]
[+] target sector   1 key type B -- found valid key [ B0B1B2B3B4B5 ]
[+] target sector   2 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   2 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   3 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   3 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   4 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   4 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   5 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   5 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   6 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   6 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   7 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   7 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   8 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   8 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   9 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector   9 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  10 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  10 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  11 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  11 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  12 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  12 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  13 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  13 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  14 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  14 key type B -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  15 key type A -- found valid key [ FFFFFFFFFFFF ]
[+] target sector  15 key type B -- found valid key [ FFFFFFFFFFFF ]

[+] found keys:

[+] |-----|----------------|---|----------------|---|
[+] | Sec | key A          |res| key B          |res|
[+] |-----|----------------|---|----------------|---|
[+] | 000 | a0a1a2a3a4a5   | D | b0b1b2b3b4b5   | D |
[+] | 001 | a0a1a2a3a4a5   | D | b0b1b2b3b4b5   | D |
[+] | 002 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 003 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 004 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 005 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 006 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 007 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 008 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 009 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 010 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 011 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 012 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 013 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 014 | ffffffffffff   | D | ffffffffffff   | D |
[+] | 015 | ffffffffffff   | D | ffffffffffff   | D |
[+] |-----|----------------|---|----------------|---|
[=] ( D:Dictionary / S:darkSide / U:User / R:Reused / N:Nested / H:Hardnested / C:statiCnested / A:keyA  )


[+] Generating binary key file
[+] Found keys have been dumped to hf-mf-2F64EF3E-key-3.bin
[=] FYI! --> 0xFFFFFFFFFFFF <-- has been inserted for unknown keys where res is 0
[+] transferring keys to simulator memory (Cmd Error: 04 can occur)
[=] fast dump reported back failure w KEY A,  swapping to KEY B
[#] Cmd Error 04
[#] wrong response len 0 (expected 18)
[#] wrong response len 0 (expected 18)
[#] wrong response len 0 (expected 18)
[=] fast dump reported back failure w KEY B
[=] Dump file is PARTIAL complete
[=] downloading the card content from emulator memory
[+] saved 1024 bytes to binary file hf-mf-2F64EF3E-dump-3.bin
[+] saved 64 blocks to text file hf-mf-2F64EF3E-dump-3.eml
[+] saved to json file hf-mf-2F64EF3E-dump-3.json
[=] autopwn execution time: 2 seconds

```
```
[usb] pm3 --> hf mf view -f hf-mf-2F64EF3E-dump-3

[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-3

[=] ----+-------------------------------------------------+-----------------
[=] blk | data                                            | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 34 00 07 00 00 D1 82 BB 53 00 00 00 00 00 07 00 | 4.......S.......
[=]   1 | 01 00 F4 71 09 67 64 15 07 13 00 1B 30 2E 02 15 | ...q.gd.....0... 
[=]   2 | 00 DD B7 42 88 8D D4 01 A2 B1 25 A4 F7 4A 6F B0 | ...B......%..Jo. 
[=]   3 | A0 A1 A2 A3 A4 A5 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......
[=]   4 | 25 53 9A 91 AC 02 15 00 A0 B0 A1 ED A8 AD BA 1A | %S.............. 
[=]   5 | 92 E4 13 C7 CF 56 A5 9F BF 42 0B D4 FF FF FF FF | .....V...B...... 
[=]   6 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   7 | A0 A1 A2 A3 A4 A5 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......
[=]   8 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]   9 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  10 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  11 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  12 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  13 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  14 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  15 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  16 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  17 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  18 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  19 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  20 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  21 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  22 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  23 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  24 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  25 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  26 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  27 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  28 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  29 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  30 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  31 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  32 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  33 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  34 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  35 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  36 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  37 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  38 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  39 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  40 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  41 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  42 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  43 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  44 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  45 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  46 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  47 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  48 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  49 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  50 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  51 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  52 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  53 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  54 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  55 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  56 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  57 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  58 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  59 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=]  60 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  61 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  62 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ 
[=]  63 | FF FF FF FF FF FF FF 07 80 00 FF FF FF FF FF FF | ................
[=] ----+-------------------------------------------------+-----------------

```
```
[usb] pm3 --> hf mf rdsc -k a0a1a2a3a4a5 -s 0 -v

[=]   # | sector 00 / 0x00                                | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 34 00 07 00 00 D1 82 BB 53 00 00 00 00 00 07 00 | 4.......S.......
[=]   1 | 01 00 F4 71 09 67 64 15 07 13 00 1B 30 2E 02 15 | ...q.gd.....0... 
[=]   2 | 00 DD B7 42 88 8D D4 01 A2 B1 25 A4 F7 4A 6F B0 | ...B......%..Jo. 
[=]   3 | 00 00 00 00 00 00 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......

[=] ----------------------- Sector trailer decoder -----------------------
[=] key A........ 000000000000
[=] acr.......... FF0780
[=] user / gpb... 69
[=] key B........ B0B1B2B3B4B5

[=]   # | Access rights
[=] ----+-----------------------------------------------------------------
[=]   0 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   1 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   2 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   3 | write A by A; read/write ACCESS by A; read/write B by A
[=] ----------------------------------------------------------------------


```

**Comment by mwalker33** [comment]
Can I get you to post the sector 0 of the original.

So far it seems that the restore (cload) worked as expected, but the dump has an incorrect block 0.  (I want to test with 100% the same block 0, as the original)

Thanks

**Comment by mwalker33** [comment]
Note: I can make it happen.    For testing, I updated my client the the very latest (as at now)
I setup a card based on your dump from above (with a working block 0, that may not match yours)

```
hf mf autopwn
```
Block 0 is what was on my test card
```
[usb] pm3 --> hf mf view -f hf-mf-2F64EF3E-dump-2
[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-2

[=] ----+-------------------------------------------------+-----------------
[=] blk | data                                            | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 2F 64 EF 3E 9A D1 82 BB 53 00 00 00 00 00 07 00 | /d.>....S.......
[=]   1 | 01 00 F4 71 09 67 64 15 07 13 00 1B 30 2E 02 15 | ...q.gd.....0...
```

Restore to a gen1a card
```
[usb] pm3 --> hf mf cload -f hf-mf-2F64EF3E-dump-2.bin
[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-2.bin
[=] Copying to magic gen1a card
[=] .................................................................

[+] Card loaded 64 blocks from file
[=] Done!
```

hf search finds the correct card (based on my block 0)
```
[usb] pm3 --> hf mf cload -f hf-mf-2F64EF3E-dump-2.bin
[+] loaded 1024 bytes from binary file hf-mf-2F64EF3E-dump-2.bin
[=] Copying to magic gen1a card
[=] .................................................................

[+] Card loaded 64 blocks from file
[=] Done!
```

So unless there is some weirdness in your original card, I cant see why it would not work.
Lets see what happens when I get your original block 0.
Thanks

**Comment by uspilot** [comment]
This is ORIGINAL card
It looks very strange, but it have no idea why is block 0 don't read correct 
```
[usb] pm3 --> hf mf rdsc -k a0a1a2a3a4a5 -s 0 -v

[=]   # | sector 00 / 0x00                                | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 34 00 07 00 00 D1 82 BB 53 00 00 00 00 00 07 00 | 4.......S.......
[=]   1 | 01 00 F4 71 09 67 64 15 07 13 00 1B 30 2E 02 15 | ...q.gd.....0... 
[=]   2 | 00 DD B7 42 88 8D D4 01 A2 B1 25 A4 F7 4A 6F B0 | ...B......%..Jo. 
[=]   3 | 00 00 00 00 00 00 FF 07 80 69 B0 B1 B2 B3 B4 B5 | .........i......

[=] ----------------------- Sector trailer decoder -----------------------
[=] key A........ 000000000000
[=] acr.......... FF0780
[=] user / gpb... 69
[=] key B........ B0B1B2B3B4B5

[=]   # | Access rights
[=] ----+-----------------------------------------------------------------
[=]   0 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   1 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   2 | read AB; write AB; increment AB; decrement transfer restore AB
[=]   3 | write A by A; read/write ACCESS by A; read/write B by A
[=] ----------------------------------------------------------------------
```
```
[usb] pm3 --> hf 14a info

[+]  UID: 2F 64 EF 3E 
[+] ATQA: 00 44
[+]  SAK: 08 [2]
[+] Possible types:
[+]    MIFARE Classic 1K CL2
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: hard
[#] Auth error

```

**Comment by mwalker33** [comment]
Thanks.
So now we can say that the proxmark dump does contain what it read and the cload did restore what was in the dump.

As to why block 0 does not match the UID seen, no idea.  I am wondering if its protected somehow (started to get outside of my mifare classic skill set), just a guess.

Maybe someone else has some idea.

**Comment by uspilot** [comment]
Yes, it seems like some kind of protection because I have the same readout with Chinese firmware on PM3 Easy.

**Comment by iceman1001** [comment]
Closing, since its no issue in the code base.   I suggest you take it to discord and continue in the _mifare_ channel
