### ISSUE TITLE
hf mf chk failed to use with other sectors

### ISSUE THREAD

**Issue by hanyuhang** [RfidResearchGroup/proxmark3#1664]
**Describe the bug**
hf mf chk failed to use with other sectors

**Screenshots**
pm3 --> hf mf chk -a --tblk 10 -f E:\dictionaries\mfc_default_keys.dic
[=] Start check for keys...
[=] ..
[=] time in checkkeys 0 seconds

[=] testing to read key B...
[=] Sector: 2, First block: 8, Last block: 11, Num of blocks: 4
[=] Reading sector trailer
Data:FF FF FF FF FF FF

[+] found keys:

[+] -----+-----+--------------+---+--------------+----
[+]  Sec | Blk | key A        |res| key B        |res
[+] -----+-----+--------------+---+--------------+----
[+]  002 | 011 | ------------ | 0 | ------------ | 0
[+] -----+-----+--------------+---+--------------+----
[+] ( 0:Failed / 1:Success )

**Comment by iceman1001** [comment]
user related question,  this is for code base bugs.   Ask questions on Discord server or Proxmark3 forum.
