### ISSUE TITLE
usb driver

### ISSUE THREAD

**Issue by Jfridd1984** [RfidResearchGroup/proxmark3#1665]
***Things to try before submitting bug report***
read the [troubleshooting guide](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Troubleshooting.md)

***Compilation problems***
Try compiling with verbose.  `make VERBOSE=1` with main makefile or `make V=1` with cmake.

***flashing problems***
Have you followed the instructions properly?  ie,  flashed bootrom seperately first if you are going from Offical repo to Iceman repo.

-i restarted in safe mode with windows sign drivers only disabled and now i can no longer pick up the device on any computer

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version
 - hw status
 - data tune

**Additional context**

**Comment by iceman1001** [comment]
It is like you missed to fill in the template with all relevant data

**Comment by Jfridd1984** [comment]
i did i apologize i will get it right next time. thanks
