### ISSUE TITLE
autopwn无法破解无漏洞卡autopwn cannot crack non-vulnerable cards

### ISSUE THREAD

**Issue by xbebhxx3** [RfidResearchGroup/proxmark3#1671]
我在对一个无漏洞卡执行hf mf autopwn时返回[!!] Error: No response from Proxmark3
虽然这张卡可以使用hf mf staticnested破解，但是我还是您能希望修复这个bug
I get  [!!] Error: No response from Proxmark3  when doing hf mf autopwn on a non-vulnerable card
Although this card can be hacked using hf mf staticnested, I still hope you can fix this bug

**Comment by iceman1001** [comment]
You will need to provide with a more detailed bug report in order to be able to look into this issue.

**Comment by wh201906** [comment]
Seems like your firmware on your PM3 hardware doesn't match your client
