### ISSUE TITLE
[idea] NDEF encoding/writing

### ISSUE THREAD

**Issue by darrellenns** [RfidResearchGroup/proxmark3#1677]
Currently, NDEF can be read and decoded/parsed from many types of tags. However, there is no option to encode or write NDEF messages. It would be great if there were functions to encode various types of NDEF messages (text, URLs, arbitrary MIME data, etc) and to write or append the message to a tag.

**Comment by iceman1001** [comment]
Something to write up on the wish list.  
https://github.com/RfidResearchGroup/proxmark3/wiki/Wishlist

When it comes to NDEF encoding, its a complex matter.  So there are some nice ndef projects on NFCtools that do the job just fine.  The code base isn't easy to merge into Proxmark3 code base,  so I suggest you use that tool instead.

https://github.com/nfc-tools/libndef

Feel free to contribute!
