### ISSUE TITLE
[想法]I want to create an operation interface for Proxmark3 on macos, what should I do?

### ISSUE THREAD

**Issue by micoewhl** [RfidResearchGroup/proxmark3#1680]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iceman1001** [comment]
Not sure what you are trying to say. 

Operation interface for OSX ?   You have the pm3 client,  you can use python3 to send commands..
