### ISSUE TITLE
 HF antenna is UNUSABLE

### ISSUE THREAD

**Issue by xkuza** [RfidResearchGroup/proxmark3#1705]
[usb] pm3 --> hw tune
[=] ---------- Reminder ------------------------
[=] `hw tune` doesn't actively tune your antennas,
[=] it's only informative.
[=] Measuring antenna characteristics, please wait...
 🕛   9
[=] ---------- LF Antenna ----------
[+] LF antenna:  4.43 V - 125.00 kHz
[+] LF antenna:  4.06 V - 134.83 kHz
[+] LF optimal:  4.18 V - 115.38 kHz
[+] Approx. Q factor (*): 2.4 by frequency bandwidth measurement
[+] Approx. Q factor (*): 1.2 by peak voltage measurement
[+] LF antenna is MARGINAL
[=] ---------- HF Antenna ----------
[!] ⚠  HF antenna is UNUSABLE

**Comment by iceman1001** [comment]
You seem to have crappy LF antenna too.  I suggest you ask questions at discord server or Pm3 forum.  

Closing since this is not a sw/fw related question.
