### ISSUE TITLE
generator.c g_debugMode undeclared in mfdes_kdf_input_gallagher

### ISSUE THREAD

**Issue by Axlbuld** [RfidResearchGroup/proxmark3#1736]
Hi,
I reinstalled my kali linux and pulled the current version of proxmark3.

Compile shows an error when compiling generator.c
"../common/generator.c: In function 'mfdes_kdf_input_gallagher
../common/generator.c:488:13: error: 'g_debugMode' undeclared (first use in this function)"

Consequently, compliation stops and firmware is not provided.

**Comment by iceman1001** [comment]
Pull latest and it is fixed

**Comment by Axlbuld** [comment]
Thanks, That was fast. Fixed.

**Comment by iceman1001** [comment]
you caught me before I was able to push the fix ;)
