### ISSUE TITLE
Writing to legic cards fails

### ISSUE THREAD

**Issue by le-krogoth** [RfidResearchGroup/proxmark3#1748]
**Describe the bug**
Writing to legic cards stops with the following error message

`Sending 517 bytes of payload is too much, abort`

This is because of a bug most probably introduced in commit [63bc9b5eb25dea6d1c2add122c2587ff68d78d0c](https://github.com/RfidResearchGroup/proxmark3/commit/63bc9b5eb25dea6d1c2add122c2587ff68d78d0c) when switching to NG comms.

This affects _hf legic wipe_ as well as at least _hf legic restore_. 

**To Reproduce**
1. Start proxmark
2. hf legic wipe

or

1. Start proxmark
2. hf legic restore -f file

**Expected behavior**
The card will either be wiped or the content overwritten.

**Desktop (please complete the following information):**
IMHO not relevant. See below.

**Additional context**
Said commit changed how data is sent to the proxmark hardware. It now uses a struct not only containing the data to be written to the card, but also other relevant meta data:

```
typedef struct {
    uint16_t offset;
    uint16_t len;
    uint8_t iv;
    uint8_t data[];
} PACKED legic_packet_t; 
```

The problem is, that with that struct, the size of the data sent to the hardware increased by the size of sizeof(legic_packet_t). Which is not considered when calling: 

`SendCommandNG`

Which ultimately results in the above error message in:

_client/src/comms.c, line 134_:

```
if (len > PM3_CMD_DATA_SIZE) {
        PrintAndLogEx(WARNING, "Sending %zu bytes of payload is too much, abort", len);
        return;
    }
```

Since the preparation of data does not consider _sizeof(legic_packet_t)_. As example in:

_client/src/cmdhflegic.c, line 945_:

```
for (size_t i = 7; i < bytes_read; i += PM3_CMD_DATA_SIZE) {

        size_t len = MIN((bytes_read - i), PM3_CMD_DATA_SIZE);
```

Which will add 517bytes of data to the _legic_packet_t_ struct. The preparation of the _legic_packet_t_ will have to be fixed in at least _hf legic wipe_ as well as _hf legic restore_.

**Comment by iceman1001** [comment]
Interesting,
I see I failed to adapt two commands for the new sizes.  
I pused a fix,  Try pulling latest
