### ISSUE TITLE
All the steps are functional but can not connect.(IceMan [EASY])

### ISSUE THREAD

**Issue by GeojoL** [RfidResearchGroup/proxmark3#1750]
![image](https://user-images.githubusercontent.com/97789539/184179083-5b130f1d-a5d8-40d4-ba94-f6a6374b7b9d.png)

**Comment by GeojoL** [comment]
I've tired
brew remove proxmark3  
brew install --with-blueshark --HEAD rfidresearchgroup/proxmark3/proxmark3
pm3-flash-all

**Comment by iceman1001** [comment]
Try asking in the discord.   It seems more related to your setup than the source code.

...try different usb cable etc.
and there is a troubleshooting guide that you can try.

**Comment by GeojoL** [comment]
Thank you for your help, I have joined the discord community and solved the problem.
