### ISSUE TITLE
 hardnested random number is always 1

### ISSUE THREAD

**Issue by xbebhxx3** [RfidResearchGroup/proxmark3#1760]
Describe the bug

When I run hf mf hardnested --blk 0 -b -k ced0cfc1bbbf random number is always 1.

To Reproduce

run hf mf hardnested --blk 0 -b -k ced0cfc1bbbf.

Expected behavior
Found hidden mifare keys.

Screenshots
![1660892575890](https://user-images.githubusercontent.com/102897690/185562549-4c7298ef-a654-444e-b900-e926658bc39c.jpg)

Desktop (please complete the following information):

OS: windows 10
inside proxmark3 client run the following commands and paste the output here.
hw version
![image](https://user-images.githubusercontent.com/102897690/185562652-59b7883b-86da-4dfd-9211-0b856879ad4d.png)

hw status
![image](https://user-images.githubusercontent.com/102897690/185562699-3aea0f6c-25d5-45b3-8912-d1316c086abb.png)

data tune
![image](https://user-images.githubusercontent.com/102897690/185562777-1e34cdca-b343-4355-8699-b070810be5c0.png)

**Comment by iceman1001** [comment]
Which proxmark3 device do you have?

I see that you are not on latest source,    please pull latest, compile, flash and test.

I have tried it on a RDV2 with firmware PM3_GENERIC and it works.

**Comment by xbebhxx3** [comment]
proxmark3 easy
I have recompiled the latest version, but the problem persists

![1660900741481](https://user-images.githubusercontent.com/102897690/185587677-0328b0ea-176f-4661-b56b-ed4460848a81.jp
![1660900837375](https://user-images.githubusercontent.com/102897690/185587831-5c24d4c1-4c4f-489a-ba37-912f8c45a5c7.jpg)
g)

**Comment by xbebhxx3** [comment]
Only the current card has problems, other cards do not

**Comment by iceman1001** [comment]
Which card is it?

**Comment by xbebhxx3** [comment]
It may be the 3rd generation without loopholes card made in China

**Comment by atkfromabove** [comment]
Is this the same issue as the other Hardnested ticket?

https://github.com/RfidResearchGroup/proxmark3/issues/1734

**Comment by xbebhxx3** [comment]
Only 2 I've come across have this situation

**Comment by xbebhxx3** [comment]
I would like to know how to read this kind of card

**Comment by xbebhxx3** [comment]
> Is this the same issue as the other Hardnested ticket?
> 
> #1734

mine is not stuck

**Comment by iceman1001** [comment]
If you can post a picture of the card you are looking at,  that would be helpful to identify which system its being used with.
Otherwise I am afraid I have no idea whats wrong.

**Comment by xbebhxx3** [comment]
![3a3974e4b5be6cc9e50f21e1f7e7bf2](https://user-images.githubusercontent.com/102897690/186159862-e0796740-da27-4f0a-a303-9108689adf6f.jpg)

**Comment by iceman1001** [comment]
`hf mfp info`  ?

**Comment by xbebhxx3** [comment]
[=] --- Tag Information ---------------------------
    [=] -------------------------------------------------------------
    [!!] No card response.
    
    [+]  UID: 53 2E 97 B9
    [+] ATQA: 00 04
    [+]  SAK: 08 [2]
    [+] Possible types:
    [+]    MIFARE Classic 1K
    [=] proprietary non iso14443-4 card found, RATS not supported
    [+] Prng detection: weak
    [#] Auth error
    [?] Hint: try `hf mf` commands
    
    [!!] No card response.
    [=] --- Fingerprint
    [=]           SIZE: 2K (4 UID)
    [=]             SAK: 2K 7b UID
    [=] --- Security Level (SL)
    [+]        SL mode: SL1
    [=]   SL 1: backwards functional compatibility mode (with MIFARE Classic 1K / 4K) with an optional AES authentication

**Comment by iceman1001** [comment]
ok,  so the card isn't a MFC.   

No luck for you.

**Comment by xbebhxx3** [comment]
So how do I crack it

**Comment by iceman1001** [comment]
use the forum or discord to ask user related questions.

**Comment by huanyingu** [comment]
I have the same problem. Is it resolved?
