### ISSUE TITLE
Standalone hf_tmudford.c compilation error

### ISSUE THREAD

**Issue by Fl0-0** [RfidResearchGroup/proxmark3#1771]
***Compilation problem***
[-] CC appmain.c
../armsrc/Standalone/hf_tmudford.c: In function 'RunMod':
../armsrc/Standalone/hf_tmudford.c:78:17: error: too few arguments to function 'SimTagIso15693'
   78 |                 SimTagIso15693(card.uid);
      |                 ^~~~~~~~~~~~~~
In file included from ../armsrc/Standalone/hf_tmudford.c:29:
./iso15693.h:51:6: note: declared here
   51 | void SimTagIso15693(uint8_t *uid, uint8_t block_size); // simulate an ISO15693 tag
      |      ^~~~~~~~~~~~~~
make[1]: *** [../common_arm/Makefile.common:119: obj/hf_tmudford.o] Error 1

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Compiler (ARM):  arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)

**Comment by iceman1001** [comment]
I pushed a fix,
