### ISSUE TITLE
src/cmdlfparadox.c:102:13: error: variable 'error' set but not used [-Werror,-Wunused-but-set-variable]
    uint8_t error = 0;

### ISSUE THREAD

**Issue by sun1ch** [RfidResearchGroup/proxmark3#1780]
I got that error when Im trying to compile client in Termux

I need solution of this problem.

Device Samsung Galaxy Tab S7 Android 12
![Screenshot_20220920_064332_Termux.jpg](https://user-images.githubusercontent.com/98668583/191162982-4bbea681-1f8e-4e3d-981f-89b58e1e638a.jpg)

**Comment by iceman1001** [comment]
I pushed a fix,  
Try pulling latest and see if it compiles now

**Comment by sun1ch** [comment]
Now error is

bignum.c:1442:29: error: variable 't' set but not used [-Werror,-Wunused-but-set-variable]
    mbedtls_mpi_uint c = 0, t = 0;
                            ^
1 error generated.
make[2]: *** [../../Makefile.host:95: ../../client/obj/mbedtls/bignum.o] Error 1
make[1]: *** [Makefile:866: obj/libmbedtls.a] Error 2
make: *** [Makefile:158: client/all] Error 2

![Screenshot_20220920_103756_Termux.jpg](https://user-images.githubusercontent.com/98668583/191196690-227fa391-93a3-42a1-b4b1-06121b5a6e32.jpg)

**Comment by iceman1001** [comment]
Feel free to contribute
