### ISSUE TITLE
NixOS (nix-Shell) config

### ISSUE THREAD

**Issue by foorschtbar** [RfidResearchGroup/proxmark3#1798]
For the NixOS users i created a nix-shell file for comping this project.

Copy this file as shell.nix to the cloned proxmark3 folder and run `sudo nix-shell`. Continue with the normal compiling guide.

```nix
with (import <nixpkgs> {});
mkShell {
  buildInputs = [
    readline
    ocamlPackages.bz2
    ocamlPackages.ssl
    gcc-arm-embedded
  ];
}
```

**Comment by iceman1001** [comment]
Not sure why you closed this issue?  
But it looks like a good helper script for nixos users. 
I believe we have some more dependencies

**Comment by lennyerik** [comment]
Hey, for anyone coming across this and looking for an up-to-date config, I wanted to share my `shell.nix`, which I used to successfully build the pm3 for my proxmark easy board.
```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = with pkgs; [
    ccache
    gcc-arm-embedded
  ];

  NIX_CFLAGS_COMPILE = [
    "-I${pkgs.openssl.dev}/include"
    "-I${pkgs.lz4.dev}/include"
    "-I${pkgs.bzip2.dev}/include"
    "-I${pkgs.readline.dev}/include"
  ];
  NIX_LDFLAGS = [
    "-L${pkgs.openssl.out}/lib"
    "-L${pkgs.lz4.lib}/lib"
    "-L${pkgs.bzip2.out}/lib"
    "-L${pkgs.readline.out}/lib"
  ];

  NIX_ENFORCE_NO_NATIVE = false;
}
```

You might need a few more packages depending on your systemPackages (I have gnumake, a C compiler, etc. installed system-wide), but this should be a fairly good starting point for anyone wanting to build on nixos. 😄
