### ISSUE TITLE
Bluetooth no longer working

### ISSUE THREAD

**Issue by evazzoler** [RfidResearchGroup/proxmark3#1803]
Since v4.1584 cannot connect with PM3 via bluetooth on Linux Ubuntu (different versions).
I get this error "[!!] 🚨 ERROR: cannot communicate with the Proxmark" after few second the blue led becomes fixed blue.
Same happens with "RFID Tools" on Android.

**Comment by evazzoler** [comment]
It was a mess made by git. I started from zero, now it works, sorry for the issue opened without checking that.

**Comment by evazzoler** [comment]
Problem pesists with Android RFID Tools App. I will open a issue on the app repo.

**Comment by iceman1001** [comment]
the rfid apps etc is out of reach for the responsibility of this repo.
