### ISSUE TITLE
Unable to flash

### ISSUE THREAD

**Issue by cafedevx** [RfidResearchGroup/proxmark3#1845]
Hello,
I have a problem with my proxmark3 rdv4.It was working fine, I wanted to update the firmware and there was a disaster. I am stuck on an error  :
pm3-flash-bootrom 
[=] Session log /home/xxx/.proxmark3/logs/log_20221218.txt
[+] loaded from JSON file /home/xxx/.proxmark3/preferences.json
[+] About to use the following file:
[+]    /usr/local/bin/../share/proxmark3/firmware/bootrom.elf
[+] Loading ELF file /usr/local/bin/../share/proxmark3/firmware/bootrom.elf
[+] ELF file version Iceman/master/v4.15864-149-gda3fff58f 2022-12-18 22:17:29 a3d49350c

[+] Waiting for Proxmark3 to appear on /dev/ttyACM1
 🕑  59 found
[+] Entering bootloader...
[+] (Press and release the button only to abort)
[+] Waiting for Proxmark3 to appear on /dev/ttyACM1
 🕗  31 found
[!!] 🚨 ====================== OBS ! ===========================================
[!!] 🚨 Note: Your bootloader does not understand the new CMD_BL_VERSION command
[!!] 🚨 It is recommended that you first update your bootloader alone,
[!!] 🚨 reboot the Proxmark3 then only update the main firmware

[!!] 🚨 ------------- Follow these steps -------------------

[!!] 🚨  1)   ./pm3-flash-bootrom
[!!] 🚨  2)   ./pm3-flash-all
[!!] 🚨  3)   ./pm3

[=] ---------------------------------------------------

[=] Available memory on this board: UNKNOWN

[!!] 🚨 ====================== OBS ! ======================================
[!!] 🚨 Note: Your bootloader does not understand the new CHIP_INFO command
[=] Permitted flash range: 0x00100000-0x00140000
[!!] 🚨 ====================== OBS ! ========================================
[!!] 🚨 Note: Your bootloader does not understand the new START_FLASH command
[+] Loading usable ELF segments:
[+]    0: V 0x00100000 P 0x00100000 (0x00000200->0x00000200) [R X] @0x94
[+]    1: V 0x00200000 P 0x00100200 (0x00000d1c->0x00000d1c) [R X] @0x298

[+] Flashing...
[+] Writing segments for file: /usr/local/bin/../share/proxmark3/firmware/bootrom.elf
[+]  0x00100000..0x001001ff [0x200 / 1 blocks]

[!] ⚠️  Communicating with Proxmark3 device failed

Can you help me please ?
Thanks a lot !

**Comment by iceman1001** [comment]
User related questions is handled at the discord server.   The channel  _bricked_my_device_  is for you
