### ISSUE TITLE
Build fail on termux (mbedtls, unused variable)

### ISSUE THREAD

**Issue by alexcher-im** [RfidResearchGroup/proxmark3#1848]
I'm trying to build the client (`make client`) on termux (aarch64 device), and getting compilation error:
```
bignum.c:1444:29: error: variable 't' set but not used [-Werror,-Wunused-but-set-variable]
    mbedtls_mpi_uint c = 0, t = 0;
                            ^
1 error generated.
```
Manually removing variable and it's write-usage fixes the problem (`common/mbedtls/bignum.c` lines `1444` and `1490`)

**Comment by Javimoya03** [comment]
Hello, did you find a way to fix this?

**Comment by iceman1001** [comment]
Would this work?
```
    mbedtls_mpi_uint c = 0, t = 0;
    (void)t;
```

**Comment by Javimoya03** [comment]
but where do i write that?

**Comment by Javimoya03** [comment]
Nothing, its says:


bignum.c:1444:36: error: expected expression
    mbedtls_mpi_uint c = 0, t = 0 (void)t;
                                   ^
1 error generated.
make[2]: *** [../../Makefile.host:95: ../../client/obj/mbedtls/bignum.o] Error 1
make[1]: *** [Makefile:867: obj/libmbedtls.a] Error 2
make: *** [Makefile:158: client/all] Error 2

**Comment by iceman1001** [comment]
the suggested fix has been pushed to the repo,  so you pull latest and compile

**Comment by Javimoya03** [comment]
> the suggested fix has been pushed to the repo,  so you pull latest and compile

Thanks bro!!
