### ISSUE TITLE
Changing HID iClass Legacy key bricks card.

### ISSUE THREAD

**Issue by shellster** [RfidResearchGroup/proxmark3#1852]
**Describe the bug**
There's a good chance that I simply don't know what I'm doing, but I'm attempting to take an iClass Legacy card and change the encryption key.  Everytime I attempt this I end up bricking a card (presumably because it is writing the wrong key and then I can't read it after this point).  The reason I'm trying to do this is to get around the iCopy-X's proprietary card requirement (See ICL section here: https://github.com/iCopy-X-Community/icopyx-teardown/tree/master/tags#icl)

**To Reproduce**
Basically follow the steps above in the supplied link.  In more detail:
I'm using a Proxmark 3 Easy  with the latest firmware (compiled today 12/29/2022).
I put a Hid iClass Legacy card on the reader. 
I run `hf iclass calcnewkey --old AFA785A7DAB33378 --new 2020666666668888`
I record the the Xor div key.
I then run: `hf iclass wrbl -b 3 -d <xor div key (no spaces)> -k AFA785A7DAB33378`
I try to read the card using either the original key or the new key (2020666666668888) and am unable to.
I also tried using the `hf iclass permute -r --key <xor div key (no spaces)>` and writing that result but end up with the same result of not being able to decrypt the card with any key after writing.

**Expected behavior**
I expect to be able to read and decrypt the card with the key `2020666666668888`
Or, if I am doing something stupid, would appreciate any advice on how to do what I am attempting the right way.

**Comment by iceman1001** [comment]
User related question is best handled in the discord server,
