### ISSUE TITLE
Error compiling the firmware (arm-none-eabi-gcc)

### ISSUE THREAD

**Issue by Javimoya03** [RfidResearchGroup/proxmark3#1874]
I am trying to use my proxmark3 easy on android with termux.
When I try to compile the program for my proxmark easy, with:`make clean && PLATFORM=PM3GENERIC`,
Everything works correctly until there is an error, the description indicates that it cannot find the file arm-none-eabi-gcc. Attached the text and a screenshot of the error:
`make[1]: arm-none-eabi-gcc: No such file or directory
make[1]: *** [../common_arm/Makefile.common:133: obj/version_pm3.o] Error 127
make: *** [Makefile:152: bootrom/all] Error 2`
![Screenshot_20230116_223443_Termux](https://user-images.githubusercontent.com/98014500/212769091-13be7477-dafa-4d8c-b375-5737a1145da0.jpg)
Sorry for my english :)

**Comment by iceman1001** [comment]
did you set up your development environment correct?   if no, follow the appropriate guide.

**Comment by squigley74** [comment]
Other than the wildly unhelpful comment from three years ago.. is there a solution to this issue? I just received a new proxmark3 easy and followed the instructions to the letter. Unable to open PM3.

[*] MAKE bootrom/all
/bin/sh: line 1: arm-none-eabi-gcc: command not found
compiler version:
[=] CHECK version_pm3.c
[-] CC version_pm3.c
make[2]: arm-none-eabi-gcc: No such file or directory
make[2]: *** [../common_arm/Makefile.common:137: obj/version_pm3.o] Error 127
make[1]: *** [Makefile:180: bootrom/all] Error 2
make[1]: Leaving directory '/pm3/proxmark3'
make: *** [Makefile:41: all] Error 1

**Comment by iceman1001** [comment]
yet again,   your development environment is not setup properly.   Follow the guide ,  respective your choice of OS...   

After you done that we will see how far you got.
