### ISSUE TITLE
ERROR : sscanf  %lu long unsigned int - brute_key.c:115:24

### ISSUE THREAD

**Issue by deg-mallard** [RfidResearchGroup/proxmark3#1923]
Running the latest git clone, when running make clean && make -j8 all I get the below error

brute_key.c:115:24: error: format '%lu' expects argument of type 'long unsigned int *', but argument 3 has type 'uint64_t *' {aka 'long long unsigned int *'} [-Werror=format=]
  115 |     sscanf(argv[1], "%lu", &timestamp);
      |                      ~~^   ~~~~~~~~~~
      |                        |   |
      |                        |   uint64_t * {aka long long unsigned int *}
      |                        long unsigned int *
      |                      %llu

I then run ./pm3-flash-bootrom which works fine but when I run ./pm3-flash-fullimage I get the error 

Error - can't find 'fullimage.elf'

I am now unable to use my Proxmark reader

**Comment by iceman1001** [comment]
Noted, 
If you pull latest,  see if this suggested fiix helps
