### ISSUE TITLE
Pinout of SAM7512 for SPI

### ISSUE THREAD

**Issue by DonLaman** [RfidResearchGroup/proxmark3#1954]
Hi, I bought a Chinese proxmark3 Easy some time ago. It doesn't have external flash support. I decided to use the spi support of the pm3 but I can't find the connection PIN to the CS or SS. Could you tell me which PIN I have to connect?

**Comment by wh201906** [comment]
![图片](https://user-images.githubusercontent.com/62299611/229357754-2a1b89d0-c4d4-449c-b3ff-281f5b4e021c.png)
