### ISSUE TITLE
 Unable to dump with user-provided key B with ANY command

### ISSUE THREAD

**Issue by mattiacolombomc** [RfidResearchGroup/proxmark3#1972]
_Maybe this is related to #960?_

**Describe the bug**
 I can't dump any card with **user-provided key B** (_even though it is the master key!_)

First, I obviously checked the status of my keys:
`hf mf chk --1k -k <key1> -k <key2> -k <key3> -k FFFFFFFFFFFF` works and checks the keys:
![1](https://user-images.githubusercontent.com/55593934/234852077-33abfe26-64d1-4a3a-9224-b070c9d3026e.png)

Then, I tried to dump with two different methods:
### **METHOD 1 - hf mf autopwn**
1) Added the KNOWN keys in the dictionary file [following the documentation](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/path_notes.md#proxmark3-client-files-dictionaries) 
2) Ran `hf mf autopwn`, but then this happens:
![b](https://user-images.githubusercontent.com/55593934/234852574-c8db6374-25e0-4570-8bbd-9cf26a0e6ee6.png)

### **METHOD 2 - hf mf dump**
1) Created `.dic` file: `client/dictionaries/userDic.dic` with the same format of `client/dictionaries/mfc_default_keys.dic` - this is how `userDic.dic` looks like:
![b](https://user-images.githubusercontent.com/55593934/234854359-b3377076-af1b-4a0e-b737-cd1a60c740c0.png)
2) `hf mf dump --1k -k client/dictionaries/userDic.dic -f dump.bin` 
**The strangest thing here is that access rights can't be gained even when using key B (master key) authentication using the SAME keys I tested above.**

![c](https://user-images.githubusercontent.com/55593934/234854962-68a26312-b536-446b-a306-2dfd17289a04.png)

**Expected behavior**
The card should be dumped successfully, how normally happens for example on an Android phone.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2 (22D49)
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version
  ```
[ Proxmark3 RFID instrument ]

 [ CLIENT ]
  Iceman/master/v4.16191-303-g1a3a6e5f1-dirty-unclean 2023-04-17 21:08:45 3222e6903
  compiled with............. Clang/LLVM Apple LLVM 14.0.3 (clang-1403.0.22.14.1)
  platform.................. OSX / x86_64
  Readline support.......... present
  QT GUI support............ present
  native BT support......... absent
  Python script support..... present
  Lua SWIG support.......... present
  Python SWIG support....... present

 [ PROXMARK3 ]
  firmware.................. PM3 GENERIC

 [ ARM ]
  bootrom: Iceman/master/v4.16191-303-g1a3a6e5f1-dirty-unclean 2023-04-17 21:08:28 3222e6903
       os: Iceman/master/v4.16191-303-g1a3a6e5f1-dirty-unclean 2023-04-17 21:08:34 3222e6903
  compiled with GCC 10.2.1 20201103 (release)

 [ FPGA ]
  LF image 2s30vq100 2022-03-23 17:21:05
  HF image 2s30vq100 2022-03-23 17:21:16
  HF FeliCa image 2s30vq100 2022-03-23 17:21:27
  HF 15 image 2s30vq100 2022-03-23 17:21:38

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev A
  --= Embedded Processor: ARM7TDMI
  --= Internal SRAM size: 64K bytes
  --= Architecture identifier: AT91SAM7Sxx Series
  --= Embedded flash memory 512K bytes ( 60% used )
```
 - hw status
```
[#] Memory
[#]   BigBuf_size............. 42744
[#]   Available memory........ 40436
[#] Tracing
[#]   tracing ................ 1
[#]   traceLen ............... 120
[#] Current FPGA image
[#]   mode.................... HF image 2s30vq100 2022-03-23 17:21:16
[#] LF Sampling config
[#]   [q] divisor............. 95 ( 125.00 kHz )
[#]   [b] bits per sample..... 8
[#]   [d] decimation.......... 1
[#]   [a] averaging........... yes
[#]   [t] trigger threshold... 0
[#]   [s] samples to skip..... 0
[#]
[#] LF T55XX config
[#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
[#]            mode            |start|write|write|write| read|write|write
[#]                            | gap | gap |  0  |  1  | gap |  2  |  3
[#] ---------------------------+-----+-----+-----+-----+-----+-----+------
[#] fixed bit length (default) |  31 |  20 |  18 |  50 |  15 | N/A | N/A |
[#]     long leading reference |  31 |  20 |  18 |  50 |  15 | N/A | N/A |
[#]               leading zero |  31 |  20 |  18 |  40 |  15 | N/A | N/A |
[#]    1 of 4 coding reference |  31 |  20 |  18 |  34 |  15 |  50 |  66 |
[#]
[#] HF 14a config
[#]   [a] Anticol override.... std    ( follow standard )
[#]   [b] BCC override........ std    ( follow standard )
[#]   [2] CL2 override........ std    ( follow standard )
[#]   [3] CL3 override........ std    ( follow standard )
[#]   [r] RATS override....... std    ( follow standard )
[#] Transfer Speed
[#]   Sending packets to client...
[#]   Time elapsed................... 500ms
[#]   Bytes transferred.............. 297984
[#]   Transfer Speed PM3 -> Client... 595968 bytes/s
[#] Various
[#]   Max stack usage......... 4288 / 8480 bytes
[#]   Debug log level......... 1 ( error )
[#]   ToSendMax............... 75
[#]   ToSend BUFFERSIZE....... 2308
[#]   Slow clock.............. 28890 Hz
[#] Installed StandAlone Mode
[#]   LF HID26 standalone - aka SamyRun (Samy Kamkar)
```
 - data tune
```
[=] ---------- Reminder ------------------------
[=] `hw tune` doesn't actively tune your antennas,
[=] it's only informative.
[=] Measuring antenna characteristics, please wait...
 🕛   9
[=] ---------- LF Antenna ----------
[+] LF antenna: 23,71 V - 125,00 kHz
[+] LF antenna: 15,25 V - 134,83 kHz
[+] LF optimal: 26,68 V - 118,81 kHz
[+] Approx. Q factor (*): 6,7 by frequency bandwidth measurement
[+] Approx. Q factor (*): 7,8 by peak voltage measurement
[+] LF antenna is OK
[=] ---------- HF Antenna ----------
[+] HF antenna: 14,77 V - 13.56 MHz
[+] Approx. Q factor (*): 4,3 by peak voltage measurement
[+] HF antenna is OK

(*) Q factor must be measured without tag on the antenna

[+] Displaying LF tuning graph. Divisor 88 (blue) is 134,83 kHz, 95 (red) is 125,00 kHz.
```
<img width="779" alt="proxmark3 -27 -04-2023 at 14 04 40@2x" src="https://user-images.githubusercontent.com/55593934/234856629-2c709a5f-5fab-4a97-8d8c-a043c5f001e0.png">

**Comment by iceman1001** [comment]
I don't really see this as a bug in the software.

1.  you didnt get all keys.
2. Have you verified the ACL for the sectors you couldn't extract keys from?
3. the dump execution,  looks like you could do some more space between tag and antenna.

All in all,   I also see you asked on the discord,   which is the correct place for this kind of questions. 

Closing,
