### ISSUE TITLE
Just few typos 

### ISSUE THREAD

**Issue by RekordNadoev** [RfidResearchGroup/proxmark3#1986]
**Describe the bug**
Have found some typos:

client/src/cmdhfmfu.c:4700 - "Cofigure the tamper feature on an NTAG 213TT"
doc/commands.md:571 - Cofigure the tamper
client/src/cmdhfmfu.c:2693 - "Set the congiguration of the NTAG 213TT tamper feature\n"
doc/commands.json:6568 - "description": "Set the congiguration

**To Reproduce**
1. start pm3
2. exec "hf mfu tamper --help"
3. exec "hf mfu"
4. See typos

**Expected behavior**
See no typos. :-)

**Comment by iceman1001** [comment]
thanks for pointing it out.
Pushed a fix,   the rest will be fixed when I push `make style`  soon.
