### ISSUE TITLE
`pm3_help2json.py` doesn't work for commands with empty lines in description

### ISSUE THREAD

**Issue by wh201906** [RfidResearchGroup/proxmark3#2015]
**Describe the bug**
The `pm3_help2json.py` cannot parse some of the command helps into json
output from client:
```
---------------------------------------------------------------------------------------
usart btfactory          
available offline: no

Reset BT add-on to factory settings
This requires
    1) BTpower to be turned ON
    2) BT add-on to NOT be connected
      => the add-on blue LED must blink

WARNING: process only if strictly needed!

usage:
    usart btfactory [-h]

options:
    -h, --help                     This help

examples/notes:
    usart btfactory               

```
parse result:
```
        "usart btfactory": {
            "command": "usart btfactory",
            "description": "Reset BT add-on to factory settings This requires 1) BTpower to be turned ON 2) BT add-on to NOT be connected => the add-on blue LED must blink",
            "notes": [],
            "offline": false,
            "options": [],
            "usage": ""
        },
``` 

**Expected behavior**
```
        "usart btfactory": {
            "command": "usart btfactory",
            "description": "Reset BT add-on to factory settings This requires 1) BTpower to be turned ON 2) BT add-on to NOT be connected => the add-on blue LED must blink WARNING: process only if strictly needed!",
            "notes": [
                "usart btfactory"
            ],
            "offline": false,
            "options": [
                "-h, --help This help"
            ],
            "usage": "usart btfactory [-h]"
        },
```

**Additional context**
More than 100 commands are not parsed correctly.
![图片](https://github.com/RfidResearchGroup/proxmark3/assets/62299611/1310115b-2176-4f71-86ef-4172f9cabe29)

I think it's caused by the regular expression in the `pm3_help2json.py`.
```
re_description = r'(?P<description>(?:.+\n)+)\n+'
```
It doesn't match the empty lines.

**Comment by iceman1001** [comment]
After playing with regex online...   The problem seem to be description regex.    When the description has empty lines in it,  the usage part fails..

![image](https://github.com/RfidResearchGroup/proxmark3/assets/8577004/d6949493-da9c-486c-bbe9-03769fe7b077)

**Comment by wh201906** [comment]
Yes. I think so.

**Comment by iceman1001** [comment]
complex regex..    there lots of mismatches.

**Comment by wh201906** [comment]
I tried to match every line with Positive Lookahead like this
```
(?P<description>(?:.*\n)+)\n+(?=usage)
```
It works on regex101.com, but not in the `pm3_help2json.py`

<details><summary>regex101.com</summary>

![图片](https://github.com/RfidResearchGroup/proxmark3/assets/62299611/65a5d2cc-a0fe-4e67-915d-44392b4076c6)

</details>

**Comment by iceman1001** [comment]
:)  funny,   I just pushed a fix based on the same idea.

This one remove all empty sub command help items, like  "lf help".   It also fixes a bunch of misses before.

If you don't mind to pull and test?

**Comment by iceman1001** [comment]
For the regex101.com to test properly you will need to give it the whole help text file.   Its lot to look through.
