### ISSUE TITLE
MAGIC_QL88 - error

### ISSUE THREAD

**Issue by jareckib** [RfidResearchGroup/proxmark3#2017]
![7](https://github.com/RfidResearchGroup/proxmark3/assets/116510448/692d78a7-a29a-4502-b42b-c2ffc2163af5)

![6](https://github.com/RfidResearchGroup/proxmark3/assets/116510448/fbc92b7f-39e0-47c1-9906-2be16ef73c87)

**Comment by iceman1001** [comment]
my bad,  pushed the missing define
