### ISSUE TITLE
Partial key view on hf mf super when key start with 0

### ISSUE THREAD

**Issue by TrixyCracker** [RfidResearchGroup/proxmark3#2047]
when key starts with zeroes, mfkey returns a partial key.
`
[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [            0 ]  LOOK HERE
[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000000
[#] Auth error

[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [            0 ]  LOOK HERE
[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000000
[#] Auth error

[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [            0 ]  LOOK HERE
[usb] pm3 --> hf mf rdbl --blk 0 -k 100000000000
[#] Auth error

[usb] pm3 --> hf mf rdbl --blk 0 -k 100000000000
[#] Auth error

[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [ 100000000000 ]
[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000001
[#] Auth error

[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000001
[#] Auth error

[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [            1 ]  LOOK HERE
[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [            1 ]  LOOK HERE
[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000011
[#] Auth error

[usb] pm3 --> hf mf super
[-] ⛔ failed to recover any key
[usb] pm3 --> hf mf super
^[[A[-] ⛔ failed to recover any key
[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000011
[#] Auth error

[usb] pm3 --> hf mf rdbl --blk 0 -k 000000000011
[#] Auth error

[usb] pm3 --> hf mf super
[+] UID: ED6F8104 Sector 00 key A [           11 ]  LOOK HERE
`

**Comment by iceman1001** [comment]
I don't have a super card,  so first of all, which one do you have?
 
And it is hard to duplicate the issue with your samples.  
How about you compliment with proper details?

**Comment by TrixyCracker** [comment]
> I don't have a super card, so first of all, which one do you have?
> 
> And it is hard to duplicate the issue with your samples. How about you compliment with proper details?

![Screenshot from 2023-07-20 20-45-32](https://github.com/RfidResearchGroup/proxmark3/assets/29796954/8dd1f72b-9fc3-405c-9826-d2887839f706)
it's easier to understand with a picture, as u can see, extension with zeroes not working, in fact instead of 000011223344 i can see only 11223344.

**Comment by iceman1001** [comment]
interesting,   all three possible places which prints that kind of line uses zero padding string formatters  (%012)
                                       
```
   PrintAndLogEx(SUCCESS, "UID: %s Sector %02x key %c [ " _GREEN_("%012" PRIX64) " ]",
```

**Comment by TrixyCracker** [comment]
> interesting, all three possible places which prints that kind of line uses zero padding string formatters (%012)
> 
> ```
>    PrintAndLogEx(SUCCESS, "UID: %s Sector %02x key %c [ " _GREEN_("%012" PRIX64) " ]",
> ```

im using previous version, my bad, in new version code seems correct
