### ISSUE TITLE
hitag - it's the same problem all the time

### ISSUE THREAD

**Issue by jareckib** [RfidResearchGroup/proxmark3#2048]
`[usb] pm3 --> lf search

[=] NOTE: some demods output possible binary
[=] if it finds something that looks like a tag
[=] False Positives ARE possible
[=]
[=] Checking for known tags...
[=]
lf hitag read: invalid option "--26"
[!] Try 'lf hitag read --help' for more information.

[|]Searching for COTAG tag......
[!] command execution time out

[-] No data found!
[?] Maybe not an LF tag?`

**Comment by iceman1001** [comment]
pull latest,  should be fixed
