### ISSUE TITLE
LEGIC Sim broken?

### ISSUE THREAD

**Issue by 0none** [RfidResearchGroup/proxmark3#2056]
**Describe the bug**

Somewhere between the latest release ("seven") and master, tie ability to simulate a legic prime 1024 was lost.
Recompiling and repeating on current master (1a4df13aaec982f66777b06e1231807eaba54979) the B and C lights flicker on, but the reader does not react.

**To Reproduce**

- clone current master 
- flash firmware
- dump MIM1024 card
- eload dump to memory
- simulate
- try to authenticate against reader using simulated card

**Expected behavior**

Loading the same dump file to memory, at "seven" the pm3 (generic) successfully transmits to the reader, in this case a door control system, authenticating the user and opening the door.

**Desktop (please complete the following information):**

 OS: Ubuntu on WSL2 / Windows 11

<details><summary>hw version</summary>

    ```
    [ Proxmark3 RFID instrument ]

    [ CLIENT ]
    Iceman/master/v4.16717-236-g7f5590d94 2023-07-27 12:06:44 f67bd6537
    compiled with............. GCC 12.2.0
    platform.................. Linux / x86_64
    Readline support.......... present
    QT GUI support............ present
    native BT support......... present
    Python script support..... present
    Lua SWIG support.......... present
    Python SWIG support....... present

    [ PROXMARK3 ]
    firmware.................. PM3 GENERIC

    [ ARM ]
    bootrom: Iceman/master/v4.16717-236-g7f5590d94 2023-07-27 12:06:30 f67bd6537
        os: Iceman/master/v4.16717-236-g7f5590d94 2023-07-27 12:06:58 f67bd6537
    compiled with GCC 12.2.1 20221205

    [ FPGA ]
    fpga_pm3_lf.ncd image 2s30vq100 2023-07-12 16:12:04
    fpga_pm3_hf.ncd image 2s30vq100 2023-07-12 16:12:14
    fpga_pm3_felica.ncd image 2s30vq100 2023-07-12 16:12:34
    fpga_pm3_hf_15.ncd image 2s30vq100 2023-07-12 16:12:24

    [ Hardware ]
    --= uC: AT91SAM7S512 Rev B
    --= Embedded Processor: ARM7TDMI
    --= Internal SRAM size: 64K bytes
    --= Architecture identifier: AT91SAM7Sxx Series
    --= Embedded flash memory 512K bytes ( 60% used )
    ```
</details>
<details><summary>hw status</summary>

    ```
    [#] Memory
    [#]   BigBuf_size............. 42400
    [#]   Available memory........ 42400
    [#] Tracing
    [#]   tracing ................ 1
    [#]   traceLen ............... 0
    [#] Current FPGA image
    [#]   mode.................... fpga_pm3_hf.ncd image 2s30vq100 2023-07-12 16:12:14
    [#] LF Sampling config
    [#]   [q] divisor............. 95 ( 125.00 kHz )
    [#]   [b] bits per sample..... 8
    [#]   [d] decimation.......... 1
    [#]   [a] averaging........... yes
    [#]   [t] trigger threshold... 0
    [#]   [s] samples to skip..... 0
    [#]
    [#] LF T55XX config
    [#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
    [#]            mode            |start|write|write|write| read|write|write
    [#]                            | gap | gap |  0  |  1  | gap |  2  |  3
    [#] ---------------------------+-----+-----+-----+-----+-----+-----+------
    [#] fixed bit length (default) |  31 |  20 |  18 |  50 |  15 | N/A | N/A |
    [#]     long leading reference |  31 |  20 |  18 |  50 |  15 | N/A | N/A |
    [#]               leading zero |  31 |  20 |  18 |  40 |  15 | N/A | N/A |
    [#]    1 of 4 coding reference |  31 |  20 |  18 |  34 |  15 |  50 |  66 |
    [#]
    [#] HF 14a config
    [#]   [a] Anticol override.... std    ( follow standard )
    [#]   [b] BCC override........ std    ( follow standard )
    [#]   [2] CL2 override........ std    ( follow standard )
    [#]   [3] CL3 override........ std    ( follow standard )
    [#]   [r] RATS override....... std    ( follow standard )
    [#] Transfer Speed
    [#]   Sending packets to client...
    [#]   Time elapsed................... 500ms
    [#]   Bytes transferred.............. 286720
    [#]   Transfer Speed PM3 -> Client... 573440 bytes/s
    [#] Various
    [#]   Max stack usage......... 4088 / 8480 bytes
    [#]   Debug log level......... 1 ( error )
    [#]   ToSendMax............... -1
    [#]   ToSend BUFFERSIZE....... 2308
    [#]   Slow clock.............. 29609 Hz
    [#] Installed StandAlone Mode
    [#]   LF HID26 standalone - aka SamyRun (Samy Kamkar)
    [#]
    ```
</details>

<details><summary>data tune</summary>

    ```
    [=] ---------- Reminder ------------------------
    [=] `hw tune` doesn't actively tune your antennas,
    [=] it's only informative.
    [=] Measuring antenna characteristics, please wait...
    🕛   9
    [=] ---------- LF Antenna ----------
    [+] LF antenna: 42.15 V - 125.00 kHz
    [+] LF antenna: 32.99 V - 134.83 kHz
    [+] LF optimal: 42.91 V - 126.32 kHz
    [+] Approx. Q factor (*): 7.3 by frequency bandwidth measurement
    [+] Approx. Q factor (*): 12.5 by peak voltage measurement
    [!] ⚠  Contradicting measures seem to indicate you're running a PM3GENERIC firmware on a RDV4
    [!] ⚠  False positives is possible but please check your setup
    [+] LF antenna is OK
    [=] ---------- HF Antenna ----------
    [+] HF antenna: 30.74 V - 13.56 MHz
    [+] Approx. Q factor (*): 8.9 by peak voltage measurement
    [+] HF antenna is OK

    (*) Q factor must be measured without tag on the antenna

    [+] Displaying LF tuning graph. Divisor 88 (blue) is 134.83 kHz, 95 (red) is 125.00 kHz.
    ```
</details>

</br>

**Additional context**

<details>
    <summary>tracelog data from working tag sim:</summary>

    [=] downloading tracelog data from device
    [+] Recorded activity (trace len = 388 bytes)
    [=] start = start of start frame end = end of frame. src = source of transfer
    [=] LEGIC - Reader Mode: Timings are in ticks (1us == 1.5ticks)
    [=]         Tag Mode: Timings are in sub carrier periods (1/212 kHz == 4.7us)

        Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
    ------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
            0 |        132 | Rdr |07  39  00  00                                                           |     | IV 0x39
            202 |        328 | Tag |06  1d  00                                                               |     |
            381 |        483 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
            541 |        709 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
            779 |       1031 | Tag |0c  57  06                                                               |     |
        1087 |       1231 | Rdr |09  03  00  00                                                           |     | READ Byte(1)
        1301 |       1553 | Tag |0c  a4  07                                                               |     |
        1609 |       1777 | Rdr |09  05  00  00                                                           |     | READ Byte(2)
        1847 |       2099 | Tag |0c  de  06                                                               |     |
        2155 |       2315 | Rdr |09  07  00  00                                                           |     | READ Byte(3)
        2385 |       2637 | Tag |0c  e9  08                                                               |     |
        2693 |       2869 | Rdr |09  09  00  00                                                           |     | READ Byte(4)
        2939 |       3191 | Tag |0c  b3  08                                                               |     |
        3625 |       3769 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        3839 |       4091 | Tag |0c  57  06                                                               |     |
        4147 |       4307 | Rdr |09  03  00  00                                                           |     | READ Byte(1)
        4377 |       4629 | Tag |0c  a4  07                                                               |     |
        4685 |       4853 | Rdr |09  05  00  00                                                           |     | READ Byte(2)
        4923 |       5175 | Tag |0c  de  06                                                               |     |
        5231 |       5407 | Rdr |09  07  00  00                                                           |     | READ Byte(3)
        5477 |       5729 | Tag |0c  e9  08                                                               |     |
        5785 |       5961 | Rdr |09  09  00  00                                                           |     | READ Byte(4)
        6031 |       6283 | Tag |0c  b3  08                                                               |     |
        6381 |       6549 | Rdr |09  0d  00  00                                                           |     | READ Byte(6)
        6619 |       6871 | Tag |0c  ff  00                                                               |     |
        6927 |       7111 | Rdr |09  0b  00  00                                                           |     | READ Byte(5)
        7181 |       7433 | Tag |0c  ff  0d                                                               |     |
        7489 |       7665 | Rdr |09  0f  00  00                                                           |     | READ Byte(7)
        7735 |       7987 | Tag |0c  00  0e                                                               |     |
        8043 |       8195 | Rdr |09  11  00  00                                                           |     | READ Byte(8)
        8265 |       8517 | Tag |0c  00  05                                                               |     |

</details>

<details>
    <summary>tracelog data from broken tag sim:</summary>

    [=] downloading tracelog data from device
    [+] Recorded activity (trace len = 2391 bytes)
    [=] start = start of start frame end = end of frame. src = source of transfer
    [=] LEGIC - Reader Mode: Timings are in ticks (1us == 1.5ticks)
    [=]         Tag Mode: Timings are in sub carrier periods (1/212 kHz == 4.7us)

        Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
    ------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
            0 |        132 | Rdr |07  0f  00  00                                                           |     | IV 0x0F
            202 |        328 | Tag |06  1d  00                                                               |     |
            381 |        491 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
            549 |        717 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
            787 |       1039 | Tag |0c  57  06                                                               |     |
        1095 |       1263 | Rdr |09  37  00  00                                                           |     | READ Byte(27)
        1641 |       1809 | Rdr |09  5a  01  00                                                           |     | WRITE Byte(173)
        6376 |       6524 | Rdr |07  77  00  00                                                           |     | IV 0x77
        6594 |       6720 | Tag |06  1d  00                                                               |     |
        6773 |       6891 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        6949 |       7125 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        7195 |       7447 | Tag |0c  57  06                                                               |     |
        7503 |       7679 | Rdr |09  5d  01  00                                                           |     | READ Byte(174)
        8057 |       8201 | Rdr |09  42  00  00                                                           |     | WRITE Byte(33)
        12722 |      12854 | Rdr |07  47  00  00                                                           |     | IV 0x47
        12924 |      13050 | Tag |06  1d  00                                                               |     |
        13103 |      13205 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        13263 |      13439 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        13509 |      13761 | Tag |0c  57  06                                                               |     |
        13817 |      13969 | Rdr |09  19  00  00                                                           |     | READ Byte(12)
        14347 |      14531 | Rdr |09  af  01  00                                                           |     | READ Byte(215)
        19100 |      19224 | Rdr |07  0b  00  00                                                           |     | IV 0x0B
        19294 |      19420 | Tag |06  1d  00                                                               |     |
        19473 |      19583 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        19641 |      19809 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        19879 |      20131 | Tag |0c  57  06                                                               |     |
        20187 |      20371 | Rdr |09  df  00  00                                                           |     | READ Byte(111)
        20749 |      20917 | Rdr |09  93  01  00                                                           |     | READ Byte(201)
        25432 |      25564 | Rdr |07  27  00  00                                                           |     | IV 0x27
        25634 |      25760 | Tag |06  1d  00                                                               |     |

</details>

**Comment by iceman1001** [comment]
hmm..
I see,   pull latest and see if it works better again?

**Comment by 0none** [comment]
Unfortunately the situation seems unchanged

<details>
  <summary>log attached</summary>


    [=] downloading tracelog data from device
    [+] Recorded activity (trace len = 1145 bytes)
    [=] start = start of start frame end = end of frame. src = source of transfer
    [=] LEGIC - Reader Mode: Timings are in ticks (1us == 1.5ticks)
    [=]         Tag Mode: Timings are in sub carrier periods (1/212 kHz == 4.7us)


        Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation
    ------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------
            0 |        116 | Rdr |07  03  00  00                                                           |     | IV 0x03
            186 |        312 | Tag |06  1d  00                                                               |     |
            533 |        709 | Rdr |09  e7  00  00                                                           |     | READ Byte(115)
        1087 |       1279 | Rdr |09  fe  01  00                                                           |     | WRITE Byte(255)
        6371 |       6487 | Rdr |07  05  00  00                                                           |     | IV 0x05
        6557 |       6683 | Tag |06  1d  00                                                               |     |
        6736 |       6854 | Rdr |06  2b  00  00                                                           |     |
        6912 |       7048 | Rdr |09  08  00  00                                                           |     | WRITE Byte(4)
        7426 |       7578 | Rdr |09  30  01  00                                                           |     | WRITE Byte(152)
        12721 |      12861 | Rdr |07  5d  00  00                                                           |     | IV 0x5D
        12931 |      13057 | Tag |06  1d  00                                                               |     |
        13110 |      13212 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        13270 |      13454 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        13524 |      13776 | Tag |0c  57  06                                                               |     |
        13832 |      14000 | Rdr |09  ec  00  00                                                           |     | WRITE Byte(118)
        14378 |      14538 | Rdr |09  64  01  00                                                           |     | WRITE Byte(178)
        19056 |      19164 | Rdr |07  01  00  00                                                           |     | IV 0x01
        19234 |      19360 | Tag |06  1d  00                                                               |     |
        19413 |      19507 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        19565 |      19725 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        19795 |      20047 | Tag |0c  57  06                                                               |     |
        20103 |      20271 | Rdr |09  a3  01  00                                                           |     | READ Byte(209)
        20649 |      20793 | Rdr |09  42  00  00                                                           |     | WRITE Byte(33)
        25394 |      25526 | Rdr |07  55  00  00                                                           |     | IV 0x55
        25596 |      25722 | Tag |06  1d  00                                                               |     |
        25775 |      25885 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        25943 |      26111 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        26181 |      26433 | Tag |0c  57  06                                                               |     |
        26489 |      26665 | Rdr |09  7c  01  00                                                           |     | WRITE Byte(190)
        27043 |      27219 | Rdr |09  fc  00  00                                                           |     | WRITE Byte(126)
        31738 |      31870 | Rdr |07  0f  00  00                                                           |     | IV 0x0F
        31940 |      32066 | Tag |06  1d  00                                                               |     |
        32119 |      32229 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        32287 |      32455 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        32525 |      32777 | Tag |0c  57  06                                                               |     |
        32833 |      33001 | Rdr |09  37  00  00                                                           |     | READ Byte(27)
        33379 |      33547 | Rdr |09  5a  01  00                                                           |     | WRITE Byte(173)
        38083 |      38231 | Rdr |07  7d  00  00                                                           |     | IV 0x7D
        38301 |      38427 | Tag |06  1d  00                                                               |     |
        38480 |      38582 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        38640 |      38808 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        38878 |      39130 | Tag |0c  57  06                                                               |     |
        39186 |      39338 | Rdr |09  28  01  00                                                           |     | WRITE Byte(148)
        39716 |      39892 | Rdr |09  dc  01  00                                                           |     | WRITE Byte(238)
        44425 |      44565 | Rdr |07  1f  00  00                                                           |     | IV 0x1F
        44635 |      44761 | Tag |06  1d  00                                                               |     |
        44814 |      44924 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        44982 |      45150 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        45220 |      45472 | Tag |0c  57  06                                                               |     |
        45528 |      45680 | Rdr |09  86  00  00                                                           |     | WRITE Byte(67)
        46058 |      46242 | Rdr |09  dd  01  00                                                           |     | READ Byte(238)
        50766 |      50906 | Rdr |07  6d  00  00                                                           |     | IV 0x6D
        50976 |      51102 | Tag |06  1d  00                                                               |     |
        51155 |      51265 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        51323 |      51499 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        51569 |      51821 | Tag |0c  57  06                                                               |     |
        51877 |      52061 | Rdr |09  dd  01  00                                                           |     | READ Byte(238)
        52439 |      52623 | Rdr |09  7d  01  00                                                           |     | READ Byte(190)
        57114 |      57254 | Rdr |07  73  00  00                                                           |     | IV 0x73
        57324 |      57450 | Tag |06  1d  00                                                               |     |
        57503 |      57613 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        57671 |      57831 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        57901 |      58153 | Tag |0c  57  06                                                               |     |
        58209 |      58369 | Rdr |09  d0  01  00                                                           |     | WRITE Byte(232)
        58747 |      58899 | Rdr |09  11  01  00                                                           |     | READ Byte(136)
        63456 |      63596 | Rdr |07  75  00  00                                                           |     | IV 0x75
        63666 |      63792 | Tag |06  1d  00                                                               |     |
        64029 |      64189 | Rdr |09  a1  01  00                                                           |     | READ Byte(208)
        64567 |      64727 | Rdr |09  8a  01  00                                                           |     | WRITE Byte(197)
        69796 |      69928 | Rdr |07  1d  00  00                                                           |     | IV 0x1D
        69998 |      70124 | Tag |06  1d  00                                                               |     |
        70177 |      70295 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        70353 |      70505 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        70575 |      70827 | Tag |0c  57  06                                                               |     |
        70883 |      71051 | Rdr |09  5e  00  00                                                           |     | WRITE Byte(47)
        71429 |      71597 | Rdr |09  e3  00  00                                                           |     | READ Byte(113)
        76130 |      76254 | Rdr |07  19  00  00                                                           |     | IV 0x19
        76324 |      76450 | Tag |06  1d  00                                                               |     |
        76503 |      76613 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        76671 |      76823 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        76893 |      77145 | Tag |0c  57  06                                                               |     |
        77201 |      77369 | Rdr |09  b2  01  00                                                           |     | WRITE Byte(217)
        77747 |      77939 | Rdr |09  7f  01  00                                                           |     | READ Byte(191)
        82499 |      82622 | Rdr |07  23  00  00                                                           |     | IV 0x23
        82692 |      82818 | Tag |06  1d  00                                                               |     |
        82871 |      82973 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
        83031 |      83191 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
        83261 |      83513 | Tag |0c  57  06                                                               |     |
        83569 |      83721 | Rdr |09  0e  00  00                                                           |     | WRITE Byte(7)
        84099 |      84275 | Rdr |09  d5  01  00                                                           |     | READ Byte(234)
    [usb] pm3 -->

</details>

**Comment by 0none** [comment]
Reverting the changes made to armsrc/legicrfsim.c in commit c70e5beeac7229605690230985e029031ae37a59 seems to fix the issue for me, tough I am not exactly sure what exactly causes it. 
Sorry if this is vague, I'm not a programmer.

**Comment by iceman1001** [comment]
hm..
pull latest and test again

**Comment by 0none** [comment]
Sorry for the delay.
Doesn't seem to have worked.


<details>
  <summary>log attached</summary>


      Start |        End | Src | Data (! denotes parity error)                                           | CRC | Annotation                                                                                      ------------+------------+-----+-------------------------------------------------------------------------+-----+--------------------                                                                                       0 |        132 | Rdr |07  47  00  00                                                           |     | IV 0x47                                                                                                 202 |        328 | Tag |06  1d  00                                                               |     |                                                                                                         381 |        483 | Rdr |06  39  00  00                                                           |     | ACK 256/1024                                                                                            541 |        717 | Rdr |09  01  00  00                                                           |     | READ Byte(0)                                                                                            787 |       1039 | Tag |0c  57  06                                                               |     |                                                                                                        1095 |       1247 | Rdr |09  19  00  00                                                           |     | READ Byte(12)
       1625 |       1809 | Rdr |09  af  01  00                                                           |     | READ Byte(215)
       6382 |       6522 | Rdr |07  75  00  00                                                           |     | IV 0x75
       6592 |       6718 | Tag |06  1d  00                                                               |     |
       6771 |       6897 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
       6955 |       7115 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
       7185 |       7437 | Tag |0c  57  06                                                               |     |
       7493 |       7645 | Rdr |09  88  01  00                                                           |     | WRITE Byte(196)
       8023 |       8159 | Rdr |09  40  00  00                                                           |     | WRITE Byte(32)
      12724 |      12856 | Rdr |07  33  00  00                                                           |     | IV 0x33
      12926 |      13052 | Tag |06  1d  00                                                               |     |
      13105 |      13199 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
      13257 |      13417 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
      13487 |      13739 | Tag |0c  57  06                                                               |     |
      13795 |      13963 | Rdr |09  76  00  00                                                           |     | WRITE Byte(59)
      14341 |      14525 | Rdr |09  bb  01  00                                                           |     | READ Byte(221)
      19069 |      19209 | Rdr |07  1f  00  00                                                           |     | IV 0x1F
      19279 |      19405 | Tag |06  1d  00                                                               |     |
      19458 |      19568 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
      19626 |      19794 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
      19864 |      20116 | Tag |0c  57  06                                                               |     |
      20186 |      20324 | Rdr |08  43  00  00                                                           |     |
      20702 |      20886 | Rdr |09  dd  01  00                                                           |     | READ Byte(238)
      25440 |      25580 | Rdr |07  6b  00  00                                                           |     | IV 0x6B
      25650 |      25776 | Tag |06  1d  00                                                               |     |
      25829 |      25947 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
      26005 |      26157 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
      26227 |      26479 | Tag |0c  57  06                                                               |     |
      26535 |      26687 | Rdr |09  23  00  00                                                           |     | READ Byte(17)
      27065 |      27233 | Rdr |09  e4  01  00                                                           |     | WRITE Byte(242)
      31768 |      31884 | Rdr |07  03  00  00                                                           |     | IV 0x03
      31954 |      32080 | Tag |06  1d  00                                                               |     |
      32133 |      32243 | Rdr |06  39  00  00                                                           |     | ACK 256/1024
      32301 |      32477 | Rdr |09  01  00  00                                                           |     | READ Byte(0)
      32547 |      32799 | Tag |0c  57  06                                                               |     |
      32855 |      33039 | Rdr |09  fc  01  00                                                           |     | WRITE Byte(254)
      33417 |      33569 | Rdr |09  41  01  00                                                           |     | READ Byte(160)
      38108 |      38240 | Rdr |07  33  00  00                                                           |     | IV 0x33
      38310 |      38436 | Tag |06  1d  00                                                               |     |


</details>

**Comment by iceman1001** [comment]
Pull latest and it should work just fine again
