### ISSUE TITLE
Mf Magic Gen4 GDM possible config

### ISSUE THREAD

**Issue by gid9798** [RfidResearchGroup/proxmark3#2073]
**Is your feature request related to a problem? Please describe.**
Possible configuration option `850000000000005A00FF005A00000008`
This option disables shadow mode, and the card behaves like a regular CUID (directwrite)

**Describe the solution you'd like**
On/off shadow mode command in `hf mf gdm...` menu

**Describe alternatives you've considered**
Adding this config to the description `hf mf gdmsetcfg -h`
and in the documentation `proxmark3/doc/magic_cards_notes.md`

**Additional context**
I ordered these cards on aliexpress as gen2(CUID)
They really worked like gen2.
`hf search` revealed `Magic capabilities : Gen 4 GDM`
but the `hf mf gdmsetblk `command did not work on the starting config
`hf mf gdmcfg` returned: `850000000000005A00FF005A00000008`

After switching to shadow mode (`hf mf gdmsetcfg -d 850000000000000000005A5A00000008`), the `hf mf gdmsetblk` record started working
Also, when switching from normal mode to shadow mode, the card remembers the value of the blocks

**Comment by team-orangeBlue** [comment]
We're working on all possible USCUID (official and general name for similar tags, GDM is a variation) configurations, see #2003

**Comment by team-orangeBlue** [comment]
Config was added.

Probably should be closed by now
