### ISSUE TITLE
Termux client source compilation documentation does not work 

### ISSUE THREAD

**Issue by celowsky** [RfidResearchGroup/proxmark3#2076]
***Compilation problems***
Try compiling with verbose.  `make VERBOSE=1` with main makefile or `make V=1` with cmake.

**Describe the bug**
When following the instructions described in the Termux setup documentation [here](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/termux_notes.md#optional-building-proxmark3-client-from-source) to compile the proxmark3 client, an error occurs during the `make` process. The error looks like the following:

---
===================================================================
[*] MAKE client/all
===================================================================
Version info:      Iceman/master/v4.16717-322-gd6e36f8b7
Client platform:   Linux                              GUI support:       QT not found, disabled
native BT support: Bluez not found, disabled
Jansson library:   system library not found, using local library                                            Lua library:       system library not found, using local library
Python3 library:   Python3 v3.11 found, enabled
Readline library:  enabled
Whereami library:  system library not found, using local library
Lua SWIG:          wrapper found
Python SWIG:       wrapper found
compiler version:  clang version 16.0.6               ===================================================================                                         [-] CC src/mifare/aiddesfire.c                        [-] CC src/aidsearch.c
[-] CC src/atrs.c                                     [-] CC src/cmdanalyse.c
src/cmdanalyse.c:1121:87: error: floating-point comparison is always false; constant cannot be represented exactly in type 'float' [-Werror,-Wliteral-range]              PrintAndLogEx(INFO, "   1 ETU = %3.2f US (expect 9.44) %s", test_us, (test_us == 9.44) ? _GREEN_("ok") : _RED_("fail"));
                                                                              ~~~~~~~ ^  ~~~~               src/cmdanalyse.c:1123:88: error: floating-point comparison is always false; constant cannot be represented exactly in type 'float' [-Werror,-Wliteral-range]              PrintAndLogEx(INFO, "  10 ETU = %4.2f US (expect 94.40) %s", test_us, (test_us == 94.40) ? _GREEN_("ok") : _RED_("fail"));
                                                                               ~~~~~~~ ^  ~~~~~             src/cmdanalyse.c:1125:89: error: floating-point comparison is always false; constant cannot be represented exactly in type 'float' [-Werror,-Wliteral-range]              PrintAndLogEx(INFO, "  32 ETU = %5.2f US (expect 302.06) %s", test_us, (test_us == 320.06) ? _GREEN_("ok") : _RED_("fail"));                                                                                                              ~~~~~~~ ^  ~~~~~~
3 errors generated.
make[1]: *** [Makefile:941: obj/cmdanalyse.o] Error 1
make: *** [Makefile:171: client/all] Error 2
---
**To Reproduce**
Steps to reproduce the behavior:
1. Follow the directions written [here](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/termux_notes.md#optional-building-proxmark3-client-from-source)
```
pkg install make clang readline libc++ git binutils
git clone https://github.com/RfidResearchGroup/proxmark3.git
cd proxmark3
make clean && make client
``` 
Use the latest from master at the time of this issue's writing. This is commit **d6e36f8b7a00afc36c48f6bb15123688dd80d454**.
4. See error described above.

**Expected behavior**
The client compiles correctly in Termux.

**Desktop (please complete the following information):**
 - OS: 
 ```
 Distributor ID: Linuxmint
Description:    Linux Mint 20.1
Release:        20.1
Codename:       ulyssa
```

**Additional Context**
I tried using the suggestions from [here](https://discord.com/channels/738045391416852520/790252611361964093/1138199503422365727) without success

**Comment by iceman1001** [comment]
looks like a type conversion error,   not a biggie,
