### ISSUE TITLE
/usr/lib/gcc/arm-none-eabi/13.2.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory

### ISSUE THREAD

**Issue by strasharo** [RfidResearchGroup/proxmark3#2112]
**Describe the bug**
Trying to build on latest Fedora 38 I'm getting the following error

[-] CC version_pm3.c
In file included from ../include/common.h:22,
                 from version_pm3.c:1:
/usr/lib/gcc/arm-none-eabi/13.2.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
make[1]: *** [../common_arm/Makefile.common:133: obj/version_pm3.o] Error 1
make: *** [Makefile:171: bootrom/all] Error 2

**To Reproduce**
1. Clone the repo
2. cd into the repo
3. make PLATFORM=PM3GENERIC VERBOSE=1
4. Getting this error:

[-] CC version_pm3.c
In file included from ../include/common.h:22,
                 from version_pm3.c:1:
/usr/lib/gcc/arm-none-eabi/13.2.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
    9 | # include_next <stdint.h>
      |                ^~~~~~~~~~
compilation terminated.
make[1]: *** [../common_arm/Makefile.common:133: obj/version_pm3.o] Error 1
make: *** [Makefile:171: bootrom/all] Error 2

**Expected behavior**
Pm2 should compile

**Desktop (please complete the following information):**
 - OS: Fedora 38

**Comment by iceman1001** [comment]
Is your dev env set up correct?

**Comment by iceman1001** [comment]
well,  the error is suggesting system libs not there.   Nothing to do with the pm3 source.

I would look at the installation note:
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md#on-fedora
