### ISSUE TITLE
Getting Target.... device / fw mismatch, please help?

### ISSUE THREAD

**Issue by michalss** [RfidResearchGroup/proxmark3#2114]
-

**Describe the bug**
I'm scare to run pm3-flash-all, since im afraid i brick the device... I have been following the tutorial and all went smoot but i cannot run flashing comman?

![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/33c6f42c-c5ba-4701-9966-12e3da11ab15)

![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/387a25b7-647d-4026-8709-e059d7a032da)

**Screenshots**
![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/b7aaa129-d13b-4d55-aa8a-62f93eea8be3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.x.x LTS

**Additional context**
![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/1e236af0-97a1-4084-9832-06c94da4e6c2)

**Comment by michalss** [comment]
Now i was able to flash it ok.. but im getting 

![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/2f29aaef-89dd-4e48-8851-0f97f22ce97b)

**Comment by michalss** [comment]
how to fix this pls ?

**Comment by iceman1001** [comment]
We use the discord server for user related questions. 

In your case here,   are you sure you complied for the target hw  and flashed the device ,  then using the same client from the build?

I.e,     In the proxmark world the Firmware goes hand in hand with the Software.    Don't mix 'em up.

**Comment by iceman1001** [comment]
That would be the installation guide.   
You should look at the compilation guide linked to in the bottom of the installation guide.
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Use_of_Proxmark/0_Compilation-Instructions.md
And take notice of which device you have.

**Comment by michalss** [comment]
Well i have been through this already. Problem is im not exactly sure what version i do have. I got it from here ..

https://www.aliexpress.com/item/1005005209158934.html?spm=a2g0o.order_detail.order_detail_item.3.3ca0f19cp0sXWq

**Comment by michalss** [comment]
All i did found is this AT91SAM7S512  and 512Kb..

**Comment by michalss** [comment]
this could lead to an issue :D
[!] ⚠️  Contradicting measures seem to indicate you're running a PM3_RDV4 firmware on a generic device

**Comment by michalss** [comment]
ok i will recompile it with generic platform tag.. thx ill try this

**Comment by michalss** [comment]
ok closing it worked 

![image](https://github.com/RfidResearchGroup/proxmark3/assets/1000729/10b56f0d-fac0-48fb-9757-fef297c81d8d)

**Comment by iceman1001** [comment]
That device is not a RDV4 as you guessed.  You built the repo with that setting,  which lead to your issues.
Once understanding you need to change target for compilation,   a flash and voilá  you are on your feet again.

I do recommend the RFID Hacking discord server.
