### ISSUE TITLE
lf em 4x05 chk

### ISSUE THREAD

**Issue by jareckib** [RfidResearchGroup/proxmark3#2119]
Password search doesn't work. Each time you run the command, you will get different passwords found. 
None of the found passwords work.

**Comment by iceman1001** [comment]
You would need to fill in some more details in order to look into what is not working....

**Comment by jareckib** [comment]
There's nothing to explain. I have several Em4305 with a password imposed by a Chinese duplicator. After running the command ---lf em 4x05 chk... it finds the passwords from the file, or it does not find them... Unfortunately, the ones found do not work either....19924027....or 11111111 or ABCD1234 or 44444444 etc.

**Comment by iceman1001** [comment]
Not really constructive feedback.  

Your opinion on the commands is most likely best expressed in the discord server. 

Closing.
