### ISSUE TITLE
Mf Classic keys for elevator cards

### ISSUE THREAD

**Issue by LowSkillDeveloper** [RfidResearchGroup/proxmark3#2120]
Keys that are used in cards for using elevators in Ukraine, in Kherson.

AC37E76385F5
576DCFFF2F25

Yes, people are forced to pay for elevator rides in their own homes. If you don't want to, walk up to the 9th floor :)
If anyone is interested, sector 3 indicates the number of available trips.

**Comment by iceman1001** [comment]
https://github.com/RfidResearchGroup/proxmark3/commit/3d9d8253a6ba4b19e5430ef8a5442f1472f402e0

**Comment by iceman1001** [comment]
Thanks!

if you have dumps of such cards, feel free to send them to me.
