### ISSUE TITLE
About ISO 14443B' tags

### ISSUE THREAD

**Issue by jacopo-j** [RfidResearchGroup/proxmark3#215]
Hello. I'm interested in reading ISO 14443B' (Innovatron pre-ISO 14443B) Calypso cards, which at the current state of things don't seem to be supported – or even detected – by the Proxmark client.

I am willing to implement at least some basic features for getting information and/or reading those tags myself, however I'm struggling to find any sort of documentation about how to communicate with the tags. Communication sniffing in 14b mode seems to produce unreliable results, and I still weren't able to have the card respond to raw 14b commands.

libnfc can at least select ISO 14443B' cards and is able to print the ATS and UID, but I couldn't find any information about how to select the card myself and send raw APDU commands.

Calypso cards (Navigo cards in particular) were previously discussed on Proxmark forums [here](http://www.proxmark.org/forum/viewtopic.php?id=2533) and [here](http://www.proxmark.org/forum/viewtopic.php?id=2572). A [calypso.lua](https://github.com/RfidResearchGroup/proxmark3/blob/master/client/scripts/calypso.lua) script exists in this repository but only works with standard 14443B cards.

Does anybody have further information about this topic?

**Comment by joanbono** [comment]
Interested on that also.
I found a while ago Navigoat, an android application which was taking information from the Navigo card (last stations and so on), maybe it;s possible to use that information to decode some of the obtained data somehow (can be found [here](https://github.com/sp1d3rb0y/Navigoat/tree/master/app/src/main/res/xml) )

I should have one or two navigos at home, but I'm not living in Paris :/

**Comment by iceman1001** [comment]
Indeed interesting to get calypso support.
The calypso lua script was thought of getting the cardpeek apdu's as a base to operate it.
As you noticed the 14B wasn't good and 14B' non-existent.    The need to implement signal modulation/demodulatio ,  encoding / decoding of 14B' protocol,   and client support..

I would say start with getting 14B better.  There is a fix for fpga signaling in offical repo that is on my todo list to implement in this repo.  That will increase the 14a/14b/15 communications.  And could most likely be uses for FeliCa and 14B'  protocols. 

Old issues I did over at Iceman fork.
https://github.com/iceman1001/proxmark3/issues/41
https://github.com/iceman1001/proxmark3/issues/39

**Comment by doegox** [comment]
FTR modulations are the same as for typeB, typeB' has just a different "anticollision" phase. (and latest Navigo Easy are pure typeB, not typeB' anymore)

**Comment by doegox** [comment]
You can find an example how to talk to typeB' here:
https://github.com/nfc-tools/libnfc/blob/master/examples/pn53x-tamashell-scripts/ReadNavigo.sh
For newer Navigo typeB, it looks more like Mobibi:
https://github.com/nfc-tools/libnfc/blob/master/examples/pn53x-tamashell-scripts/ReadMobib.sh

**Comment by iceman1001** [comment]
I am not sure how to read the anticollision phase from those tamashell scripts.

**Comment by doegox** [comment]
Very first command equivalent is
`hf 14b raw -c -p 010b3f80`
but it seems the Proxmark3 doesn't see the answer.

Here are (decimated) captures from another proxmark with `hf sniff`
First: sniffing libnfc  tamashell `42:010b3f80`
![image](https://user-images.githubusercontent.com/60773/94732659-d761f200-0366-11eb-8b4d-e8b19804db54.png)
Then sniffing pm3 `hf 14b raw -c -p 010b3f80`
![image](https://user-images.githubusercontent.com/60773/94732794-08422700-0367-11eb-923a-c619edc252bf.png)
Note also the two extra signals at end of pm3 command ?!

**Comment by doegox** [comment]
So after bugfix and addition of 14b' framing support, here we are:
![image](https://user-images.githubusercontent.com/60773/94865680-50804880-043e-11eb-9689-bfc667942edf.png)

**Comment by iceman1001** [comment]
Remarkable!

**Comment by iceman1001** [comment]
What is the select / anti collision for 14b'   ?

**Comment by valtoo16** [comment]
> So after bugfix and addition of 14b' framing support, here we are: ![image](https://user-images.githubusercontent.com/60773/94865680-50804880-043e-11eb-9689-bfc667942edf.png)

hello, sorry for the reopening...
But I am facing this problem and with the latest relase and an rdv4 proxmark the command is not running. Did you publish your changes or did you just do it "locally"
If so, your modification will interest me :)

**Comment by iceman1001** [comment]
yes, it was all commited.

**Comment by valtoo16** [comment]
> yes, it was all commited.

it's strange because I do not have the return of the order on a calypso card... ( and with hf sniff, i have a modulation)

**Comment by doegox** [comment]
Are you sure your Calypso is 14b' ? All modern Calypso are 14b nowadays

**Comment by valtoo16** [comment]
> Are you sure your Calypso is 14b' ? All modern Calypso are 14b nowadays

I don' know, if the card repond to 14b select (05 00 00), it can't be 14b 'at the same time?
(I don't know I can't find any documentation on this subject)


https://image.prntscr.com/image/nVxeqSHVQ_ybOm6TlgK4jg.png

**Comment by doegox** [comment]
No it can't be both. If it replies to 14b select, it *is* 14b.
Read the specs for more info.
