### ISSUE TITLE
Building against Python 3.12 is broken

### ISSUE THREAD

**Issue by dogtopus** [RfidResearchGroup/proxmark3#2182]
**Describe the bug**

Python 3.12.0 has a bug (python/cpython#106560) that will cause the compilation of pm3 client to fail.

A workaround would simply be disabling `-Werror` for `redundant-decls`.

**To Reproduce**
1. Build proxmark3 client with Python 3.12.0
2. See it fail with `-Werror=redundant-decls`

**Expected behavior**
Build under Python 3.12.0 successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version
 - hw status
 - data tune

**Additional context**

**Comment by wh201906** [comment]
Does the cmake work?

**Comment by dogtopus** [comment]
@wh201906 Presumably no since it's a Python issue, unless CMake didn't honor `-Werror` by default for some reason.

**Comment by wh201906** [comment]
I don't have Fedora 39 so I did a test roughly and it seems to only affect the `make` command. Could you please help me to test `cmake` on Fedora 39 with Python 3.12?
As for the `Makefile`, I've made PR #2185 to fix it.

**Comment by iceman1001** [comment]
merged the fix.

closing
