### ISSUE TITLE
Em410x emulation not working

### ISSUE THREAD

**Issue by Fonteno** [RfidResearchGroup/proxmark3#2197]
Reading and cloning works fine. But emulation is not working for em4100 cards. It says simulating but the reader is not picking anything.

**Comment by piotrva** [comment]
What type of hardware do you have?
There are is lot of hardware on the market that is flawed unfortunately

**Comment by iceman1001** [comment]
I just used the pm3 to simulate EM4100 against a Chameleon Ultra (CU).   The CU didn't have any issue reading the simulated tag. 

You will need to add details on how to replicate your issue.

**Comment by piotrva** [comment]
I am simulating both 125kHz and 13.56 MHz using Proxmark3 RDV without any issue.
However there is Proxmark3 Easy:
1. I received one unit with a missing driver IC (so it was the reason why I was unable to run any simulation)
2. It was replaced by a seller and I got unit with all IC correctly populated. However only simulation of 125 KHz worked - 13.56 MHz was still not functioning.

So in this situation I assume @Fonteno might have similar hardware issue.

**Comment by iceman1001** [comment]
OK,    
Thanks for clarifying.   

Closing since its a hardware issue.

**Comment by piotrva** [comment]
Also a note for future users - try running simulation with `--gap 0` argument - some readers expect a continuous, uninterrupted stream of data.

**Comment by iceman1001** [comment]
Maybe we should improve the help text part. 
So we get two clear examples and a short explanation why.

**Comment by piotrva** [comment]
I was thinking about it as well as making gap = 0 a default option. What do you think?
