### ISSUE TITLE
hf mfp dunp (and possibly other functions) not implemented - no clear message on status of the feature

### ISSUE THREAD

**Issue by piotrva** [RfidResearchGroup/proxmark3#2212]
There are some unimplemented features, like hf mfp dump:
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/src/cmdhfmfp.c#L1692
I would be more than helpful to display in such a case a clear message in the console, like: not (yet) implemented.
For now it took me like 3 hours scratching my head before I opened source code and found it not implemented...

**Comment by iceman1001** [comment]
Yeah,   it should have a more clear message.  
Fixed [#eb673d27b7a51b3611c938e93f518d7f88a7ab94 ](https://github.com/RfidResearchGroup/proxmark3/commit/eb673d27b7a51b3611c938e93f518d7f88a7ab94)
