### ISSUE TITLE
proxmark3.sh crashes

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#224]
**Describe the bug**
the changes introduced to proxmark3.sh script to autodetect com port on windows, crashes on proxspace.  This one is for you @slurdge 

**To Reproduce**
1. run proxspace
2. compile
3. run ' ./proxmark3.sh'

**Expected behavior**
client to autodetect com port and run :)

**Screenshots**
```
pm3 ~$ ./proxmark3.sh
./proxmark3.sh: line 67: syntax error in conditional expression: unexpected token `('
./proxmark3.sh: line 67: syntax error near `MINGW(3'
./proxmark3.sh: line 67: `elif [[ "$HOSTOS" =~ MINGW(32|64)_NT* ]]; then'
pm3 ~$
```

**Comment by doegox** [comment]
Bummer, we tested it under proxspace with @slurdge 
Just by curiosity @iceman1001 you used the latest proxspace ? As you've a few of them...
I'd suggest to change it into simply `elif [[ "$HOSTOS" =~ MINGW ]]; then`
Can you test @iceman1001 ?

**Comment by slurdge** [comment]
Yes it works perfectly on my proxspace setup... It seems that the bash included doesn't support the `(` in the expression.

**Comment by iceman1001** [comment]
no..  
my old ps didn't work.  regex in bash doesn't seem to work.
tested also on ps3.1 ,   where is does work but have the following new issue..
![image](https://user-images.githubusercontent.com/8577004/60754820-04e6b100-9fe7-11e9-9d59-4807c9f19450.png)

Where if you have more than one com port device hooked up it only looks at row 2.

**Comment by slurdge** [comment]
Ah! We feared that may be the case in some setups. It will involve more complicated path to find the first "correct" line.

**Comment by slurdge** [comment]
I have a simple fix:
```
wmic path Win32_SerialPort where "PNPDeviceID like '%VID_9AC4&PID_4B8F%'" get DeviceID, PNPDeviceID
```
Which is actually much simpler... Since we do not need the second filtering with this method.

**Comment by doegox** [comment]
Yes please :)

**Comment by iceman1001** [comment]
I still wonder about that limit of vid/pid.   There is more vid/pid in the wild..

**Comment by slurdge** [comment]
Well the proxmark3.sh is for convenience, so it's alright to cater to the main case IMO. That's why the script also selects the first available proxmark3 even if there's more than one.

**Comment by iceman1001** [comment]
Fair enough limitation.
