### ISSUE TITLE
Tools name change

### ISSUE THREAD

**Issue by Doris1379** [RfidResearchGroup/proxmark3#2276]
I suggest to change one of tools name because that is incorrect and Illusory!
"cryptorf" tools: https://github.com/RfidResearchGroup/proxmark3/tree/master/tools/cryptorf.
I checked source code of this tools, that is about securememory and absolutely not about CryptoRF and CryptoMemory even! 
That is clear in [sma_multi.cpp](https://github.com/RfidResearchGroup/proxmark3/blob/master/tools/cryptorf/sma_multi.cpp) and [sma.cpp](https://github.com/RfidResearchGroup/proxmark3/blob/master/tools/cryptorf/sma.cpp) completely.

securememory algorithm and security method is so different of cryptoMemory so this tools is not useable for cryptoRF.

can you extend code for "Cma_multi" for example ?

**Comment by iceman1001** [comment]
I suspect the name originates from 2010 and this paper. 
http://www.proxmark.org/files/Documents/13.56%20MHz%20-%20CryptoRF/Dismantling_SecureMemory_CryptoMemory_and_CryptoRF-CCS10.pdf


It been around for some year so we have no need to modify it. 

Feel free to contribute and extend the code for "cma_multi".

We welcome pull requests
