### ISSUE TITLE
DESfire DeleteApp authenticates to wrong AID

### ISSUE THREAD

**Issue by craftbyte** [RfidResearchGroup/proxmark3#2336]
**Describe the bug**
When using `hf mfdes deleteapp`, the client authenticates and selects the AID being deleted instead of the PICC AID, which needs to be selected to manage apps (unless they are delegated). I would suggest either adding another CLI argument for the auth AID or having the default be to have the `aid` parameter specify the AID being deleted instead of the AID used for authentication.

**To Reproduce**
1. Make sure that unauthenticated app management is disabled in the PICC config
2. Create a DESfire app with any AID
3. Try to delete the same app

**Expected behavior**
The client authenticates to the PICC AID and then deletes the app.

**Comment by iceman1001** [comment]
Interesting,

We don't have many developers anymore, so you are the best candidate to do it.

Feel free to make pull request with the changes.
