### ISSUE TITLE
Upgrade SWIG to 4.2.0 for Python 3.12 support ?

### ISSUE THREAD

**Issue by philicious** [RfidResearchGroup/proxmark3#2350]
**Describe the bug**
With 
> Python3 library:   Python3 v3.12 found, enabled

you cannot compile and get errors

```
ld: Undefined symbols:
  _PyArg_UnpackTuple, referenced from:
      _SwigPyObject_own in pm3_pywrap.o
  _PyBool_FromLong, referenced from:
...
alot more lines
```
The `pm3_pywrap.c` and `pm3_luawrap.c` files were generated with SWIG 4.0.2 as header comments suggests. SWIG 4.2.0 brings support for Python 3.12, according to https://www.swig.org/Release/RELEASENOTES

Thats also likely the reason for https://github.com/RfidResearchGroup/proxmark3/issues/2305

**Comment by philicious** [comment]
interestingly its building against Python 3.12 using cmake instead of make. so its probably

**Comment by iceman1001** [comment]
I updated the swig to 4.2.1 ...  
Now its down to testing if the experimental lib/client works :)
