### ISSUE TITLE
Compiling error: implicit declaration of function 'ht2_crack'

### ISSUE THREAD

**Issue by gorditodellgado** [RfidResearchGroup/proxmark3#2371]
Have you followed the instructions properly?  ie,  flashed bootrom seperatel
I am doing a fresh install of the proxmark3 software. While folowing the guide I got the the compilation instructions. At the step that says to run "make clean && make -j" I get the following error towards the end. I get the same error when compiling verbose. The troubleshooting guide doesn't seem to make any mention of this.

```
[*] MAKE fpga_compress/all
make[1]: Nothing to be done for 'all'.
[*] MAKE armsrc/all
compiler version:  arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009
[-] CC appmain.c
appmain.c: In function 'PacketReceived':
appmain.c:1144:13: error: implicit declaration of function 'ht2_crack'; did you mean 'ht2_crack2'? [-Werror=implicit-function-declaration]
 1144 |             ht2_crack(payload->NrAr);
      |             ^~~~~~~~~
      |             ht2_crack2
appmain.c:1144:13: error: nested extern declaration of 'ht2_crack' [-Werror=nested-externs]
cc1: all warnings being treated as errors
make[1]: *** [../common_arm/Makefile.common:119: obj/appmain.o] Error 1
make: *** [Makefile:174: armsrc/all] Error 2

```
**Computer info**
 - OS: Kali Linux
 - Kernal: 6.6.15-amd64
 - As per the instructions I just did an update and upgrade

**Comment by iceman1001** [comment]
pull latest,  should be fixed
