### ISSUE TITLE
Hitag2 password write is offset by 1

### ISSUE THREAD

**Issue by ViRb3** [RfidResearchGroup/proxmark3#239]
`lf hitag write 1 00000000`
Expected write to page 1, actually writes to page 2.

Issue is in the `blocknr` incremention behavior in password auth, can be patched but I will try to refactor the whole thing the coming days.

**Comment by doegox** [comment]
ok thanks, waiting for your PR :)

**Comment by iceman1001** [comment]
Nice catch!
