### ISSUE TITLE
PM3 Easy won't connect via USB/serial if it is powered up beforehand

### ISSUE THREAD

**Issue by jgoggan** [RfidResearchGroup/proxmark3#2421]
**Describe the bug**
I have a PM3 Easy with 512k.  It also happens to have a small flash storage of about 140k.  It has two MicroUSB ports -- both of which allow both power and data if either one is connected.

My issue is that if the device is powered up (say, via battery) BEFORE it is connected via USB for data, then it won't connect via data at all.  Under Windows, instead of detecting it as a COM port device, it says "USB device not recognized" and that it "malfunctioned."

Note that the device is up and running.  I can even put it in Standalone mode by holding down the button and everything works normally -- I just have no output via USB/COM.

It appears that when the device is powered up, it attempts a serial/COM connection.  If that fails at boot, then it goes into some other mode where it no longer will communicate on that port.  

Note that the same thing happens if it IS connected to the PC at boot and then a battery is added.  As soon as the battery connection happens on the second MicroUSB port, it disconnects the data connection and Windows gives the error.

I'm hoping there is away around this.  I really want to be able to debug some standalone things.  So I want to be able to have a battery connected while also communicating with the device via USB/COM.

**To Reproduce**
1. Power up a PM3 Easy using a battery.
2. Attempt to connect via USB to a PC or other device.
3. No communication is possible.

or...
1. Connect the PM3 using a USB cable.  It connects fine to the interface/serial/COM.
2. Connect a battery to the second MicroUSB port.
3. The original data/serial/COM connection will stop working.

**Expected behavior**
Connecting a battery -- with no data lines -- to the second MicroUSB port should not disrupt the data connection on the other MicroUSB port.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version
 [ Proxmark3 RFID instrument ]

 [ Client ]
  Iceman/master/v4.18589-75-g2a86a86a0-suspect 2024-07-10 08:59:38 f1dc6862f
  compiled with............. MinGW-w64 13.2.0
  platform.................. Windows (64b) / x86_64
  Readline support.......... present
  QT GUI support............ present
  native BT support......... absent
  Python script support..... present
  Lua SWIG support.......... present
  Python SWIG support....... present

 [ Proxmark3 ]
  firmware.................. PM3 GENERIC
  external flash............ present

 [ ARM ]
  bootrom: Iceman/master/v4.18589-75-g2a86a86a0-suspect 2024-07-10 13:58:06 f1dc6862f
       os: Iceman/master/v4.18589-75-g2a86a86a0-suspect 2024-07-10 13:58:21 f1dc6862f
  compiled with GCC 12.2.0

 [ FPGA ]
  fpga_pm3_lf.ncd image 2s30vq100 2024-02-03 15:12:10
  fpga_pm3_hf.ncd image 2s30vq100 2024-02-03 15:12:20
  fpga_pm3_felica.ncd image 2s30vq100 2024-02-03 15:12:41
  fpga_pm3_hf_15.ncd image 2s30vq100 2024-02-03 15:12:31

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev A
  --= Embedded Processor: ARM7TDMI
  --= Internal SRAM size: 64K bytes
  --= Architecture identifier: AT91SAM7Sxx Series
  --= Embedded flash memory 512K bytes ( 69% used )

 - hw status
[#] Memory
[#]   BigBuf_size............. 39584
[#]   Available memory........ 39584
[#] Tracing
[#]   tracing ................ 1
[#]   traceLen ............... 0
[#] Current FPGA image
[#]   mode.................... fpga_pm3_hf.ncd image 2s30vq100 2024-02-03 15:12:20
[#] Flash memory
[#]   Baudrate................ 24 MHz
[#]   Init.................... ok
[#]   Device ID............... 85 / 14 (unknown)
[#]   Unique ID (be).......... 0x0C3537304E325041
[#] LF Sampling config
[#]   [q] divisor............. 95 ( 125.00 kHz )
[#]   [b] bits per sample..... 8
[#]   [d] decimation.......... 1
[#]   [a] averaging........... yes
[#]   [t] trigger threshold... 0
[#]   [s] samples to skip..... 0
[#]
[#] LF T55XX config
[#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
[#]            mode            |start|write|write|write| read|write|write
[#]                            | gap | gap |  0  |  1  | gap |  2  |  3
[#] ---------------------------+-----+-----+-----+-----+-----+-----+------
[#] fixed bit length (default) |  29 |  17 |  15 |  47 |  15 | n/a | n/a |
[#]     long leading reference |  29 |  17 |  15 |  47 |  15 | n/a | n/a |
[#]               leading zero |  29 |  17 |  15 |  40 |  15 | n/a | n/a |
[#]    1 of 4 coding reference |  29 |  17 |  15 |  31 |  15 |  47 |  63 |
[#]
[#] HF 14a config
[#]   [a] Anticol override.... std    ( follow standard )
[#]   [b] BCC override........ std    ( follow standard )
[#]   [2] CL2 override........ std    ( follow standard )
[#]   [3] CL3 override........ std    ( follow standard )
[#]   [r] RATS override....... std    ( follow standard )
[#] Transfer Speed
[#]   Sending packets to client...
[#]   Time elapsed................... 500ms
[#]   Bytes transferred.............. 270336
[#]   Transfer Speed PM3 -> Client... 540672 bytes/s
[#] Various
[#]   Max stack usage......... 3520 / 8480 bytes
[#]   Debug log level......... 1 ( error )
[#]   ToSendMax............... -1
[#]   ToSend BUFFERSIZE....... 2308
[#]   Slow clock.............. 30970 Hz
[#] Installed StandAlone Mode
[#]   LF HID26 standalone - aka SamyRun (Samy Kamkar)
[#] Flash memory dictionary loaded

 - data tune
This command does not appear to be valid any longer.

Thank you!

**Comment by iceman1001** [comment]
Not really a issue with the repo.    Its something you would need to discuss on the discord server.
