### ISSUE TITLE
Antennas Problem.

### ISSUE THREAD

**Issue by cauabenigri** [RfidResearchGroup/proxmark3#2436]
I've received my proxmark3 easy last week, and when I flashed it, everything was OK. I could read and write LF and HF cards and tags. Today I got some spare time to play with it, and for my surprise, it didn't work at all. At first, I ran LF SEARCH with a card on it, and this was the result: 

[usb] pm3 --> lf search
[=] You can cancel this operation by pressing the pm3 button
[!] (lf_read) command execution time out
[-] Data in Graphbuffer was too small.

Afterwards, I tried HF SEARCH with a card on it, and this was the result:

[usb] pm3 --> hf search
[-] Searching for ISO14443-A tag...[#] BCC0 incorrect, got 0x00, expected 0x02
[#] Aborting
[!] No known/supported 13.56 MHz tags found

So I checked my antennas with HW TUNE:

[usb] pm3 --> hw tune

[=] -------- Reminder ----------------------------
[=] `hw tune` doesn't actively tune your antennas.
[=] It's only informative.
[=] Measuring antenna characteristics...
[\] 10

[=] -------- LF Antenna ----------
[!] LF antenna............ unusable

[=] -------- HF Antenna ----------
[+] 13.56 MHz............. 15.61 V
[+]
[+] Approx. Q factor measurement
[+] Peak voltage.......... 4.5
[+] HF antenna ( ok )

[-] All values are zero. Not showing LF tuning graph

[=] Q factor must be measured without tag on the antenna

Then, I tried recompiling proxmark3 software, but I forgot to change the Makefile.platform, and flashed it all as RDV4, which mine isn't.

Now, I have recompiled everything again with the right Makefile.platform, but got the exactly same results. 

Is my PM3 dead?

 - OS: I've tried it on Debian Bookworm and on Windows 10, both with same result
 - hw version:
 [usb] pm3 --> hw version

 [ Proxmark3 RFID instrument ]

 [ Client ]
  Iceman/master/v4.18589-145-g1393b55fe-suspect 2024-07-28 21:39:45 bb7b3ae3a
  compiled with............. MinGW-w64 13.2.0
  platform.................. Windows (64b) / x86_64
  Readline support.......... present
  QT GUI support............ present
  native BT support......... absent
  Python script support..... present
  Lua SWIG support.......... present
  Python SWIG support....... present

 [ Proxmark3 ]
  firmware.................. PM3 GENERIC

 [ ARM ]
  bootrom: Iceman/master/v4.18589-145-g1393b55fe-suspect 2024-07-28 21:38:58 bb7b3ae3a
       os: Iceman/master/v4.18589-145-g1393b55fe-suspect 2024-07-28 21:39:20 bb7b3ae3a
  compiled with GCC 12.2.0

 [ FPGA ]
  fpga_pm3_lf.ncd image 2s30vq100 2024-02-03 15:12:10
  fpga_pm3_hf.ncd image 2s30vq100 2024-02-03 15:12:20
  fpga_pm3_felica.ncd image 2s30vq100 2024-02-03 15:12:41
  fpga_pm3_hf_15.ncd image 2s30vq100 2024-02-03 15:12:31

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev A
  --= Embedded Processor: ARM7TDMI
  --= Internal SRAM size: 64K bytes
  --= Architecture identifier: AT91SAM7Sxx Series
  --= Embedded flash memory 512K bytes ( 63% used )

 - hw status

[usb] pm3 --> hw status
[#] Memory
[#]   BigBuf_size............. 41436
[#]   Available memory........ 41436
[#] Tracing
[#]   tracing ................ 1
[#]   traceLen ............... 0
[#] Current FPGA image
[#]   mode.................... fpga_pm3_hf.ncd image 2s30vq100 2024-02-03 15:12:20
[#] LF Sampling config
[#]   [q] divisor............. 95 ( 125.00 kHz )
[#]   [b] bits per sample..... 8
[#]   [d] decimation.......... 1
[#]   [a] averaging........... yes
[#]   [t] trigger threshold... 0
[#]   [s] samples to skip..... 0
[#]
[#] LF T55XX config
[#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
[#]            mode            |start|write|write|write| read|write|write
[#]                            | gap | gap |  0  |  1  | gap |  2  |  3
[#] ---------------------------+-----+-----+-----+-----+-----+-----+------
[#] fixed bit length (default) |  31 |  20 |  18 |  50 |  15 | n/a | n/a |
[#]     long leading reference |  31 |  20 |  18 |  50 |  15 | n/a | n/a |
[#]               leading zero |  31 |  20 |  18 |  40 |  15 | n/a | n/a |
[#]    1 of 4 coding reference |  31 |  20 |  18 |  34 |  15 |  50 |  66 |
[#]
[#] HF 14a config
[#]   [a] Anticol override.... std    ( follow standard )
[#]   [b] BCC override........ std    ( follow standard )
[#]   [2] CL2 override........ std    ( follow standard )
[#]   [3] CL3 override........ std    ( follow standard )
[#]   [r] RATS override....... std    ( follow standard )
[#] Transfer Speed
[#]   Sending packets to client...
[#]   Time elapsed................... 500ms
[#]   Bytes transferred.............. 311296
[#]   Transfer Speed PM3 -> Client... 622592 bytes/s
[#] Various
[#]   Max stack usage......... 3520 / 8480 bytes
[#]   Debug log level......... 1 ( error )
[#]   ToSendMax............... -1
[#]   ToSend BUFFERSIZE....... 2308
[#]   Slow clock.............. 32429 Hz
[#] Installed StandAlone Mode
[#]   LF HID26 standalone - aka SamyRun (Samy Kamkar)

PS: I've let it on the same anti-static bag it came from in the period I didn't use it.

**Comment by iceman1001** [comment]
When you compile 
```
make clean;
make -j;
./pm3-flash-all;
./pm3
```
However this doesn't seem to be a firmware issue but user related issue. 

Please use the discord server to ask those questions.
