### ISSUE TITLE
[idea]about  fm11rf08s

### ISSUE THREAD

**Issue by hanyuhang** [RfidResearchGroup/proxmark3#2443]
Now,we can use the scripts of 'fm11rf08s_recovery.py' on linux , When can I use this script on Windows?

**Comment by iceman1001** [comment]
Feel free to contribute for a solution in the Proxspace env.    @doegox   has some fixes out,   which might have solved your problem

**Comment by doegox** [comment]
Actually it works on Windows and Termux as well, since yesterday
