### ISSUE TITLE
i2c  potential hang issue

### ISSUE THREAD

**Issue by RfidResearchGroup** [RfidResearchGroup/proxmark3#29]
From:  https://github.com/iceman1001/proxmark3/issues/247
Sometime it is useful to be able to unhang the i2c.   Normally would be unplug pm3 but that is a too blunt method to use.  

Link to suggested code that deals with a hung i2c.
https://github.com/merlokk/SmartHome/blob/master/ESP8266CO2PM25/ESP8266CO2PM25.ino#L75

@cjbrigato   any takers on this?

**Comment by TomHarkness** [comment]
Friend of mine is looking in to it right now.

**Comment by RfidResearchGroup** [comment]
Great!

**Comment by iceman1001** [comment]
@merlokk   Its better you answer in this thread than over at the iceman fork repo where I posted.

**Comment by merlokk** [comment]
yes)
hi) it may be problem... in some rare cases but....
ill fix it in near future after end fido part.

**Comment by merlokk** [comment]
close? e4cb74fedb165ea5d24e1b567d88dd3d29d63893

**Comment by merlokk** [comment]
by code it should work.
if you have proxmark wo i2c module...
it needs a resistor to ground on any i2c pin to check if it works
