### ISSUE TITLE
SPIFFS Writing to flash is brokken after summer restruct.

### ISSUE THREAD

**Issue by cjbrigato** [RfidResearchGroup/proxmark3#316]
**Describe the bug**
#db# errno -10010
 when attempting ny kkind of writing.
Reading is fine.
will check ...

**Comment by cjbrigato** [comment]
omg... sorry @doegox but there are some absolute mess and nonsense regarding include management here...

This will be hell to debug here.

**Comment by cjbrigato** [comment]
@doegox why on earth did you add all the include s*it even in low Spiffs original implementation files... this is properly undebugable.

**Comment by cjbrigato** [comment]
wontfix

**Comment by doegox** [comment]
it works for me...
do you still have a bug or was it sth else ?

**Comment by iceman1001** [comment]
@cjbrigato  You have still a problem?

**Comment by cjbrigato** [comment]
It's way more complicated than being code side. Spiffs implementation is not strong enough here. I'll make some improvement as I can.
