### ISSUE TITLE
use ~/.proxmark3 or similar

### ISSUE THREAD

**Issue by ZeroChaos-** [RfidResearchGroup/proxmark3#320]
this tools drops a few file in whatever cwd is.  this means that when the tool is installed systemwide it drops files wherever I happen to be when I run proxmark3.  This dirty's up the filesystem and means proxmark3 doesn't have access to the files it expects when I happen to run from a different directory.  Please pick a dot directory like .proxmark3 or .pm3 or even a non-dot directory and use it.

**Comment by iceman1001** [comment]
yup,  Totally agree

**Comment by iceman1001** [comment]
and now we do have a ~/.proxmark3
which is searched for  lualibs / luascripts / dictionaries/  folders.

**Comment by doegox** [comment]
it's a start but we're not yet done with  ~/.proxmark3
see https://github.com/RfidResearchGroup/proxmark3/issues/325#issuecomment-523633394 for details

**Comment by doegox** [comment]
still imho we can close this one as we're tracking the issue in the more global context of make install

**Comment by doegox** [comment]
I think you didn't follow the recent progresses on that one ZeroChaos.
For dicts and luascripts we're automatically searching at specific locations:
* in current dir relative paths, so it works from the non-installed repo
* in ~/.proxmark3 relative paths, for *user provided* dicts and scripts, i.e. stuffs we don't provide ourselves
* in /usr/local/share/proxmark3 (or whatever system path it was used) for stuff deployed via make install

**Comment by doegox** [comment]
and yes, history and log are still todo, as shown in #325

**Comment by doegox** [comment]
yes, so a local file or a file provided in ~/.proxmark3 can shadow an installed one, as typically user-provided stuffs can shadow system-installed ones.

**Comment by doegox** [comment]
and full path is displayed when item is used, so you can see from where it was taken

**Comment by doegox** [comment]
history & logfile moved to ~/.proxmark3 now, time for field testing...

**Comment by iceman1001** [comment]
to see the positive in this ,  we actually get to release how many files there are laying around.

**Comment by iceman1001** [comment]
time to close?

**Comment by doegox** [comment]
yep I'm done on my side.
we're ready to have a make install! let's continue with #325
