### ISSUE TITLE
stop bundling liblua

### ISSUE THREAD

**Issue by ZeroChaos-** [RfidResearchGroup/proxmark3#323]
I'm not certain, but I'm pretty sure that client/liblua is just a bundled version of lua.  This should be already available on every major distro, can this simply be dropped?

**Comment by ZeroChaos-** [comment]
I tested removing the bundled liblua and replacing the static lib with "pkg-config --libs lua" for the linking of proxmark3 and got some errors...  Not sure if I just didn't do it right or if the bundled version of lua is older/newer/modified
```
[-] CC pm3_binlib.c
pm3_binlib.c: In function ‘luaopen_binlib’:
pm3_binlib.c:322:5: error: implicit declaration of function ‘luaL_newlib’; did you mean ‘luaL_openlib’? [-Werror=implicit-function-declaration]
     luaL_newlib(L, binlib);
     ^~~~~~~~~~~
     luaL_openlib
pm3_binlib.c: In function ‘set_bin_library’:
pm3_binlib.c:330:5: error: implicit declaration of function ‘luaL_requiref’; did you mean ‘luaL_unref’? [-Werror=implicit-function-declaration]
     luaL_requiref(L, "bin", luaopen_binlib, 1);
     ^~~~~~~~~~~~~
     luaL_unref
cc1: all warnings being treated as errors
```

**Comment by iceman1001** [comment]
The liblua we use is kind of old...
For us,  we need to keep stuff working on:
mingw, *nix, windows wsl, OSX, android. 

I guess we should add a depency for the tool chain to install lua instead.

**Comment by ZeroChaos-** [comment]
keeping the bundled version is fine, but using the system version when available should be preferred.

**Comment by iceman1001** [comment]
Its different today,   around 2014 when liblua was bundled,   the mingw was annoying.
today,  we have a nice proxspace distro ( @Gator96100  maintains it)  
all *nix, osx,  wsl can apt/emerge it...

**Comment by iceman1001** [comment]
How do you swap between system and bundled?

**Comment by ZeroChaos-** [comment]
if needed, you would basically try to detect if the needed libs are available in system and switch to bundled if not.  this is usually done with a configure script but it's not impossible to do in a Makefile (just uglier)

**Comment by ZeroChaos-** [comment]
I would probably set LUALIBS with `pkg-config --libs lua` and if that's blank switch to the bundled version.

Upon some rough investigation I found this in the bundled version
```
lua.h:#define LUA_VERSION_MAJOR   "5"
lua.h:#define LUA_VERSION_MINOR   "2"
lua.h:#define LUA_VERSION_NUM     502
lua.h:#define LUA_VERSION_RELEASE "2"
```
Which may be newer than the version shipped as "stable" with gentoo (5.1.5).  Having a specified minimum version (and maybe checking it) would make this pretty smooth.

**Comment by iceman1001** [comment]
502 vs 515...  I would say gentoo has a newer version :)

**Comment by ZeroChaos-** [comment]
when I run the bundled compiled version it seems to think it's 5.2, which makes sense with the above Major/Minor

**Comment by ZeroChaos-** [comment]
I mean, I have newer available in gentoo, but 5.1.5 is current "stable" :-)

**Comment by Gator96100** [comment]
If you need to test liblua under ProxSpace you can simply install it with `pacman -S mingw-w64-x86_64-lua mingw-w64-i686-lua`
The latest version in msys2:
```
#define LUA_VERSION_MAJOR	"5"
#define LUA_VERSION_MINOR	"3"
#define LUA_VERSION_NUM		503
#define LUA_VERSION_RELEASE	"4"
```

**Comment by eybisi** [comment]
I'm trying to install luasocket module (on my system) and use it in my lua script but I'm getting this error:
```
pm3 --> script run proxy.lua
[+] Executing Lua script: ~/proxmark3/client/luascripts/proxy.lua, args ''
          
error loading module 'socket.core' from file '/usr/local/lib/lua/5.2/socket/core.so':
	/usr/local/lib/lua/5.2/socket/core.so: undefined symbol: lua_gettop
```
Is this related to using bundled verson ? How can i swap proxmark to use my system instead of bundled?

**Comment by doegox** [comment]
I pushed an attempt in branch https://github.com/RfidResearchGroup/proxmark3/tree/liblua
Makefile only.
Still CMake to do.

**Comment by doegox** [comment]
FTR it fails on OSX, I'll look into it...

**Comment by doegox** [comment]
Fixed on OSX and merged in master. Still no cmake support

**Comment by iceman1001** [comment]
Dark Makefile woodo again.   I swear those makefiles is growing

**Comment by doegox** [comment]
FTR (makefile only, not cmake), we now detect and use system libs in the client for:
* Lua
* Jansson
* Whereami
* Zlib

**Comment by iceman1001** [comment]
Excellent bro!
time to close?

**Comment by doegox** [comment]
yes we can close, I've still on my todo to try to bring the same detection in cmake
