### ISSUE TITLE
latest reveng stuff breaks on proxspace.

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#329]
**Describe the bug**
reveng commits breaks on proxspace

**To Reproduce**
read https://github.com/Gator96100/ProxSpace/issues/16 

**Expected behavior**
a clean compilation

**Desktop (please complete the following information):**
latest proxspace env.

**Additional context**

**Comment by doegox** [comment]
So now that's the mingw64 which is broken while mingw32 is fine! Sigh... I'll have a look this evening.
His error message seems to indicate that even on mingw64, revenge wants 32b setup

**Comment by doegox** [comment]
ok on mingw64 an unsigned long is only 32b, while it's 64b on linux64.
`sizeof(unsigned long)` is the dynamic way, but I've to find static way with compilation vars...
Or, if not possible, reveng helper to modify these vars dynamically...

**Comment by doegox** [comment]
should be fixed by last commit

**Comment by iceman1001** [comment]
And now I will look at reveng 2.0.1...
