### ISSUE TITLE
Travis CI on MacOSX does not checkout the proper branch

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#332]
See e.g. https://travis-ci.org/RfidResearchGroup/proxmark3/jobs/572902998 which should have failed building branch `makefile_restruct` but instread succeeded in building branch `master`

I guess the brew mechanism fetches unconditionally the master.

Now I understand why a previous PR which was apparently ok, broke stuffs once merged...

**Comment by iceman1001** [comment]
@merlokk   our CI expert...

**Comment by merlokk** [comment]
i think problem is here `brew install --HEAD proxmark3`
ill look how to fix

**Comment by iceman1001** [comment]
We would need to compile two versions on Travis CI for OSX.
With and without BT support.
```
brew install --HEAD proxmark3
brew install --with-blueshark proxmark3
```

**Comment by iceman1001** [comment]
I also think it needs to be  like this,  but not sure
```
brew install --HEAD --with-blueshark proxmark3
```

**Comment by doegox** [comment]
It would be far easier if Brew was like ProxSpace: only responsible to provide the environment.
Then we take over as usual with git/make instructions.
So no need for magic tricks to get BT support, to fetch a branch, to let Travis testing the branch and the PR (so the merge of the branch in master), etc.
And when we're starting to work on the make install, we can have make install running on MacOSX too, without relying on Brew and being tied to the brew formula expectations in terms of directories etc.

**Comment by merlokk** [comment]
there was an idea that brew can be used by users to have proxmark installed.
i'd prefer that we have sh file to get and make, but maybe it will be better to fix current system.
ill try and lets see.

**Comment by RfidResearchGroup** [comment]
Thanks @Merlokk  .   I added you and @doegox  as collabs to that repo so you can merge PRs  :)
Also changed some textual things and removed old directives of hid-flasher.

**Comment by merlokk** [comment]
now it looks it works with branches, but not works with PR's
@doegox if you have changes to repo - check please branches testing (i dont want to make strange commits)

**Comment by merlokk** [comment]
ok. it works with branches.

**Comment by merlokk** [comment]
1. make work my script for osx
2.  PR compiling. maybe fully get rid of brew install and move logic to plain make all (needs to think how to debug brew install or just let it work wo this)
3. make compile matrix to check some modes (now for btaddon)

**Comment by iceman1001** [comment]
time to close?

**Comment by doegox** [comment]
ok
