### ISSUE TITLE
make mfkey doesn't build mfkey32v2

### ISSUE THREAD

**Issue by ZeroChaos-** [RfidResearchGroup/proxmark3#374]
the top level makefile has targets for mfkey and nonce2key, but the mfkey one only builds mfkey{32,64} not mfkey32v2

**Comment by iceman1001** [comment]
On my WSL, it compiles
![image](https://user-images.githubusercontent.com/8577004/63970858-7736b780-caa5-11e9-891d-739b4d5e563f.png)

**Comment by ZeroChaos-** [comment]
hmm, that's odd, broken on my end, I'll fix it.  thanks for testing :-)
