### ISSUE TITLE
Error: The file iclass_dump.bin was not found

### ISSUE THREAD

**Issue by merlokk** [RfidResearchGroup/proxmark3#376]
```
[!!] Error: The file iclass_dump.bin was not found!          
[!!] There were errors!!!
```
test
https://travis-ci.org/RfidResearchGroup/proxmark3/jobs/578368587

bug started here
https://github.com/RfidResearchGroup/proxmark3/commit/f3a63767ed22d34afc6e914f9ee6e2351b93a6f1

**Comment by iceman1001** [comment]
try again,  I think @doegox  pushed fixes for it.
we have  resources folder now.   Maybe need to configure appveyor / homebrew / travis for it

**Comment by doegox** [comment]
Yep Travis is happy now

**Comment by merlokk** [comment]
wotks) thanks!
