### ISSUE TITLE
Mess with information about proxmark3 rdv40 

### ISSUE THREAD

**Issue by zhovner** [RfidResearchGroup/proxmark3#38]
Okay, I want to read more about proxmark3 rdv40 and make a decision wether it is worth buying or not.

First I go to rfidresearchgroup.com and what I see. It's an instagram with fashionable colourful PCB's? 
<img width="400" src="https://user-images.githubusercontent.com/774290/47290304-76bccd00-d607-11e8-9eec-0b8cabc3cc92.png" />

Not a single line of text with specification. I see black, blue and red PCB's. Are these different models of device? Where should I click? Or should I click on every model and look for differences? 
Okay, I click on random device that looks similar to proxmark3. And gallery carousel appears with PCB photos. What?!
<img width="400" src="https://user-images.githubusercontent.com/774290/47290528-a15b5580-d608-11e8-984c-8a309a0f7cff.png" />

Okay I finally find a menu on the top and click on `Our Projects --> PROXMARK3 RDV4.0` and get to proxgrind.com. I click on `Shop --> Hardware` to read more information about proxmark3 RDV4.0 

<img width="400" src="https://user-images.githubusercontent.com/774290/47290684-54c44a00-d609-11e8-93eb-809bf045d9fa.png" />

And here is what I see. Where is the proxmark3 RDV4.0?!

<img width="400" src="https://user-images.githubusercontent.com/774290/47290736-889f6f80-d609-11e8-998e-4e23fb38ce59.png" />

 Okay, I found this page http://proxgrind.com/prototyping/proxmark3-rdv4-0-development/ and finally read some useful info. 

Then I got to https://lab401.com/collections/hardware/products/proxmark-3-rdv4 to read  more information. I still don't get what for the SIM card socket was made and what's the difference between external red HF antenna and assembly blue HF antenna even after watching a video. Which is the long and medium range? 
<img width="400" src="https://user-images.githubusercontent.com/774290/47291101-20518d80-d60b-11e8-8b89-5c138212773b.png" />

So I look at  Assembly Instructions link in resources section. Guess what I get? 

<img width="400" src="https://user-images.githubusercontent.com/774290/47291130-33fcf400-d60b-11e8-8b4f-5346ca5367be.png" />

I got this: proxmark elechouse RDV version assembly instruction.
`Installation / Introduction` manual opens elechouse documents too.
<img width="200" src="https://user-images.githubusercontent.com/774290/47291235-9229d700-d60b-11e8-9f4b-541548bdf7d7.png" />

#### Conclusion

Proxmark3 is a highly specialized device for experts who are expecting to see schemes, accurate technical documents and so on. RDV4.0 looks very cool but it lacks a clear documentation and accurate structure of information on all affiliated sites. I want to see all necessary information on single page, without scrolling tons of slides from kickstarter presentation. I want to see a real comparisons with old revisions and real usage examples. Not a PCB photo gallery. 

Here is the example of good product page, take a look for inspiration:

https://hydrabus.com/hydrabus-1-0-hw-detailed/

**Comment by zhovner** [comment]
I will better post this here http://www.proxmark.org/forum/viewtopic.php?pid=32590

**Comment by iceman1001** [comment]
You sound very confused.  Let me try to clear it for you a bit,  reading on the forum thread also helps.

The PM3 rdv4  is a _normal_ Pm3 with some extra features as

- onboad memory
- sim card module
- fpc connector

All neatly packaged in a small formfactor and nice case. 
As mention on those sites the RDV4 is at the moment only sold via two distributors .  Hackerwarehouse and Lab401. 

These extra hardware features enables you to make more interesting functionality with your pm3 rdv4. 
I among others have added basic support for the hardware,  making it more rapid developement for new features.   It offers you a new platform of possibilities to make use of. 

for instance you can now take your rfid enabled credit card and look at the rfid part and hook into the sim card via a extender (sim size -> full size)  the card and see that part of the ISO-7816 comms.  
All in same client.  

The new extra onboard memory will help for all kinds of times you want save / load stuff on the device,  some ppl has already started adding it to standalone modes..   Making the device in standalone mode much more efficent in the field.
