### ISSUE TITLE
Received packet frame with variable part too short? & sc raw

### ISSUE THREAD

**Issue by joelsernamoreno** [RfidResearchGroup/proxmark3#396]
Hello

Whenever I run any command I get the following:
Received packet frame with variable part too short?

I can read cards without problems, but I get that message.

But for example... if I run the hw version command I only get that message, I don't get the command information. This worked yesterday but not today...

I flashed bootrom and fullimage again but I have the same problems.

Another problem:
When I run the command sc raw xxxxx I get the following:

Command successfully executed, xxxxxxxxxxx
Requesting 0x17 bytes response
smart card response failed

**Comment by joelsernamoreno** [comment]
Hello!
I have done the complete installation in Kali Linux and I no longer receive that warning, the command hw version works
<img width="463" alt="proxmark" src="https://user-images.githubusercontent.com/27963913/64850764-49f61780-d616-11e9-8e21-05d2b22311da.PNG">
I'm going to run several tests and I'm writing to tell you that everything is ok

**Comment by iceman1001** [comment]
Just make sure you kill the modem manager on Kali.  I will close this issue,  if you have more troubles feel free to make a new issue.  Also consider contributing a fix for problems you find.

**Comment by joelsernamoreno** [comment]
Modem manager I removed it in Ubuntu 16.04 and Kali Linux

Proxmark3 I only got it to work on Kali Linux
