### ISSUE TITLE
You can find the key with hf mf darkside but not with hf mf autopwn

### ISSUE THREAD

**Issue by libin-ka** [RfidResearchGroup/proxmark3#400]
pm3 --> hf mf darkside
--------------------------------------------------------------------------------

executing Darkside attack. Expected execution time: 25sec on average
press pm3-button on the Proxmark3 device to abort both Proxmark3 and client.
--------------------------------------------------------------------------------

[+] Parity is all zero. Most likely this card sends NACK on every authentication.
[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[+] found 118 candidate keys.

[-] all candidate keys failed. Restarting darkside attack

[+] Parity is all zero. Most likely this card sends NACK on every authentication.
[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[+] found 178 candidate keys.

[-] all candidate keys failed. Restarting darkside attack

[+] Parity is all zero. Most likely this card sends NACK on every authentication.
[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[-] no candidates found, trying again

[+] found 10 candidate keys.

[+] found valid key: eb2faed9503b

pm3 --> hf mf autopwn
[!] no known key was supplied, key recovery might fail
[+] loaded 23 keys from hardcoded default array
[=] running strategy 1

[+] Chunk: 0.5s | found 0/32 keys (23)

[=] running strategy 2

[+] Chunk: 4.3s | found 0/32 keys (23)

--------------------------------------------------------------------------------

executing Darkside attack. Expected execution time: 25sec on average
press pm3-button on the Proxmark3 device to abort both Proxmark3 and client.
--------------------------------------------------------------------------------

[-] Card is not vulnerable to Darkside attack (doesn't send NACK on authentication requests).

[-] No usable key was found!

**Comment by iceman1001** [comment]
yes,  autopwn doesn't loop over and over darkside to solve the special case "parity all zeros"...  However you can use that found key with autopwn.
