### ISSUE TITLE
Proxmark RDV4.01 stuck with LEDs C&A on after flashing

### ISSUE THREAD

**Issue by insatomcat** [RfidResearchGroup/proxmark3#411]
**Describe the bug**
I tried to flash a brand new proxmark rdv4.01 with a freshly compiled image from this repo.
The flasher informed me that I needed to flash the bootrom first.
So I did and and it worked fine.
Then I tried to flash the image again, and althought it started fine, then the proxmark got stuck with leds A & B on, and the usb disconnected.
I tried to reboot it many times

**To Reproduce**

1. Buy a brand new proxmark RDV 4.01
2. Try to flash the image and the bootroom at the same time

```
git clone https://github.com/RfidResearchGroup/proxmark3.git
cd proxmark3
client/flasher /dev/ttyACM0 -b bootrom/obj/bootrom.elf armsrc/obj/fullimage.elf

```

You then receive a message that you need to flash the bootrom first and only.
 

3. Flash the bootrom only:

`client/flasher /dev/ttyACM0 -b bootrom/obj/bootrom.elf`

No error.

4. Then flash the image:

`client/flasher /dev/ttyACM0 armsrc/obj/fullimage.elf
`

**Expected behavior**

The proxmark will disconnect in the middle of the flashing process, and get stuck with leds C and A on.

 - OS: Kali Linux
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version : the proxmark does not work anymore
 - hw status : the proxmark does not work anymore
 - data tune : the proxmark does not work anymore

**Comment by iceman1001** [comment]
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/ModemManager-Must-Be-Discarded.md

**Comment by insatomcat** [comment]
Thanks !
