### ISSUE TITLE
Compiling proxmark3 on fedora 30 fails with skipping incompatible /lib/libreadline.so when searching for -lreadline

### ISSUE THREAD

**Issue by zezadas** [RfidResearchGroup/proxmark3#413]
Compiling proxmark project on fedora 30 will fail with "/usr/bin/ld: skipping incompatible //lib/libreadline.so when searching for -lreadline"

I have fixed this by installing readline-static ( sudo dnf install readline-static ).

can you confirm this and update the compiling guide on fedora?(https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md)

regards

**Comment by doegox** [comment]
any news?

**Comment by iceman1001** [comment]
Closed due to inactivity by OP
