### ISSUE TITLE
Integrate with LGTM Continuous security analysis

### ISSUE THREAD

**Issue by ViRb3** [RfidResearchGroup/proxmark3#414]
I know there's Coverity integration already, but there's another new kid in the block called [LGTM](https://lgtm.com/). UI and setup seems much easier, could provide some interesting insights.

**Comment by iceman1001** [comment]
The problem right now isn't more automated test tools... but people who can fix the already found bugs/errors/warnings...   
We can set it up for the fun of it.  Why not.

**Comment by RfidResearchGroup** [comment]
Up and trying atleast...   It fails on ARM compilation.  Needs to be configured properly.  @merlokk ???
![image](https://user-images.githubusercontent.com/40314039/65633172-c7893280-dfdb-11e9-926c-884db10aa121.png)

**Comment by RfidResearchGroup** [comment]
https://lgtm.com/projects/g/RfidResearchGroup/proxmark3/

**Comment by RfidResearchGroup** [comment]
I guess we need a LGTM yml configuration file
https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

**Comment by RfidResearchGroup** [comment]
Build env is docker based Ubuntu.   
https://lgtm.com/help/lgtm/analysis-faqs#whats-the-default-build-environment-for-cpp-projects

**Comment by merlokk** [comment]
looks like it cant compile arm-none-eabi standard library.

**Comment by iceman1001** [comment]
If @ViRb3  or @merlokk  is not able to configure it properly, I fear that we might just aswell drop this idea.   Whats your comment?

**Comment by doegox** [comment]
if the problem is the arm-none-eabi, it's no different than Coverity which also scans only the client part.
I'm still very interested to see how both compare on the client part.

**Comment by iceman1001** [comment]
No,  Coverity does scan arm.
![image](https://user-images.githubusercontent.com/8577004/66192820-979ff600-e691-11e9-8b47-8488f836edc6.png)

**Comment by doegox** [comment]
> No, Coverity does scan arm.

With zero line of code scanned, this is fine :D 
See on the dashboard "Files in latest snapshot", there are only /client/ files

![image](https://user-images.githubusercontent.com/60773/66193105-3167a300-e692-11e9-9865-97168cc7348e.png)

**Comment by iceman1001** [comment]
Coverity did something this spring,  they changed system or was bought up,  and since then nothing works.  Will look in to it when I get back from work.

**Comment by iceman1001** [comment]
This LGTM did run on the files it found. ie python files.  It didn't like it.

**Comment by iceman1001** [comment]
closed due to lack of activity
