### ISSUE TITLE
[idea] unbundle jansson

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#441]
When it comes to JSON support in Proxmark3 client / fw it comes down to two different implementations. 

The client uses libjansson v2.12 , for device side we use armsrc/frozen.c 

In order to unbundle and make use of system installed version for the client atleast we would need to identify what changes we have done.  

```
/client/jansson

/armsrc/frozen.c
```

**Comment by iceman1001** [comment]
time to close?

**Comment by doegox** [comment]
yes we're using system jansson lib when available
