### ISSUE TITLE
Compile Issue Felica

### ISSUE THREAD

**Issue by db69** [RfidResearchGroup/proxmark3#445]
Latest pull from repo doesn't compile correctly (Proxspace V3.2) : 
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
warning: option --force is deprecated; use --overwrite instead

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [Y/n]
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n]
removing unused sync repositories...

pm3 ~$ git clone https://github.com/RfidResearchGroup/proxmark3.git
Cloning into 'proxmark3'...
remote: Enumerating objects: 102, done.                                                                                 remote: Counting objects: 100% (102/102), done.                                                                         remote: Compressing objects: 100% (82/82), done.                                                                        remote: Total 45111 (delta 48), reused 49 (delta 20), pack-reused 45009                                                 Receiving objects: 100% (45111/45111), 32.57 MiB | 7.55 MiB/s, done.                                                    Resolving deltas: 100% (35127/35127), done.                                                                             Updating files: 100% (1343/1343), done.                                                                                 pm3 ~$ cd proxmark3
pm3 ~/proxmark3$ make clean && make all

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/clean
[!] Platform definitions changed, cleaning bootrom/armsrc/recovery first...
[*] MAKE bootrom/clean
[*] MAKE fpga_compress/clean
[*] MAKE armsrc/clean
[*] MAKE recovery/clean
[*] MAKE mfkey/clean
[*] MAKE nonce2key/clean

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/all
[-] CC proxmark3.c
make[1]: *** wait: No child processes.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: *** wait: No child processes.  Stop.
make: *** [Makefile:98: client/all] Error 2

pm3 ~/proxmark3$ cd
pm3 ~$ git clone https://github.com/RfidResearchGroup/proxmark3.git
Cloning into 'proxmark3'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 45111 (delta 48), reused 49 (delta 20), pack-reused 45009
Receiving objects: 100% (45111/45111), 32.57 MiB | 5.90 MiB/s, done.
Resolving deltas: 100% (35127/35127), done.
Updating files: 100% (1343/1343), done.
pm3 ~$ cd proxmark3
pm3 ~/proxmark3$ make clean && make all

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   BTADDON
Included options:  SMARTCARD FLASH FPC_USART_HOST LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF FPC_USART
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/clean
[!] Platform definitions changed, cleaning bootrom/armsrc/recovery first...
[*] MAKE bootrom/clean
[*] MAKE fpga_compress/clean
[*] MAKE armsrc/clean
[*] MAKE recovery/clean
[*] MAKE mfkey/clean
[*] MAKE nonce2key/clean

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   BTADDON
Included options:  SMARTCARD FLASH FPC_USART_HOST LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF FPC_USART
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/all
[-] CC proxmark3.c
[-] CC uart/uart_posix.c
[-] CC uart/uart_win32.c
[-] CC ui.c
[-] CC ../common/commonutil.c
[-] CC util.c
[-] CC ../common/util_posix.c
[-] CC scandir.c
[-] CC ../common/crc16.c
[-] CC comms.c
[-] CC ../common/crapto1/crapto1.c
[-] CC ../common/crapto1/crypto1.c
[-] CC mifare/mfkey.c
[-] CC tea.c
[-] CC fido/additional_ca.c
[-] CC fido/cose.c
[-] CC fido/cbortools.c
[-] CC fido/fidocore.c
[-] CC crypto/asn1dump.c
[-] CC crypto/libpcrypto.c
[-] CC crypto/asn1utils.c
[-] CC cliparser/argtable3.c
[-] CC cliparser/cliparser.c
[-] CC loclass/cipher.c
[-] CC loclass/cipherutils.c
[-] CC loclass/ikeys.c
[-] CC loclass/elite_crack.c
[-] CC fileutils.c
[-] CC whereami.c
[-] CC mifare/mifarehost.c
[-] CC ../common/parity.c
[-] CC ../common/crc.c
[-] CC ../common/crc64.c
[-] CC ../common/legic_prng.c
[-] CC ../common/iso15693tools.c
[-] CC prng.c
[-] CC graph.c
[-] CC cmddata.c
[-] CC ../common/lfdemod.c
[-] CC emv/crypto_polarssl.c
[-] CC emv/crypto.c
[-] CC emv/emv_pk.c
[-] CC emv/emv_pki.c
[-] CC emv/emv_pki_priv.c
[-] CC emv/test/cryptotest.c
[-] CC emv/apduinfo.c
[-] CC emv/dump.c
[-] CC emv/tlv.c
[-] CC emv/emv_tags.c
[-] CC emv/dol.c
[-] CC emv/emvjson.c
[-] CC emv/emvcore.c
[-] CC emv/test/crypto_test.c
[-] CC emv/test/sda_test.c
[-] CC emv/test/dda_test.c
[-] CC emv/test/cda_test.c
[-] CC emv/cmdemv.c
[-] CC emv/emv_roca.c
[-] CC mifare/mifare4.c
[-] CC mifare/mad.c
[-] CC mifare/ndef.c
[-] CC cmdanalyse.c
[-] CC cmdhf.c
[-] CC cmdhflist.c
[-] CC cmdhf14a.c
[-] CC cmdhf14b.c
[-] CC cmdhf15.c
[-] CC cmdhfepa.c
[-] CC cmdhflegic.c
[-] CC cmdhficlass.c
[-] CC cmdhfmf.c
[-] CC cmdhfmfu.c
[-] CC cmdhfmfp.c
[-] CC cmdhfmfhard.c
[-] CC hardnested/hardnested_bruteforce.c
[-] CC cmdhfmfdes.c
[-] CC cmdhftopaz.c
[-] CC cmdhffido.c
[-] CC cmdhffelica.c
[-] CC cmdhfthinfilm.c
[-] CC cmdhw.c
[-] CC cmdlf.c
[-] CC cmdlfawid.c
[-] CC cmdlfcotag.c
[-] CC cmdlfem4x.c
[-] CC cmdlffdx.c
[-] CC cmdlfguard.c
[-] CC cmdlfgallagher.c
[-] CC cmdlfhid.c
[-] CC cmdlfhitag.c
[-] CC cmdlfio.c
[-] CC cmdlfindala.c
[-] CC cmdlfjablotron.c
[-] CC cmdlfkeri.c
[-] CC cmdlfnexwatch.c
[-] CC cmdlfnedap.c
[-] CC cmdlfnoralsy.c
[-] CC cmdlfpac.c
[-] CC cmdlfparadox.c
[-] CC cmdlfpcf7931.c
[-] CC cmdlfpresco.c
[-] CC cmdlfpyramid.c
[-] CC cmdlfsecurakey.c
[-] CC cmdlft55xx.c
[-] CC cmdlfti.c
[-] CC cmdlfviking.c
[-] CC cmdlfvisa2000.c
[-] CC cmdlfmotorola.c
[-] CC cmdtrace.c
[-] CC cmdflashmem.c
[-] CC cmdflashmemspiffs.c
[-] CC cmdsmartcard.c
[-] CC cmdusart.c
[-] CC cmdwiegand.c
[-] CC cmdparser.c
[-] CC cmdmain.c
[-] CC pm3_binlib.c
[-] CC scripting.c
[-] CC cmdscript.c
[-] CC pm3_bitlib.c
[-] CC cmdcrc.c
[-] CC ../common/bucketsort.c
[-] CC flash.c
[-] CC wiegand_formats.c
[-] CC wiegand_formatutils.c
[-] UIC ui/ui_overlays.h
[-] CXX proxgui.cpp
[-] CXX proxguiqt.cpp
[-] MOC proxguiqt.moc.cpp
[-] CXX proxguiqt.moc.cpp
[-] CC(NOSIMD) hardnested/hardnested_bf_core.c
[-] CC(NOSIMD) hardnested/hardnested_bitarray_core.c
[-] CC(MMX) hardnested/hardnested_bf_core.c
[-] CC(MMX) hardnested/hardnested_bitarray_core.c
[-] CC(SSE2) hardnested/hardnested_bf_core.c
[-] CC(SSE2) hardnested/hardnested_bitarray_core.c
[-] CC(AVX) hardnested/hardnested_bf_core.c
[-] CC(AVX) hardnested/hardnested_bitarray_core.c
[-] CC(AVX2) hardnested/hardnested_bf_core.c
[-] CC(AVX2) hardnested/hardnested_bitarray_core.c
[-] CC(AVX512) hardnested/hardnested_bf_core.c
[-] CC(AVX512) hardnested/hardnested_bitarray_core.c
[*] MAKE liblua for mingw
[-] CC lapi.c
[-] CC lcode.c
[-] CC lctype.c
[-] CC ldebug.c
[-] CC ldo.c
[-] CC ldump.c
[-] CC lfunc.c
[-] CC lgc.c
[-] CC llex.c
[-] CC lmem.c
[-] CC lobject.c
[-] CC lopcodes.c
[-] CC lparser.c
[-] CC lstate.c
[-] CC lstring.c
[-] CC ltable.c
[-] CC ltm.c
[-] CC lundump.c
[-] CC lvm.c
[-] CC lzio.c
[-] CC lauxlib.c
[-] CC lbaselib.c
[-] CC lbitlib.c
[-] CC lcorolib.c
[-] CC ldblib.c
[-] CC liolib.c
[-] CC lmathlib.c
[-] CC loslib.c
[-] CC lstrlib.c
[-] CC ltablib.c
[-] CC loadlib.c
[-] CC linit.c
[=] AR liblua.a
[*] MAKE jansson
[-] CC dump.c
[-] CC error.c
[-] CC hashtable.c
[-] CC hashtable_seed.c
[-] CC load.c
[-] CC memory.c
[-] CC pack_unpack.c
[-] CC strbuffer.c
[-] CC strconv.c
[-] CC utf.c
[-] CC path.c
[-] CC value.c
[=] AR libjansson.a
[*] MAKE tinycbor
[-] CC cborencoder.c
[-] CC cborencoder_close_container_checked.c
[-] CC cborerrorstrings.c
[-] CC cborparser.c
[-] CC cborparser_dup_string.c
[-] CC cborpretty.c
[-] CC cbortojson.c
[-] CC cborvalidation.c
[=] AR tinycbor.a
[*] MAKE reveng
[-] CC bmpbit.c
[-] CC cli.c
[-] CC getopt.c
[-] CC model.c
[-] CC poly.c
[-] CC preset.c
[-] CC reveng.c
[-] CC bmpbit.c
[=] TEST bmptst
[=] AR libreveng.a
[*] MAKE mbedtls
[-] CC aes.c
[-] CC asn1parse.c
[-] CC asn1write.c
[-] CC base64.c
[-] CC bignum.c
[-] CC ctr_drbg.c
[-] CC entropy_poll.c
[-] CC entropy.c
[-] CC error.c
[-] CC timing.c
[-] CC ecp.c
[-] CC ecp_curves.c
[-] CC certs.c
[-] CC camellia.c
[-] CC blowfish.c
[-] CC cipher_wrap.c
[-] CC cipher.c
[-] CC cmac.c
[-] CC des.c
[-] CC ecdsa.c
[-] CC md.c
[-] CC md_wrap.c
[-] CC md5.c
[-] CC oid.c
[-] CC pem.c
[-] CC arc4.c
[-] CC pk.c
[-] CC pk_wrap.c
[-] CC pkwrite.c
[-] CC pkcs5.c
[-] CC pkcs12.c
[-] CC pkparse.c
[-] CC platform.c
[-] CC platform_util.c
[-] CC rsa.c
[-] CC rsa_internal.c
[-] CC sha1.c
[-] CC sha256.c
[-] CC sha512.c
[-] CC threading.c
[-] CC x509.c
[-] CC x509_crl.c
[-] CC x509_crt.c
[=] AR libmbedtls.a
[*] MAKE zlib
[-] CC deflate.c
[-] CC adler32.c
[-] CC trees.c
[-] CC zutil.c
[-] CC inflate.c
[-] CC inffast.c
[-] CC inftrees.c
[=] AR libz.a
[*] MAKE amiibo
[-] CC amiibo.c
[-] CC drbg.c
[-] CC keygen.c
[=] AR libamiibo.a
[=] GEN lualibs/pm3_cmd.lua
[=] GEN lualibs/mfc_default_keys.lua
[=] LD proxmark3
[*] MAKE bootrom/all
[=] GEN version.c
[-] CC version.c
[-] CC ram-reset.s
[-] CC flash-reset.s
[-] CC ../common_arm/usb_cdc.c
[-] CC ../common_arm/clocks.c
[-] CC bootrom.c
[=] LD obj/bootrom.elf
[=] GEN obj/bootrom.s19
[*] MAKE fpga_compress/all
[*] MAKE zlib
[-] CC deflate.c
[-] CC adler32.c
[-] CC trees.c
[-] CC zutil.c
[-] CC inflate.c
[-] CC inffast.c
[-] CC inftrees.c
[=] AR libz.a
[-] CC fpga_compress.c
[=] LD fpga_compress
[*] MAKE armsrc/all
[-] GEN fpga_version_info.c
[-] CC fpga_version_info.c
[-] GEN obj/fpga_all.bit.z
[-] GEN obj/fpga_all.o
[-] CC start.c
[-] CC iso15693.c
[-] CC ../common/iso15693tools.c
[-] CC thinfilm.c
[-] CC lfops.c
[-] CC lfsampling.c
[-] CC pcf7931.c
[-] CC ../common/lfdemod.c
[-] CC ../common/zlib/inflate.c
[-] CC ../common/zlib/inffast.c
[-] CC ../common/zlib/inftrees.c
[-] CC ../common/zlib/adler32.c
[-] CC ../common/zlib/zutil.c
[-] CC legicrf.c
[-] CC legicrfsim.c
[-] CC ../common/legic_prng.c
[-] CC flashmem.c
[-] CC i2c.c
[-] CC usart.c
[-] CC hitag2_crypto.c
[-] CC hitag2.c
[-] CC hitagS.c
[-] CC spiffs.c
[-] CC spiffs_cache.c
[-] CC spiffs_check.c
[-] CC spiffs_gc.c
[-] CC spiffs_nucleus.c
[-] CC spiffs_hydrogen.c
[-] CC appmain.c
[-] CC printf.c
[-] CC dbprint.c
[-] CC ../common/commonutil.c
[-] CC util.c
[-] CC string.c
[-] CC BigBuf.c
[-] CC ticks.c
[-] CC ../common_arm/clocks.c
[-] CC hfsnoop.c
[-] CC fpgaloader.c
[-] CC iso14443a.c
[-] CC mifareutil.c
[-] CC mifarecmd.c
[-] CC epa.c
[-] CC mifaresim.c
[-] CC iso14443b.c
[-] CC ../common/crapto1/crypto1.c
[-] CC des.c
[-] CC desfire_key.c
[-] CC mifaredesfire.c
[-] CC ../common/mbedtls/aes.c
[-] CC ../common/mbedtls/platform_util.c
[-] CC iclass.c
[-] CC optimized_cipher.c
[-] CC ../common/crc.c
[-] CC ../common/crc16.c
[-] CC ../common/crc32.c
[-] CC felica.c
felica.c: In function 'felica_send_request_service':
felica.c:777:43: error: division 'sizeof (uint8_t * {aka unsigned char *}) / sizeof (uint8_t {aka unsigned char})' does not compute the number of array elements [-Werror=sizeof-pointer-div]
     uint8_t len = sizeof(request_service) / sizeof((request_service)[0]);
                                           ^
felica.c:776:43: note: first 'sizeof' operand was declared here
 void felica_send_request_service(uint8_t *request_service) {
                                  ~~~~~~~~~^~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
make[1]: *** [../common_arm/Makefile.common:63: obj/felica.o] Error 1
make: *** [Makefile:95: armsrc/all] Error 2
pm3 ~/proxmark3$

**Comment by doegox** [comment]
It has already been spotted, thanks.
Should be solved soon... Poking @7homasSutter 
https://github.com/RfidResearchGroup/proxmark3/commit/a5e94c5a1db88a5202eeecfb0f6e3dd77d2050fd#r35550616

**Comment by doegox** [comment]
I pushed a temporary fix to un-break the repo

**Comment by db69** [comment]
Thanks



Sent from Samsung tablet.


-------- Original message --------
