### ISSUE TITLE
Broken "lf em 410x_sim"

### ISSUE THREAD

**Issue by temskiy** [RfidResearchGroup/proxmark3#448]
The latest commit with worked function "lf em 410x_sim"  is 945fb82b48054d4096f82fda892abd21422a0025

**To Reproduce**
1. Build client & firmware at any commit after 945fb82b48054d4096f82fda892abd21422a0025
2. Flash firmwatre to PM
3. Start in client emulating em4100 tag with any ID

**Comment by iceman1001** [comment]
...did you flash bootrom and fullimage?

**Comment by temskiy** [comment]
Yes. After compiling i run "pm3-flash-all"

**Comment by iceman1001** [comment]
And your output from 
```
hw status
hw tune
```

**Comment by temskiy** [comment]
In attached file
[log.txt](https://github.com/RfidResearchGroup/proxmark3/files/3762176/log.txt)

**Comment by iceman1001** [comment]
ok,  @mwalker33  confirmed the bug.  Its related to a coverity fix I tried.  He will have a look at it soon.

**Comment by mwalker33** [comment]
This should now be fixed.  Can you update with the latest and confirm it's working for you.

**Comment by temskiy** [comment]
Works fine
Thanks

**Comment by iceman1001** [comment]
Thanks @temskiy  for reporting it in  and  thanks @mwalker33  for the fix!

**Comment by temskiy** [comment]
It`s broken again.
