### ISSUE TITLE
Initial installation on Runme

### ISSUE THREAD

**Issue by ShahzebKhurshid** [RfidResearchGroup/proxmark3#454]
I followed the instructions and ran the Runme.bat
But It ended at the following commands:
warning! terminate MSYS2 without returning to the shell and check  for updates again
warning! for example close your terminal window instead  of calling  exit

![Capture](https://user-images.githubusercontent.com/53387451/67624104-aa25cf00-f7fa-11e9-937c-4b3036b6cd2f.JPG)

**Comment by iceman1001** [comment]
Sadly that is not a Proxmark issue,   but a Proxspace issue,  Head over to @Gator96100 proxspace repo [here](https://github.com/Gator96100/ProxSpace/)  and ask....
