### ISSUE TITLE
Running client program, high CPU utilization

### ISSUE THREAD

**Issue by ewangsoft** [RfidResearchGroup/proxmark3#458]
**Describe the bug**
Running client program, high CPU utilization

**To Reproduce**
make PLATFORM=PM3OTHER with  ProxSpace
Enter “proxmark3 COM3” to run the client program

Task manager display：
Windows command handler(2)：30%
    Console window main process：18%
    proxmark3.exe 12%

**Desktop (please complete the following information):**
 - OS: Windows 10 professional

  [ Proxmark3 RFID instrument ]
 [ CLIENT ]
  client: RRG/Iceman
  compiled with MinGW-w64 9.2.0 OS:Windows (64b) ARCH:x86_64
 [ PROXMARK3 ]

 [ ARM ]
  bootrom: RRG/Iceman/master/c6f4bf2a 2019-10-30 12:28:12
       os: RRG/Iceman/master/c6f4bf2a 2019-10-30 12:28:41
  compiled with GCC 8.3.1 20190703 (release) [gcc-8-branch revision 273027]

 [ FPGA ]
  LF image built for 2s30vq100 on 2019-07-31 at 15:57:16
  HF image built for 2s30vq100 on 2018-09-03 at 21:40:23

 [ Hardware ]
  --= uC: AT91SAM7S256 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 256K bytes, Used: 240866 bytes (92%) Free: 21278 bytes ( 8%)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

[usb] pm3 --> hw status
#db# Memory
#db#   BIGBUF_SIZE.............40000
#db#   Available memory........39168
#db# Tracing
#db#   tracing ................0
#db#   traceLen ...............101
#db# Currently loaded FPGA image
#db#   mode.................... HF image built for 2s30vq100 on 2018-09-03 at 21:40:23
#db# LF Sampling config
#db#   [q] divisor.............95 ( 125.00 kHz )
#db#   [b] bps.................8
#db#   [d] decimation..........1
#db#   [a] averaging...........Yes
#db#   [t] trigger threshold...0
#db#   [s] samples to skip.....0
#db# LF T55XX config
#db#            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
#db#            mode            |start|write|write|write| read|write|write
#db#                            | gap | gap |  0  |  1  | gap |  2  |  3
#db# ---------------------------+-----+-----+-----+-----+-----+-----+------
#db# fixed bit length (default) |  29 |  17 |  15 |  47 |  15 | N/A | N/A |
#db#     long leading reference |  31 |  20 |  18 |  50 |  15 | N/A | N/A |
#db#               leading zero |  31 |  20 |  18 |  40 |  15 | N/A | N/A |
#db#    1 of 4 coding reference |  29 |  17 |  15 |  31 |  15 |  47 |  63 |
#db#
#db# Transfer Speed
#db#   Sending packets to client...
#db#   Time elapsed............500ms
#db#   Bytes transferred.......247808
#db#   Transfer Speed PM3 -> Client = 495616 bytes/s
#db# Various
#db#   DBGLEVEL................1
#db#   ToSendMax...............-1
#db#   ToSendBit...............0
#db#   ToSend BUFFERSIZE.......2308
#db#   Slow clock..............28530 Hz
#db# Installed StandAlone Mode
#db#   LF HID26 standalone - aka SamyRun (Samy Kamkar)

[usb] pm3 --> data tune

[=] Measuring antenna characteristics, please wait...

[=] You can cancel this operation by pressing the pm3 button
..

[+] LF antenna: 27.33 V - 125.00 kHz
[+] LF antenna: 31.87 V - 134.83 kHz
[+] LF optimal: 36.54 V - 130.43 kHz
[+] LF antenna is OK

[+] HF antenna: 25.34 V - 13.56 MHz
[+] HF antenna is OK

[+] Displaying LF tuning graph. Divisor 88 is 134.83 kHz, 95 is 125.00 kHz.

**Comment by iceman1001** [comment]
Thats not so bad,  before recent changes we had 100% cpu utilization
