### ISSUE TITLE
Attribution for amiibo integration features

### ISSUE THREAD

**Issue by jamchamb** [RfidResearchGroup/proxmark3#460]
Hello, I see this repo has integrated features from my amiibo/NTAG215 simulator proxmark3 fork (https://github.com/nccgroup/proxmark3-amiimicyou), including a few Lua scripts and the amiitool Lua integration library. Would it be possible to add a simple attribution comment for these, e.g. "Originally from https://github.com/nccgroup/proxmark3-amiimicyou by @jamchamb"?

Files include:
* client/luascripts/amiibo.lua
* client/lualibs/amiibolib.lua
* client/lualibs/emulator.lua
* client/libluamiibo.so

I see there's a copy of amiitool in the repo, I don't mind if you pull in the Lua integration code for building the libluamiibo.so (https://github.com/jamchamb/amiitool/tree/lua-lib), as long as there's a attribution comment on the amiibo_lua.c/.h files.

**Comment by iceman1001** [comment]
For sure.   

I decided not to use the lua script route ,  we will be using the amitool source code from @socram8888 directly in the client.

https://github.com/RfidResearchGroup/proxmark3/commit/aabf3ecafad4ebcb37ce640ab6dad126b6e26cfb
