### ISSUE TITLE
iCLASS Simulation Inconsistent

### ISSUE THREAD

**Issue by digitalentropy** [RfidResearchGroup/proxmark3#469]
**Describe the bug**
App issuer area block does not always simulate correctly from dumps.
**To Reproduce**
1. Create a dump with a unique App Issuer Block
2. Try to sim.
3. Cry.

**Expected behavior**
All blocks should be emulated correctly from dump file.

**Comment by iceman1001** [comment]
Ok,  I see the problem.

**Comment by iceman1001** [comment]
@digitalentropy  I pushed a fix.

**Comment by ikarus23** [comment]
A little bit off topic and just out of curiosity: are @pwpiwi fixes for iCLASS also part of this repository? (e.g. https://github.com/Proxmark/proxmark3/commit/ece38ef311b28eefb1d716937139aad9ee00985c)

**Comment by iceman1001** [comment]
Nop,

**Comment by iceman1001** [comment]
@digitalentropy  Closing since no feedback from OP.
