### ISSUE TITLE
Pin Meassurments

### ISSUE THREAD

**Issue by duckie37** [RfidResearchGroup/proxmark3#472]
So the first thing I did when I got my Proxsmark3 v4 was brick it,  At least I am sure I did. All the lights are solid and USB won't puck it up. I am ordering a jtag device but need to get a right angle breakaway pin for this. I noticed these are tiny compared to previous versions. Any ideas on what kind of right-angle pins will fit on this comfortably?

Thanks

**Comment by merlokk** [comment]
I'd prefer pogo pins. As I remembered- it size like 50 or 75

**Comment by iceman1001** [comment]
or get a adaptor like this  https://github.com/RfidResearchGroup/proxmark3/wiki/Tools

but before that,  have you tried the button trick?   Ie, are you sure you bricked your device?
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Troubleshooting.md

**Comment by duckie37** [comment]
Thank you for the link. Yes, I am sure it's bricked. I had modem management on when I was updating the flash and since then it's solid lights across even when I boot it holding button down.

**Comment by iceman1001** [comment]
That sucks.  Luckily your way to recovery is JTAG.  You can read the docs here and look in the folder 
`https://github.com/RfidResearchGroup/proxmark3/tree/master/tools/jtag_openocd`
