### ISSUE TITLE
arm-none-eabi-gcc exists but not executing

### ISSUE THREAD

**Issue by royallyovershoot** [RfidResearchGroup/proxmark3#479]
**Describe the bug**
Under the make clean && make all steps I get the error "arm-none-eabi-gcc" is not recognized. So I manually added it to env. path. and I can see the arm-none-eabi-gcc.exe in the path and still I get the error. 
Here is where it gets witchy, I navigate using file explorer to "~\Proxmark\ProxSpace-master\gcc-arm-none-eabi\bin" and I can clearly see "arm-none-eabi-gcc.exe" but if I search for it on the search bar it doesn't show up!!! It's literally there and windows for some reason can't see it.

![Capture](https://user-images.githubusercontent.com/20677280/69398508-826e3d80-0cb8-11ea-9e4c-e47b8573b6c2.PNG)

![Capture](https://user-images.githubusercontent.com/20677280/69398546-b184af00-0cb8-11ea-9a61-66b095084ff4.PNG)

So I think this is where windows is acting funny... so, help? please? yes, I restarted.

**Comment by iceman1001** [comment]
Sounds more like you messed up your Proxspace enviroment. Did you follow the instructions over at @Gator96100 repo?  
I am closing this since its not a issue for this repo.
