### ISSUE TITLE
Annoying error messages running the client on Linux

### ISSUE THREAD

**Issue by evazzoler** [RfidResearchGroup/proxmark3#482]
![Screenshot](https://user-images.githubusercontent.com/9479876/69659478-8dd9b400-107e-11ea-81f2-8c34abac043d.png)

Some GTK errors appearing when I start the client. I searched the internet and found little documentation. It seems the code try to load a not existing theme (why?).
The plot command works apparently good.

**Comment by doegox** [comment]
Nothing we can do about it, it's due to missing stuff in your desktop theme.
See e.g. #386

**Comment by evazzoler** [comment]
And why the executable are looking for GUI stuff when it is a CLI?
Just notice that the executable coult search for the wrong stuff...
Stuff, in example, tipically not existing on a Ubuntu 18.04 desktop environment.

**Comment by doegox** [comment]
the CLI has GUI components, e.g. when running "data plot".
> Stuff, in example, tipically not existing on a Ubuntu 18.04 desktop environment.
can you elaborate?

**Comment by evazzoler** [comment]
It seems the code try to force a specific theme instead "current theme".
It happens on a clean install where other GUI applications are working well.

**Comment by evazzoler** [comment]
Data plot is working perfectly despite these errors.

**Comment by doegox** [comment]
what is your desktop environment?

**Comment by evazzoler** [comment]
My desktop environment is Gnome on Ubuntu 18.04.3. The theme is Ambiance.
The same issue happens with other themes.
The issue don't happens if I launch proxmark client as root (sudo).

Maybe the client search the theme in the location where root user theme is located, not the user one, and has no rights there.

I found some similar issues on google pointing to github issue tracker of other projects and developer closed them writing "fixed for dark theme" or "fixed". This means it was a code issue and not user environment issue / user side issue...
