### ISSUE TITLE
get rid of polarssl/des.c

### ISSUE THREAD

**Issue by merlokk** [RfidResearchGroup/proxmark3#49]
Hi

Here are strange initializers. mbedtls dont have this field.
i have no idea why it need to be.

`des3_context ctx = { DES_DECRYPT ,{ 0 } };`
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/loclass/elite_crack.c#L175
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/cmdhficlass.c#L769

can we test this parts of code if i get rid of polarssl?

P.S. i will put changes in next PR after #48

**Comment by iceman1001** [comment]
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/loclass/main.c#L67

**Comment by merlokk** [comment]
great!  thanks)
then....  ill merge fido and move it to mbedtls
