### ISSUE TITLE
[idea] textual - red colour for destruction operations

### ISSUE THREAD

**Issue by mashrum** [RfidResearchGroup/proxmark3#494]
Because of using colours for console
helpful to have some red exclamation mark for tag write operations [!] which can destruct data on card.

**Comment by iceman1001** [comment]
In the current implementation,  failed or errors gets  the red [!]. 
It will be very confusing to see red on info/success for a write command.

To consider what you wanna protect or make even more clear for end user;
I would say that if a user don't understand that writing to tag will overwrite existing memory on tag, then maybe that user should reconsider using this tool.
