### ISSUE TITLE
LF StandAlone mode is broken. Field active but no tag read

### ISSUE THREAD

**Issue by TomHarkness** [RfidResearchGroup/proxmark3#5]
This one should be easy to fix but I'm unsure where to look sorry!

**Comment by RfidResearchGroup** [comment]
too little information to be useful for debugging purposes.
...which standalone mode?

**Comment by TomHarkness** [comment]
SamyRun - default. No others tested so far, I'll get back with more info asap.

**Comment by TomHarkness** [comment]
Tested all LF StandAlone. None work, field active as I have LED test cards and can see easily. But no data read or played back.

**Comment by RfidResearchGroup** [comment]
hm.. lf sim seems to be off ..   Lets see if there was a update to fpga images..

**Comment by RfidResearchGroup** [comment]
nop,    right now its FSK based simulation that is bad like these
lf hid sim
lf pyramid sim

**Comment by TomHarkness** [comment]
Check:

`https://github.com/iceman1001/proxmark3/issues/239`

**Comment by RfidResearchGroup** [comment]
This one should be fixed now.    My LF samyrun works as expected.  @TomHarkness  Would you mind verify it?

**Comment by TomHarkness** [comment]
Confirmed working.
