### ISSUE TITLE
Valid LTO-CM tag  found

### ISSUE THREAD

**Issue by mashrum** [RfidResearchGroup/proxmark3#500]
the pm3 with NO any card or with any card
reports

```
[ ARM ]
  bootrom: RRG/Iceman/master/a6a48f0e 2019-12-23 18:46:49
       os: RRG/Iceman/master/a6a48f0e 2019-12-23 18:47:00
  compiled with GCC 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
```

[usb] pm3 --> hf search
[=] Checking for known tags...          
[-] Searching for LTO-CM tag...               
[+] Valid LTO-CM tag  found

miscellaneous: double space between words in "-CM tag  found"

**Comment by iceman1001** [comment]
try again.  
- spaces : fixed
- wrong identification of lto : fixed
