### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by D-Jy0329** [RfidResearchGroup/proxmark3#507]
[-] CC fileutils.c
fileutils.c:44:10: fatal error: sndfile.h: No such file or directory
   44 | #include <sndfile.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:436: obj/fileutils.o] Error 1
make: *** [Makefile:98: client/all] Error 2

**Comment by iceman1001** [comment]
New dependcy,  read the install instructions.

ref
http://www.proxmark.org/forum/viewtopic.php?id=7146
http://www.proxmark.org/forum/viewtopic.php?id=7151

https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md
