### ISSUE TITLE
read_lua_mem*.lua "all rights reserved"

### ISSUE THREAD

**Issue by micolous** [RfidResearchGroup/proxmark3#519]
**Describe the bug**
The scripts [read_pwd_mem.lua](https://github.com/RfidResearchGroup/proxmark3/blob/master/client/luascripts/read_pwd_mem.lua) and [read_pwd_mem_spiffs.lua](https://github.com/RfidResearchGroup/proxmark3/blob/master/client/luascripts/read_pwd_mem_spiffs.lua) are marked as _Copyright ... **All rights reserved**._

I believe the _all rights reserved_ statement (with no other license statement) conflicts with the GPLv2+ license used by the rest of the project.

I haven't checked other Lua scripts for similar issues.

This issue impacts the redistribution of the project; see also similar past issue https://github.com/Proxmark/proxmark3/issues/527.

**Expected behavior**
All Lua scripts are in GPLv2+-compatible licenses.

**Desktop (please complete the following information):**
Not applicable, source-level issue present in `git master`

**Comment by iceman1001** [comment]
The adding of individual license text in each source file practice is not something done here.

Instead we follow the [LICENSE.txt](https://github.com/RfidResearchGroup/proxmark3/blob/master/LICENSE.txt)

By adding a file to this repo without a included license,  it falls under the license for the project which is clearly expressed in aformented file.
