### ISSUE TITLE
lf cmdread on hitag got broken

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#524]
Commit f7156e7485e03b22d9f8077caccd0a173328b28f introduced somehow a bug and sending raw command to hitag as done in https://github.com/RfidResearchGroup/proxmark3/issues/124#issuecomment-472800131 returns no signal anymore.

**Comment by aczid** [comment]
Was just about to report the same bug after tracking it down to the same commit. The command `lf cmdread d 50 z 166 o 116 c 000111` and then plotting the result also shows a bunch of noise. `lf search` also does not work. Looks like a nice commit otherwise. :)
