### ISSUE TITLE
Improving LF Signal Demodulation

### ISSUE THREAD

**Issue by Silipwn** [RfidResearchGroup/proxmark3#527]
Hi guys! 
I would like to work on improving the LF signal demodulation, was just wondering what all should I look into before starting to work on the same. I'm currently reading the `common/lfdemod.c`. Any help or things to look at would be helpful. Thanks in advance. :)

**Comment by iceman1001** [comment]
For client side handling of data,  these two files are often involved.
- `common/lfdemod.c`
- `client/cmddata.c`

The lua scripts for testing lf demodulation is found here
- `https://github.com/RfidResearchGroup/proxmark3/blob/master/client/luascripts/test_t55x7.lua`
- `https://github.com/RfidResearchGroup/proxmark3/blob/master/client/luascripts/test_t55x7_ask.lua`
etc

The first script gives a good indication on which demods needs improving.

**Comment by Silipwn** [comment]
Thanks for the update.

**Comment by iceman1001** [comment]
@Silipwn   time to close?

**Comment by Silipwn** [comment]
Sure, I will close.
