### ISSUE TITLE
[Build] /usr/lib64/gcc/arm-none-eabi/9/ld: error: no memory region specified for loadable section `.note.gnu.build-id'

### ISSUE THREAD

**Issue by hsanjuan** [RfidResearchGroup/proxmark3#529]
When building, gcc fails with:

`/usr/lib64/gcc/arm-none-eabi/9/ld: error: no memory region specified for loadable section `.note.gnu.build-id'`. This happens in several places (like the `obj/fullimage.elf` object).

Google suggested I could fix this by adding `-Wl,--build-id=none,...` and that seems to work, but I'm not sure why the error happens in the first place or the consequences of the fix.

**Comment by hsanjuan** [comment]
I must add: latest `master`, on Linux (openSUSE Tumbleweed), with `cross-arm-none-gcc9-9.2.1+r279103`

**Comment by iceman1001** [comment]
No idea,  openSUSE and its arm-non-eabi compiler,   sounds like @doegox might know something

**Comment by doegox** [comment]
ok I verified it in a docker image.
The fix you proposed seems indeed to be the right thing to do.
I also added installation instructions for opnSUSE in https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md
Thank you @hsanjuan !

**Comment by hsanjuan** [comment]
Thanks so much @doegox, I very much appreciate it.
