### ISSUE TITLE
Default Hitag2 Reader password fails

### ISSUE THREAD

**Issue by Danyc0** [RfidResearchGroup/proxmark3#536]
**Describe the bug**
The client help says that the default password is 4D494B52, but this doesn't seem to work. However if you manually specify this as the password, it works.

**To Reproduce**
1. Put tag with password 4D494B52 on pm3
2. Run: lf hitag reader 21
3. Observe that read fails
4. Run: lf hitag reader 21 4D494B52
5. Observe that read succeeds

**Expected behavior**
"lf hitag reader 21" should successfully read a tag with password 4D494B52 by default, without having to specify the password (as in the documentation)

**Screenshots**
![Screenshot from 2020-01-22 16-58-44](https://user-images.githubusercontent.com/2716831/72916053-33389d80-3d39-11ea-9fd6-2a3a9a7884db.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - hw version: 
![Screenshot from 2020-01-22 17-05-20](https://user-images.githubusercontent.com/2716831/72916207-8579be80-3d39-11ea-99b7-319fcba6d7bb.png)

 - hw status: 
![Screenshot from 2020-01-22 17-05-46](https://user-images.githubusercontent.com/2716831/72916219-8c083600-3d39-11ea-9f24-27ef6301e06b.png)

 - data tune: 
![Screenshot from 2020-01-22 17-06-03](https://user-images.githubusercontent.com/2716831/72916226-90345380-3d39-11ea-8c94-f722dec00220.png)

**Comment by iceman1001** [comment]
This is all a multi step refactoring. 
So it will take some time before it all is functional.

**Comment by Danyc0** [comment]
If you need a hand with anything please let me know. I tried to find where in the code the default is set, but my knowledge of the client code base let me down.
