### ISSUE TITLE
Unable to compile from source: undefined reference to `lf_manchester_send_bit'

### ISSUE THREAD

**Issue by pacmandu** [RfidResearchGroup/proxmark3#542]
**Describe the bug**
Cannot compile even with fresh repo clone

**To Reproduce**
1. apt-get install gcc-arm-none-eabi git build-essential libreadline5 libreadline-dev gcc-arm-none-eabi libusb-0.1-4 libusb-dev libqt4-dev ncurses-dev perl pkg-config libpcsclite-dev pcscd
2. git clone https://github.com/RfidResearchGroup/proxmark3.git
3. cd proxmark3
4. make clean && make all

Output:
root@kali:/opt/proxmark3# make clean && make all

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF HFPLOT
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/clean
[!] Platform definitions changed, cleaning bootrom/armsrc/recovery first...
[*] MAKE bootrom/clean
[*] MAKE fpga_compress/clean
[*] MAKE armsrc/clean
[*] MAKE recovery/clean
[*] MAKE mfkey/clean
[*] MAKE nonce2key/clean

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF HFPLOT
Standalone mode:   LF_SAMYRUN
===================================================================
[*] MAKE client/all
[-] CC proxmark3.c
[-] CC uart/uart_posix.c
[-] CC uart/uart_win32.c
[-] CC ui.c
[-] CC ../common/commonutil.c
[-] CC util.c
[-] CC ../common/util_posix.c
[-] CC scandir.c
[-] CC ../common/crc16.c
[-] CC comms.c
[-] CC ../common/crapto1/crapto1.c
[-] CC ../common/crapto1/crypto1.c
[-] CC mifare/mifaredefault.c
[-] CC mifare/mfkey.c
[-] CC tea.c
[-] CC fido/additional_ca.c
[-] CC fido/cose.c
[-] CC fido/cbortools.c
[-] CC fido/fidocore.c
[-] CC crypto/asn1dump.c
[-] CC crypto/libpcrypto.c
[-] CC crypto/asn1utils.c
[-] CC cliparser/argtable3.c
[-] CC cliparser/cliparser.c
[-] CC loclass/cipher.c
[-] CC loclass/cipherutils.c
[-] CC loclass/ikeys.c
[-] CC loclass/elite_crack.c
[-] CC fileutils.c
[-] CC whereami.c
[-] CC mifare/mifarehost.c
[-] CC ../common/parity.c
[-] CC ../common/crc.c
[-] CC ../common/crc64.c
[-] CC ../common/legic_prng.c
[-] CC ../common/iso15693tools.c
[-] CC prng.c
[-] CC ../common/generator.c
[-] CC graph.c
[-] CC cmddata.c
[-] CC ../common/lfdemod.c
[-] CC emv/crypto_polarssl.c
[-] CC emv/crypto.c
[-] CC emv/emv_pk.c
[-] CC emv/emv_pki.c
[-] CC emv/emv_pki_priv.c
[-] CC emv/test/cryptotest.c
[-] CC emv/apduinfo.c
[-] CC emv/dump.c
[-] CC emv/tlv.c
[-] CC emv/emv_tags.c
[-] CC emv/dol.c
[-] CC emv/emvjson.c
[-] CC emv/emvcore.c
[-] CC emv/test/crypto_test.c
[-] CC emv/test/sda_test.c
[-] CC emv/test/dda_test.c
[-] CC emv/test/cda_test.c
[-] CC emv/cmdemv.c
[-] CC emv/emv_roca.c
[-] CC mifare/mifare4.c
[-] CC mifare/mad.c
[-] CC mifare/ndef.c
[-] CC cmdanalyse.c
[-] CC cmdhf.c
[-] CC cmdhflist.c
[-] CC aidsearch.c
[-] CC cmdhf14a.c
[-] CC cmdhf14b.c
[-] CC cmdhf15.c
[-] CC cmdhfepa.c
[-] CC cmdhflegic.c
[-] CC cmdhficlass.c
[-] CC cmdhfmf.c
[-] CC cmdhfmfu.c
[-] CC cmdhfmfp.c
[-] CC cmdhfmfhard.c
[-] CC hardnested/hardnested_bruteforce.c
[-] CC cmdhfmfdes.c
[-] CC cmdhftopaz.c
[-] CC cmdhffido.c
[-] CC cmdhffelica.c
[-] CC cmdhfthinfilm.c
[-] CC cmdhflto.c
[-] CC cmdhw.c
[-] CC cmdlf.c
[-] CC cmdlfawid.c
[-] CC cmdlfcotag.c
[-] CC cmdlfem4x.c
[-] CC cmdlffdx.c
[-] CC cmdlfguard.c
[-] CC cmdlfgallagher.c
[-] CC cmdlfhid.c
[-] CC cmdlfhitag.c
[-] CC cmdlfio.c
[-] CC cmdlfindala.c
[-] CC cmdlfjablotron.c
[-] CC cmdlfkeri.c
[-] CC cmdlfnexwatch.c
[-] CC cmdlfnedap.c
[-] CC cmdlfnoralsy.c
[-] CC cmdlfpac.c
[-] CC cmdlfparadox.c
[-] CC cmdlfpcf7931.c
[-] CC cmdlfpresco.c
[-] CC cmdlfpyramid.c
[-] CC cmdlfsecurakey.c
[-] CC cmdlft55xx.c
[-] CC cmdlfti.c
[-] CC cmdlfviking.c
[-] CC cmdlfvisa2000.c
[-] CC cmdlfmotorola.c
[-] CC cmdtrace.c
[-] CC cmdflashmem.c
[-] CC cmdflashmemspiffs.c
[-] CC cmdsmartcard.c
[-] CC cmdusart.c
[-] CC cmdwiegand.c
[-] CC cmdparser.c
[-] CC cmdmain.c
[-] CC pm3_binlib.c
[-] CC scripting.c
[-] CC cmdscript.c
[-] CC pm3_bitlib.c
[-] CC cmdcrc.c
[-] CC ../common/bucketsort.c
[-] CC flash.c
[-] CC wiegand_formats.c
[-] CC wiegand_formatutils.c
[-] UIC ui/ui_overlays.h
[-] CXX proxgui.cpp
[-] CXX proxguiqt.cpp
[-] MOC proxguiqt.moc.cpp
[-] CXX proxguiqt.moc.cpp
[-] CC(NOSIMD) hardnested/hardnested_bf_core.c
[-] CC(NOSIMD) hardnested/hardnested_bitarray_core.c
[-] CC(MMX) hardnested/hardnested_bf_core.c
[-] CC(MMX) hardnested/hardnested_bitarray_core.c
[-] CC(SSE2) hardnested/hardnested_bf_core.c
[-] CC(SSE2) hardnested/hardnested_bitarray_core.c
[-] CC(AVX) hardnested/hardnested_bf_core.c
[-] CC(AVX) hardnested/hardnested_bitarray_core.c
[-] CC(AVX2) hardnested/hardnested_bf_core.c
[-] CC(AVX2) hardnested/hardnested_bitarray_core.c
[-] CC(AVX512) hardnested/hardnested_bf_core.c
[-] CC(AVX512) hardnested/hardnested_bitarray_core.c
[*] MAKE liblua for linux
[-] CC lapi.c
[-] CC lcode.c
[-] CC lctype.c
[-] CC ldebug.c
[-] CC ldo.c
[-] CC ldump.c
[-] CC lfunc.c
[-] CC lgc.c
[-] CC llex.c
[-] CC lmem.c
[-] CC lobject.c
[-] CC lopcodes.c
[-] CC lparser.c
[-] CC lstate.c
[-] CC lstring.c
[-] CC ltable.c
[-] CC ltm.c
[-] CC lundump.c
[-] CC lvm.c
[-] CC lzio.c
[-] CC lauxlib.c
[-] CC lbaselib.c
[-] CC lbitlib.c
[-] CC lcorolib.c
[-] CC ldblib.c
[-] CC liolib.c
[-] CC lmathlib.c
[-] CC loslib.c
[-] CC lstrlib.c
[-] CC ltablib.c
[-] CC loadlib.c
[-] CC linit.c
[=] AR liblua.a
[*] MAKE jansson
[-] CC dump.c
[-] CC error.c
[-] CC hashtable.c
[-] CC hashtable_seed.c
[-] CC load.c
[-] CC memory.c
[-] CC pack_unpack.c
[-] CC strbuffer.c
[-] CC strconv.c
[-] CC utf.c
[-] CC path.c
[-] CC value.c
[=] AR libjansson.a
[*] MAKE tinycbor
[-] CC cborencoder.c
[-] CC cborencoder_close_container_checked.c
[-] CC cborerrorstrings.c
[-] CC cborparser.c
[-] CC cborparser_dup_string.c
[-] CC cborpretty.c
[-] CC cbortojson.c
[-] CC cborvalidation.c
[=] AR tinycbor.a
[*] MAKE reveng
[-] CC bmpbit.c
[-] CC cli.c
[-] CC getopt.c
[-] CC model.c
[-] CC poly.c
[-] CC preset.c
[-] CC reveng.c
[-] CC bmpbit.c
[=] TEST bmptst
[=] AR libreveng.a
[*] MAKE mbedtls
[-] CC aes.c
[-] CC asn1parse.c
[-] CC asn1write.c
[-] CC base64.c
[-] CC bignum.c
[-] CC ctr_drbg.c
[-] CC entropy_poll.c
[-] CC entropy.c
[-] CC error.c
[-] CC timing.c
[-] CC ecp.c
[-] CC ecp_curves.c
[-] CC certs.c
[-] CC camellia.c
[-] CC blowfish.c
[-] CC cipher_wrap.c
[-] CC cipher.c
[-] CC cmac.c
[-] CC des.c
[-] CC ecdsa.c
[-] CC md.c
[-] CC md_wrap.c
[-] CC md5.c
[-] CC oid.c
[-] CC pem.c
[-] CC arc4.c
[-] CC pk.c
[-] CC pk_wrap.c
[-] CC pkwrite.c
[-] CC pkcs5.c
[-] CC pkcs12.c
[-] CC pkparse.c
[-] CC platform.c
[-] CC platform_util.c
[-] CC rsa.c
[-] CC rsa_internal.c
[-] CC sha1.c
[-] CC sha256.c
[-] CC sha512.c
[-] CC threading.c
[-] CC x509.c
[-] CC x509_crl.c
[-] CC x509_crt.c
[=] AR libmbedtls.a
[*] MAKE zlib
[-] CC deflate.c
[-] CC adler32.c
[-] CC trees.c
[-] CC zutil.c
[-] CC inflate.c
[-] CC inffast.c
[-] CC inftrees.c
[=] AR libz.a
[*] MAKE amiibo
[-] CC amiibo.c
[-] CC drbg.c
[-] CC keygen.c
[=] AR libamiibo.a
[=] GEN lualibs/pm3_cmd.lua
[=] GEN lualibs/mfc_default_keys.lua
[=] LD proxmark3
[*] MAKE bootrom/all
[=] GEN version.c
[-] CC version.c
[-] CC ram-reset.s
[-] CC flash-reset.s
[-] CC ../common_arm/usb_cdc.c
[-] CC ../common_arm/clocks.c
[-] CC bootrom.c
[=] LD obj/bootrom.elf
[=] GEN obj/bootrom.s19
[*] MAKE fpga_compress/all
[*] MAKE zlib
[-] CC deflate.c
[-] CC adler32.c
[-] CC trees.c
[-] CC zutil.c
[-] CC inflate.c
[-] CC inffast.c
[-] CC inftrees.c
[=] AR libz.a
[-] CC fpga_compress.c
[=] LD fpga_compress
[*] MAKE armsrc/all
[-] GEN fpga_version_info.c
[-] CC fpga_version_info.c
[-] GEN obj/fpga_all.bit.z
[-] GEN obj/fpga_all.o
[-] CC start.c
[-] CC iso15693.c
[-] CC ../common/iso15693tools.c
[-] CC thinfilm.c
[-] CC lfops.c
[-] CC lfsampling.c
[-] CC pcf7931.c
[-] CC ../common/lfdemod.c
[-] CC lfadc.c
[-] CC ../common/zlib/inflate.c
[-] CC ../common/zlib/inffast.c
[-] CC ../common/zlib/inftrees.c
[-] CC ../common/zlib/adler32.c
[-] CC ../common/zlib/zutil.c
[-] CC legicrf.c
[-] CC legicrfsim.c
[-] CC ../common/legic_prng.c
[-] CC flashmem.c
[-] CC i2c.c
[-] CC hitag2_crypto.c
[-] CC hitag2.c
[-] CC hitagS.c
[-] CC spiffs.c
[-] CC spiffs_cache.c
[-] CC spiffs_check.c
[-] CC spiffs_gc.c
[-] CC spiffs_nucleus.c
[-] CC spiffs_hydrogen.c
[-] CC appmain.c
[-] CC printf.c
[-] CC dbprint.c
[-] CC ../common/commonutil.c
[-] CC util.c
[-] CC string.c
[-] CC BigBuf.c
[-] CC ticks.c
[-] CC ../common_arm/clocks.c
[-] CC hfsnoop.c
[-] CC fpgaloader.c
[-] CC iso14443a.c
[-] CC mifareutil.c
[-] CC mifarecmd.c
[-] CC epa.c
[-] CC mifaresim.c
[-] CC iso14443b.c
[-] CC ../common/crapto1/crypto1.c
[-] CC des.c
[-] CC desfire_key.c
[-] CC mifaredesfire.c
[-] CC ../common/mbedtls/aes.c
[-] CC ../common/mbedtls/platform_util.c
[-] CC iclass.c
[-] CC optimized_cipher.c
[-] CC ../common/crc.c
[-] CC ../common/crc16.c
[-] CC ../common/crc32.c
[-] CC felica.c
[-] CC ../armsrc/Standalone/lf_samyrun.c
[-] CC ../common/parity.c
[-] CC ../common_arm/usb_cdc.c
[-] CC cmd.c
[-] GEN version.c
[-] CC version.c
[=] LD obj/fullimage.stage1.elf
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: obj/lfadc.o: in function `lf_manchester_send_bytes':
lfadc.c:(.text.lf_manchester_send_bytes+0x14): undefined reference to `lf_manchester_send_bit'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: lfadc.c:(.text.lf_manchester_send_bytes+0x1a): undefined reference to `lf_manchester_send_bit'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: lfadc.c:(.text.lf_manchester_send_bytes+0x20): undefined reference to `lf_manchester_send_bit'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: lfadc.c:(.text.lf_manchester_send_bytes+0x26): undefined reference to `lf_manchester_send_bit'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: lfadc.c:(.text.lf_manchester_send_bytes+0x2c): undefined reference to `lf_manchester_send_bit'
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: obj/lfadc.o:lfadc.c:(.text.lf_manchester_send_bytes+0x58): more undefined references to `lf_manchester_send_bit' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:179: obj/fullimage.stage1.elf] Error 1
make: *** [Makefile:95: armsrc/all] Error 2

**Desktop (please complete the following information):**
 - OS: Kali Rolling

**Comment by iceman1001** [comment]
duplicate issue
https://github.com/RfidResearchGroup/proxmark3/issues/541
