### ISSUE TITLE
Duplication of keys in mfc_default_keys.dic

### ISSUE THREAD

**Issue by will-caruana** [RfidResearchGroup/proxmark3#545]
It looks like the Transportes Insular La Palma and Granada, ES Transport Card share about half of there default keys. The following keys are in this list twice in mfc_default_keys.dic :
066b2f230172
0172066b2f03
0172066b2f33
0b0172066b2f
172066b2f2f0
2066b2f27017
2f130172066b
3b0172066b2f
66b2f1f01720
6b2f1b017206
70172066b2f0
70172066b2f3
72066b2f2b01
b2f170172066
f0f0172066b2
f3f0172066b2

**Comment by iceman1001** [comment]
make a PR
