### ISSUE TITLE
RVD4.01 unable to communicate with PC&phone

### ISSUE THREAD

**Issue by anonymix007** [RfidResearchGroup/proxmark3#558]
**Describe the bug**
Clients on Windows and Android cannot be used:
![image](https://user-images.githubusercontent.com/48598263/74436092-e4cd7900-4e76-11ea-8de2-9acff5b690d9.png)
(Windows)

![image](https://user-images.githubusercontent.com/48598263/74436243-252cf700-4e77-11ea-87ee-9cf4c7140356.png)
(Android)

**To Reproduce**
1. Open ProxSpace
2. Run proxmark3 com8
3. See error
or

1. Open Rfid Tools app
2. Select Proxmark 3
3. Select All Devices
4. Click PM3__RDV4.0
5. Wait and see error.

**Expected behavior**
I expected kinda working client, not an error

**Desktop (please complete the following information):**
 - OS: Windows 10 (1607 LTSB)/ Android 10 (Oneplus 7 Pro, Root, Stock ROM/Kernel)
> - inside proxmark3 client run the following commands and paste the output here.
>- hw version
> - hw status
> - data tune

All of that is impossible to get due to not working client

**Additional context**

**Comment by iceman1001** [comment]
Wrong repo.  
[RFID app repo,  note about firmware](https://github.com/RfidResearchGroup/RFIDtools#proxmark3-firmware)

**Comment by anonymix007** [comment]
> Wrong repo.

And what about first screenshot with error (Unknown command:: 0x61334d50[!!] ERROR: cannot communicate with the Proxmark) ?

**Comment by iceman1001** [comment]
same answer, wrong repo.  I even linked to the relevant text.

**Comment by anonymix007** [comment]
After installing that FW I was able to use app, but windows client shows this:
![image](https://user-images.githubusercontent.com/48598263/74514743-44cb2a80-4f1e-11ea-8faa-e3a0a9f5f4a3.png)

**Comment by anonymix007** [comment]
@iceman1001 Are there any instructions on building FW that can work with both Android app and client on Windows?

**Comment by iceman1001** [comment]
sadly no.
