### ISSUE TITLE
How to unbrick rdv4?

### ISSUE THREAD

**Issue by sp4rrows** [RfidResearchGroup/proxmark3#56]
Hi,
How is the procedure of unbricking?
Which tools are needed-same as for pm3rdv2?

-PROXMARK 3 RDV4 - FLASHING SUPPORT (https://lab401.com/products/proxmark-3-rdv4-flash-support)
And which other tool is needed?(Segger J-LINK, Proxmark 3 RDV J-Link adaptor, AVRISP mk2,...)

Would be great to get a short howto.

Thanks

**Comment by bogiton** [comment]
Oooh, I like this adaptor! Very fancy!
I think it should be included in RDV4 and Chameleon rebooted wikis.
Btw, any idea how these smaller pin headers are called?

**Comment by RfidResearchGroup** [comment]
Yes, the adapter is slick.   Feel free to update all the Wikis..  (Rdv4,  official pm3,  chameleon rebooted and the chameleon rebooted gui )    :)

**Comment by bogiton** [comment]
Can't create a new page in rdv4 wiki. I updated the respective page in Chameleon.

**Comment by sp4rrows** [comment]
I has some issues while testing with my raspi.
Thanks the De-bricking-Segger has helped.

**Comment by RfidResearchGroup** [comment]
@bogiton   I can't see the wiki changes...  I added a page on this wiki.
