### ISSUE TITLE
Question About SamyRun UI 

### ISSUE THREAD

**Issue by Jadelutis** [RfidResearchGroup/proxmark3#562]
Sorry if this is a stupid question but I wanted to know if anyone could layout how to navigate the Samyrun standalone mode. Also, I wanted to know if there was a way to switch between the two card slots in samyrun after recording to replace each one without re-recording.
Thanks,
Justin

**Comment by iceman1001** [comment]
The standalone modes isn't "supported" by the maintainers of this repo per se. 
You would need to contact the author, track down blogs/forum posts or the easiest way, start reading the source code and figure it out.

Some info is found in the wiki but its kind of outdated when it comes to LF_SAMY_RUN.
