### ISSUE TITLE
Convert all python scripts to python3

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#564]
- [x] ./fpga/tests/plot_edgedetect.py
- [x] ./tools/findbits.py
- [x] ./tools/findbits_test.py
- [x] ./tools/pm3_eml2mfd.py
- [x] ./tools/pm3_eml_mfd_test.py
- [x] ./tools/pm3_mfdread.py
- [x] ./tools/pm3_mfd2eml.py
- [x] ./tools/xorcheck.py

And this one can probably be fixed to python3 too:
- [ ] ./tools/pm3_mf7b_wipe.py #! /usr/bin/env python3.6

**Comment by iceman1001** [comment]
@sigwinch28 
If you are up to it,  start converting to python3 would be nice.

**Comment by sigwinch28** [comment]
I will see how far i get with `2to3`.

I'll catalog the dependencies that the scripts have, too: some have numpy dependencies, etc.

**Comment by iceman1001** [comment]
that is a good way forward.

**Comment by sigwinch28** [comment]
Dependency search:

* [x]  `./fpga/tests/plot_edgedetect.py`: `numpy`, `matplotlib`
* [x] `./tools/btaddon/hc06_factory.py`: `pySerial`?
* [x] `./tools/btaddon/hc06_console_AT.py`: `pySerial`?
* [x]  `./tools/xorcheck.py`: no external dependencies
* [x]  `./tools/pm3_mfdread.py`: `bitstring`
* [x]  `./tools/findbits_test.py`: no external dependencies, imports `findbits` locally.
* [x]  `./tools/pm3_mfd2eml.py`: no external dependencies
* [x]  `./tools/findbits.py`: no external dependencies
* [x]  `./tools/pm3_eml2mfd.py`: no external dependencies
* [x]  `./tools/pm3_eml_mfd_test.py`: no external dependencies, imports `pm3_eml2mfd` and `pm3_mfd2eml` locally
* [x]  `./tools/pm3_mf7b_wipe.py`: no external dependencies

Looks like the dependencies are:
- `fpga/tests`: `numpy` and `matplotlib`
- `tools`: `bitstring`
- `tools/btaddon`: `pySerial` (unconfirmed)

**Comment by doegox** [comment]
Thanks for the list!
It is a bit overkill to require every pm3 user to install these dependencies.
These scripts are for very specific and rare use.
I prefer to catch properly the errors and guide the user.

**Comment by sigwinch28** [comment]
> Thanks for the list!
> It is a bit overkill to require every pm3 user to install these dependencies.

I agree, but perhaps we could document them somehow, for example:
- adding comments to the tools which have external dependencies; or
- adding a `requirements.txt` to the relevant directories (or whatever is fashionable these days)

**Comment by doegox** [comment]
requirements.txt are more for at least a directory of related tools, here we have all kind of scripts arbitrarily grouped.

See latest commits, the 4 scripts are now simply exiting with "Please install XXX module first" messages

**Comment by iceman1001** [comment]
Very few compiles FPGA code.  Even less runs the tests.  :)

**Comment by doegox** [comment]
lol, I even never noticed the fpga test script before today

**Comment by doegox** [comment]
done, thanks for the help @sigwinch28 !
