### ISSUE TITLE
hitag, determine adc levels to get better demodulation

### ISSUE THREAD

**Issue by cosmo6110** [RfidResearchGroup/proxmark3#570]
wrong freq for me! it stop working (keyfob) on 125khz

FpgaSendCommand(FPGA_CMD_SET_DIVISOR, 95); //125Khz FpgaSendCommand(FPGA_CMD_SET_DIVISOR, LF_DIVISOR_134);

The update is a huge improvement.
Thank's for the hard work on hitag

**Comment by iceman1001** [comment]
Not sure I am following now.
125Khz worked for you or did 134Khz work for you?

What device do you have?   Which antenna?

**Comment by cosmo6110** [comment]
I got the Proxmark3 RDV4.01 with LF Read Range (long range antenna).
After the latest update "LF_DIVISOR_134" it stop working on the 125 khz.

**Comment by iceman1001** [comment]
Does your antenna have a setting for freq 125/134 and Q 14/7 ?  Take a picture of it.
If so, try 134 / 7 

otherwise try
```
hw dbg 4
data plot
lf hitag info
data sample
data ltrim 30000
```

And post a picture of the graph...

**Comment by cosmo6110** [comment]
134 did the trick with my antenna on the 125khz transponder.

First picture is with  the old setting. FpgaSendCommand(FPGA_CMD_SET_DIVISOR, 95); //125Khz
125 /14
second picture is with the FpgaSendCommand(FPGA_CMD_SET_DIVISOR, LF_DIVISOR_134);
134 / 7
Thank's maybe we shall close thi issue?
![old_sample](https://user-images.githubusercontent.com/9219468/75109501-3bc81080-5624-11ea-8636-baf5fa2dd331.png)
![sample](https://user-images.githubusercontent.com/9219468/75109502-408cc480-5624-11ea-9262-f535b68e7cb6.png)

**Comment by iceman1001** [comment]
interesting that your tag is 125 kHz.  
I should adjust the hitag code to use the _lf config_ setting.  so we can use both 125 or 134.
