### ISSUE TITLE
Client stuck on Debian 10

### ISSUE THREAD

**Issue by CthUlhUzzz** [RfidResearchGroup/proxmark3#576]
I cloned the latest b87b031 commit and compile it on Debian 10. Client stuck on load (even in standalone mode) and one of the threads load on 100%. But on Kali linux all works fine
![75248465-47166a00-57e5-11ea-8b38-16d859c4cd13](https://user-images.githubusercontent.com/6465228/75335783-1bee5200-589b-11ea-81c6-38e37a9a675a.png)
I find the same issue (https://github.com/RfidResearchGroup/proxmark3/issues/188), but it marked solved

**Comment by iceman1001** [comment]
Debian 10 seems to be a troublesum OS...
I had to run the client as _sudo_ even to get it started.

There is isssus with **hf mf autopwn**  and **hf mf hardnested** on Debian 10.

Standalone mode doesnt need a client...
Make sure you remove modem manager and logout / login afterwards.

**Comment by CthUlhUzzz** [comment]
The client started with sudo. Any thoughts on what could be the problem?

**Comment by iceman1001** [comment]
I have no idea. You haven't followed the instructions for posting new issues, so there is not enough information to go with.

**Comment by CthUlhUzzz** [comment]
With root, the client does not load qt5/plugins/platformthemes/KDEPlasmaPlatformTheme.so and the huge list of libraries that depend on it.
`make SKIPQT=1` solve my problem

**Comment by iceman1001** [comment]
QT should work on a full fledge *nix system like Debian 10.   
I got it to work by using a different theme,  and running as sudo.
