### ISSUE TITLE
USB description error

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#584]
After updating to current firmware got an USB description error. Have backed again to older version and have positive dynamics.

**Comment by iceman1001** [comment]
We would need more details than that in order to look into this claim.

**Comment by Windslab** [comment]
Proxmark easy jumping with USB Descriptor after flashing.
*Sorry NO Description is DESCRIPTOR
What is the orfografii correction doing is not good sometimes

**Comment by iceman1001** [comment]
You would need to write which steps you did and your output from the commands you ran.

None of my proxmark3 get a bad usb descriptor when flashing.  It could be related to Pm3 Easy clone hardware.  In such case nothing to do here.

**Comment by Windslab** [comment]
My steps is: Compile> FLASH - All.bat and obtain err of USB Descriptor
After about 5 time poweroff I see COM in my hardware list.
Have you did any changers with communication setting last time? Before thise relise all been good.

You can't say "Pm3 Easy clone hardware" it is an open source project with shared PCBs. Anybody can reproduce it.

**Comment by iceman1001** [comment]
Flash All.bat?  Thats not a file in this repo.  You seem to be using some precompiled binaries.

Nothing changed in communication setting last time. 

The phrase "pm3 easy clone hardware" come from hardware manufacturers who produce crappy products.  Nothing about being open source project at all.
