### ISSUE TITLE
The "lf search" plus version(Automated iteration division value)

### ISSUE THREAD

**Issue by xianglin1998** [RfidResearchGroup/proxmark3#588]
The frequency of some ID cards is relatively rare. At this time, the standard 125kHz search will not work. I improved this situation and confirmed the command as "LF search + +"

This is lf search++ of RFID Tools client. Because I changed the communication part of the library a lot, I couldn't submit it directly.

My Impl code:
https://paste.ubuntu.com/p/w2B3V5Rr4H/

**Comment by iceman1001** [comment]
Cool idea,   let me just ask about how much the changing of frequency during **lf search** helps?

Have you tried your search++ on cards that has 250 kHz, 375 kHz, 500 kHz?
```
   // 95 -> 125.00
    // 88 -> 134.83
    // 47 -> 250.00
    // 31 -> 375.00
    // 23 -> 500.00
```
If you did,  did those cards hadve a modulation that was identified with the currect implemented demods in the pm3 client?

Since basically you are running **lf search** with different frequence and run all known demodulations against it over and over.

I am curious to hear if you have cards with those frequences and which results you got from your extended search.

**Comment by xianglin1998** [comment]
Yes, I have tried to search tag with 134khz and 250kHz frequencies. When I configure it as 88, I can search tag with 134khz frequencies, and 250kHz frequencies.

Similarly, 250kHz tag need to be configured with 47 divisors to search for tag.

The modulation of these special frequency ID cards is no different from ordinary ID cards, that is, the capacitive inductance on the hardware has been changed, resulting in that the RF frequency cannot be correctly matched by the client of PM3 (default 125khz). We need to perform frequency matching until The card is correctly communicated.

We have tested that it is indeed available, for cards with special frequencies, when the standard search instructions are not available.

**Comment by iceman1001** [comment]
I am very well aware of the purpose of the divisor. That wasn't my question.

My question is if you actually tested against a 250khz card and got it to be identified with the known demodulations inside **lf search**.   

The problem with your experiments as I seem it,  is that you change divisor but your hardware antenna is still tuned for 125 kHz.   

Let me demonstrate it with a picture.
![image](https://user-images.githubusercontent.com/8577004/75957906-5f5c4800-5ebb-11ea-97c0-3bf924a295f3.png)

What kind of voltage are you getting out of your antenna at those frequencies to power a tag and is the build in demodulation able to do its work with such time voltage changes?

**Comment by xianglin1998** [comment]
Today, we tested the special frequency tag from 125khz to 500khz, but the result is not satisfactory. We need to replace the antenna, hahaha, so this instruction can be kept temporarily, and we hope there will be a hardware solution for automatic frequency tuning in the future.

**Comment by xianglin1998** [comment]
;) Thank you for checking.

**Comment by iceman1001** [comment]
Special frequency tag,   interesting,  link to a page?  datasheet?

**Comment by xianglin1998** [comment]
Yes is very interesting.

You can buy it on taobao:

https://detail.tmall.com/item.htm?spm=a230r.1.14.36.78b361c0gutHid&id=610148446963&ns=1&abbucket=1&skuId=4460492583507

**Comment by xianglin1998** [comment]
But I don't have a datasheet.

**Comment by iceman1001** [comment]
Cool,  I am curious on what type of keyfob.  Like what it can do.

**Comment by xianglin1998** [comment]
They look like ordinary tags, but in fact, the coil and capacitance parameters have been adjusted. It needs a specific card reader to read the card. On the ordinary 125 kHz card reader, it does not work.

**Comment by iceman1001** [comment]
yes,  but are they EM4100 / t5577 / prox ?  What can the keyfob do besides 250/375/500?

**Comment by xianglin1998** [comment]
It is can change type at em & t55xx between，like your t5577, the type of card has nothing to do with the frequency.

**Comment by iceman1001** [comment]
cool,  now I will need to get one of those keyfobs...  and an tunable antenna.

**Comment by xianglin1998** [comment]
I'll ask Olaf to make antennas for these frequencies, and then I'll pack the antennas and keyfob and send them to you.

:)

**Comment by xianglin1998** [comment]
some 250, 375, 500khz keyfobs.

**Comment by xianglin1998** [comment]
and 250, 375, 500khz antennas .

**Comment by iceman1001** [comment]
Sounds like a great plan.
Push his limits by saying one antenna with auto-tuning and dynamic frequency selection. 
That will be a challenge for him,  he likes that.
