### ISSUE TITLE
Proxspace V3.3 emojis support

### ISSUE THREAD

**Issue by cosmo6110** [RfidResearchGroup/proxmark3#609]
Cant compile after the latest emoji update.

`emojis.h:25:42: error: converting to execution character set: Illegal byte sequence
   25 |     {":smiling_face_with_three_hearts:", "­m},`
[*] MAKE client/all
[-] CC proxmark3.c
[-] CC uart/uart_posix.c
[-] CC uart/uart_win32.c
[-] CC ui.c
In file included from ui.c:34:
emojis.h:11:20: error: converting to execution character set: Illegal byte sequence
   11 |     {":grinning:", "­m},
      |                    ^~~~~~
emojis.h:12:18: error: converting to execution character set: Illegal byte sequence
   12 |     {":smiley:", "­m},
      |                  ^~~~~~
emojis.h:13:17: error: converting to execution character set: Illegal byte sequence
   13 |     {":smile:", "­m},
      |                 ^~~~~~
emojis.h:14:16: error: converting to execution character set: Illegal byte sequence
   14 |     {":grin:", "­m},
      |                ^~~~~~
emojis.h:15:20: error: converting to execution character set: Illegal byte sequence
   15 |     {":laughing:", "­m},
      |                    ^~~~~~
emojis.h:16:21: error: converting to execution character set: Illegal byte sequence
   16 |     {":satisfied:", "­m},
      |                     ^~~~~~
emojis.h:17:23: error: converting to execution character set: Illegal byte sequence
   17 |     {":sweat_smile:", "­m},
      |                       ^~~~~~
emojis.h:18:16: error: converting to execution character set: Illegal byte sequence
   18 |     {":rofl:", "­m},
      |                ^~~~~~
emojis.h:19:15: error: converting to execution character set: Illegal byte sequence
   19 |     {":joy:", "­m},
      |               ^~~~~~
emojis.h:20:33: error: converting to execution character set: Illegal byte sequence
   20 |     {":slightly_smiling_face:", "­m},
      |                                 ^~~~~~
emojis.h:21:28: error: converting to execution character set: Illegal byte sequence
   21 |     {":upside_down_face:", "­m},
      |                            ^~~~~~
emojis.h:22:16: error: converting to execution character set: Illegal byte sequence
   22 |     {":wink:", "­m},
      |                ^~~~~~
emojis.h:23:17: error: converting to execution character set: Illegal byte sequence
   23 |     {":blush:", "­m},
      |                 ^~~~~~
emojis.h:24:20: error: converting to execution character set: Illegal byte sequence
   24 |     {":innocent:", "­m},
      |                    ^~~~~~
emojis.h:25:42: error: converting to execution character set: Illegal byte sequence
   25 |     {":smiling_face_with_three_hearts:", "­m},
      |                                          ^~~~~~
emojis.h:26:22: error: converting to execution character set: Illegal byte sequence
   26 |     {":heart_eyes:", "­m},
      |                      ^~~~~~
emojis.h:27:23: error: converting to execution character set: Illegal byte sequence
   27 |     {":star_struck:", "­m},
      |                       ^~~~~~
emojis.h:28:25: error: converting to execution character set: Illegal byte sequence
   28 |     {":kissing_heart:", "­m},
      |                         ^~~~~~
emojis.h:29:19: error: converting to execution character set: Illegal byte sequence
   29 |     {":kissing:", "­m},
      |                   ^~~~~~
emojis.h:30:19: error: converting to execution character set: Illegal byte sequence
   30 |     {":relaxed:", "Ôm},
      |                   ^~~~~~~~
emojis.h:31:31: error: converting to execution character set: Illegal byte sequence
   31 |     {":kissing_closed_eyes:", "­m},
      |                               ^~~~~~
emojis.h:32:32: error: converting to execution character set: Illegal byte sequence
   32 |     {":kissing_smiling_eyes:", "­m},
      |                                ^~~~~~
emojis.h:33:34: error: converting to execution character set: Illegal byte sequence
   33 |     {":smiling_face_with_tear:", "­m},
      |                                  ^~~~~~
emojis.h:34:15: error: converting to execution character set: Illegal byte sequence
   34 |     {":yum:", "­m},
      |               ^~~~~~
emojis.h:35:28: error: converting to execution character set: Illegal byte sequence
   35 |     {":stuck_out_tongue:", "­m},
      |                            ^~~~~~
emojis.h:36:40: error: converting to execution character set: Illegal byte sequence
   36 |     {":stuck_out_tongue_winking_eye:", "­m},
      |                                        ^~~~~~
emojis.h:37:21: error: converting to execution character set: Illegal byte sequence
   37 |     {":zany_face:", "­m},
      |                     ^~~~~~
emojis.h:38:40: error: converting to execution character set: Illegal byte sequence
   38 |     {":stuck_out_tongue_closed_eyes:", "­m},
      |                                        ^~~~~~
emojis.h:39:28: error: converting to execution character set: Illegal byte sequence
   39 |     {":money_mouth_face:", "­m},
      |                            ^~~~~~
emojis.h:40:16: error: converting to execution character set: Illegal byte sequence
   40 |     {":hugs:", "­m},
      |                ^~~~~~
emojis.h:41:27: error: converting to execution character set: Illegal byte sequence
   41 |     {":hand_over_mouth:", "­m},
      |                           ^~~~~~
emojis.h:42:25: error: converting to execution character set: Illegal byte sequence
   42 |     {":shushing_face:", "­m},
      |                         ^~~~~~
emojis.h:43:20: error: converting to execution character set: Illegal byte sequence
   43 |     {":thinking:", "­m},
      |                    ^~~~~~
emojis.h:44:29: error: converting to execution character set: Illegal byte sequence
   44 |     {":zipper_mouth_face:", "­m},
      |                             ^~~~~~
emojis.h:45:26: error: converting to execution character set: Illegal byte sequence
   45 |     {":raised_eyebrow:", "­m},
      |                          ^~~~~~
emojis.h:46:24: error: converting to execution character set: Illegal byte sequence
   46 |     {":neutral_face:", "­m},
      |                        ^~~~~~
emojis.h:47:26: error: converting to execution character set: Illegal byte sequence
   47 |     {":expressionless:", "­m},
      |                          ^~~~~~
emojis.h:48:20: error: converting to execution character set: Illegal byte sequence
   48 |     {":no_mouth:", "­m},
      |                    ^~~~~~
emojis.h:49:17: error: converting to execution character set: Illegal byte sequence
   49 |     {":smirk:", "­m},
      |                 ^~~~~~
emojis.h:50:20: error: converting to execution character set: Illegal byte sequence
   50 |     {":unamused:", "­m},
      |                    ^~~~~~
emojis.h:51:21: error: converting to execution character set: Illegal byte sequence
   51 |     {":roll_eyes:", "­m},
      |                     ^~~~~~
emojis.h:52:21: error: converting to execution character set: Illegal byte sequence
   52 |     {":grimacing:", "­m},
      |                     ^~~~~~
emojis.h:53:22: error: converting to execution character set: Illegal byte sequence
   53 |     {":lying_face:", "­m},
      |                      ^~~~~~
emojis.h:54:20: error: converting to execution character set: Illegal byte sequence
   54 |     {":relieved:", "­m},
      |                    ^~~~~~
emojis.h:55:19: error: converting to execution character set: Illegal byte sequence
   55 |     {":pensive:", "­m},
      |                   ^~~~~~
emojis.h:56:18: error: converting to execution character set: Illegal byte sequence
   56 |     {":sleepy:", "­m},
      |                  ^~~~~~
emojis.h:57:25: error: converting to execution character set: Illegal byte sequence
   57 |     {":drooling_face:", "­m},
      |                         ^~~~~~
emojis.h:58:20: error: converting to execution character set: Illegal byte sequence
   58 |     {":sleeping:", "­m},
      |                    ^~~~~~
emojis.h:59:16: error: converting to execution character set: Illegal byte sequence
   59 |     {":mask:", "­m},
      |                ^~~~~~
emojis.h:60:33: error: converting to execution character set: Illegal byte sequence
   60 |     {":face_with_thermometer:", "­m},
      |                                 ^~~~~~
emojis.h:61:34: error: converting to execution character set: Illegal byte sequence
   61 |     {":face_with_head_bandage:", "­m},
      |                                  ^~~~~~
emojis.h:62:26: error: converting to execution character set: Illegal byte sequence
   62 |     {":nauseated_face:", "­m},
      |                          ^~~~~~
emojis.h:63:25: error: converting to execution character set: Illegal byte sequence
   63 |     {":vomiting_face:", "­m},
      |                         ^~~~~~
emojis.h:64:25: error: converting to execution character set: Illegal byte sequence
   64 |     {":sneezing_face:", "­m},
      |                         ^~~~~~
emojis.h:65:20: error: converting to execution character set: Illegal byte sequence
   65 |     {":hot_face:", "­m},
      |                    ^~~~~~
emojis.h:66:21: error: converting to execution character set: Illegal byte sequence
   66 |     {":cold_face:", "­m},
      |                     ^~~~~~
emojis.h:67:22: error: converting to execution character set: Illegal byte sequence
   67 |     {":woozy_face:", "­m},
      |                      ^~~~~~
emojis.h:68:22: error: converting to execution character set: Illegal byte sequence
   68 |     {":dizzy_face:", "­m},
      |                      ^~~~~~
emojis.h:69:26: error: converting to execution character set: Illegal byte sequence
   69 |     {":exploding_head:", "­m},
      |                          ^~~~~~
emojis.h:70:27: error: converting to execution character set: Illegal byte sequence
   70 |     {":cowboy_hat_face:", "­m},
      |                           ^~~~~~
emojis.h:71:25: error: converting to execution character set: Illegal byte sequence
   71 |     {":partying_face:", "­m},
      |                         ^~~~~~
emojis.h:72:26: error: converting to execution character set: Illegal byte sequence
   72 |     {":disguised_face:", "­m},
      |                          ^~~~~~
emojis.h:73:22: error: converting to execution character set: Illegal byte sequence
   73 |     {":sunglasses:", "­m},
      |                      ^~~~~~
emojis.h:74:21: error: converting to execution character set: Illegal byte sequence
   74 |     {":nerd_face:", "­m},
      |                     ^~~~~~
emojis.h:75:24: error: converting to execution character set: Illegal byte sequence
   75 |     {":monocle_face:", "­m},
      |                        ^~~~~~
emojis.h:76:20: error: converting to execution character set: Illegal byte sequence
   76 |     {":confused:", "­m},
      |                    ^~~~~~
emojis.h:77:19: error: converting to execution character set: Illegal byte sequence
   77 |     {":worried:", "­m},
      |                   ^~~~~~
emojis.h:78:34: error: converting to execution character set: Illegal byte sequence
   78 |     {":slightly_frowning_face:", "­m},
      |                                  ^~~~~~
emojis.h:79:25: error: converting to execution character set: Illegal byte sequence
   79 |     {":frowning_face:", "Ôm},
      |                         ^~~~~~~~
emojis.h:80:22: error: converting to execution character set: Illegal byte sequence
   80 |     {":open_mouth:", "­m},
      |                      ^~~~~~
emojis.h:81:18: error: converting to execution character set: Illegal byte sequence
   81 |     {":hushed:", "­m},
      |                  ^~~~~~
emojis.h:82:22: error: converting to execution character set: Illegal byte sequence
   82 |     {":astonished:", "­m},
      |                      ^~~~~~
emojis.h:83:19: error: converting to execution character set: Illegal byte sequence
   83 |     {":flushed:", "­m},
      |                   ^~~~~~
emojis.h:84:25: error: converting to execution character set: Illegal byte sequence
   84 |     {":pleading_face:", "­m},
      |                         ^~~~~~
emojis.h:85:20: error: converting to execution character set: Illegal byte sequence
   85 |     {":frowning:", "­m},
      |                    ^~~~~~
emojis.h:86:21: error: converting to execution character set: Illegal byte sequence
   86 |     {":anguished:", "­m},
      |                     ^~~~~~
emojis.h:87:19: error: converting to execution character set: Illegal byte sequence
   87 |     {":fearful:", "­m},
      |                   ^~~~~~
emojis.h:88:22: error: converting to execution character set: Illegal byte sequence
   88 |     {":cold_sweat:", "­m},
      |                      ^~~~~~
emojis.h:89:33: error: converting to execution character set: Illegal byte sequence
   89 |     {":disappointed_relieved:", "­m},
      |                                 ^~~~~~
emojis.h:90:15: error: converting to execution character set: Illegal byte sequence
   90 |     {":cry:", "­m},
      |               ^~~~~~
emojis.h:91:15: error: converting to execution character set: Illegal byte sequence
   91 |     {":sob:", "­m},
      |               ^~~~~~
emojis.h:92:18: error: converting to execution character set: Illegal byte sequence
   92 |     {":scream:", "­m},
      |                  ^~~~~~
emojis.h:93:22: error: converting to execution character set: Illegal byte sequence
   93 |     {":confounded:", "­m},
      |                      ^~~~~~
emojis.h:94:21: error: converting to execution character set: Illegal byte sequence
   94 |     {":persevere:", "­m},
      |                     ^~~~~~
emojis.h:95:24: error: converting to execution character set: Illegal byte sequence
   95 |     {":disappointed:", "­m},
      |                        ^~~~~~
emojis.h:96:17: error: converting to execution character set: Illegal byte sequence
   96 |     {":sweat:", "­m},
      |                 ^~~~~~
emojis.h:97:17: error: converting to execution character set: Illegal byte sequence
   97 |     {":weary:", "­m},
      |                 ^~~~~~
emojis.h:98:22: error: converting to execution character set: Illegal byte sequence
   98 |     {":tired_face:", "­m},
      |                      ^~~~~~
emojis.h:99:24: error: converting to execution character set: Illegal byte sequence
   99 |     {":yawning_face:", "­m},
      |                        ^~~~~~
emojis.h:100:19: error: converting to execution character set: Illegal byte sequence
  100 |     {":triumph:", "­m},
      |                   ^~~~~~
emojis.h:101:16: error: converting to execution character set: Illegal byte sequence
  101 |     {":rage:", "­m},
      |                ^~~~~~
emojis.h:102:16: error: converting to execution character set: Illegal byte sequence
  102 |     {":pout:", "­m},
      |                ^~~~~~
emojis.h:103:17: error: converting to execution character set: Illegal byte sequence
  103 |     {":angry:", "­m},
      |                 ^~~~~~
emojis.h:104:24: error: converting to execution character set: Illegal byte sequence
  104 |     {":cursing_face:", "­m},
      |                        ^~~~~~
emojis.h:105:23: error: converting to execution character set: Illegal byte sequence
  105 |     {":smiling_imp:", "­m},
      |                       ^~~~~~
emojis.h:106:15: error: converting to execution character set: Illegal byte sequence
  106 |     {":imp:", "­m},
      |               ^~~~~~
emojis.h:107:17: error: converting to execution character set: Illegal byte sequence
  107 |     {":skull:", "­m},
      |                 ^~~~~~
emojis.h:108:32: error: converting to execution character set: Illegal byte sequence
  108 |     {":skull_and_crossbones:", "Ôm},
      |                                ^~~~~~~~
emojis.h:109:18: error: converting to execution character set: Illegal byte sequence
  109 |     {":hankey:", "­m},
      |                  ^~~~~~
emojis.h:110:16: error: converting to execution character set: Illegal byte sequence
  110 |     {":poop:", "­m},
      |                ^~~~~~
emojis.h:111:16: error: converting to execution character set: Illegal byte sequence
  111 |     {":shit:", "­m},
      |                ^~~~~~
emojis.h:112:22: error: converting to execution character set: Illegal byte sequence
  112 |     {":clown_face:", "­m},
      |                      ^~~~~~
emojis.h:113:25: error: converting to execution character set: Illegal byte sequence
  113 |     {":japanese_ogre:", "­m},
      |                         ^~~~~~
emojis.h:114:27: error: converting to execution character set: Illegal byte sequence
  114 |     {":japanese_goblin:", "­m},
      |                           ^~~~~~
emojis.h:115:17: error: converting to execution character set: Illegal byte sequence
  115 |     {":ghost:", "­m},
      |                 ^~~~~~
emojis.h:116:17: error: converting to execution character set: Illegal byte sequence
  116 |     {":alien:", "­m},
      |                 ^~~~~~
emojis.h:117:25: error: converting to execution character set: Illegal byte sequence
  117 |     {":space_invader:", "­m},
      |                         ^~~~~~
emojis.h:118:17: error: converting to execution character set: Illegal byte sequence
  118 |     {":robot:", "­m},
      |                 ^~~~~~
emojis.h:119:22: error: converting to execution character set: Illegal byte sequence
  119 |     {":smiley_cat:", "­m},
      |                      ^~~~~~
emojis.h:120:21: error: converting to execution character set: Illegal byte sequence
  120 |     {":smile_cat:", "­m},
      |                     ^~~~~~
emojis.h:121:19: error: converting to execution character set: Illegal byte sequence
  121 |     {":joy_cat:", "­m},
      |                   ^~~~~~
emojis.h:122:26: error: converting to execution character set: Illegal byte sequence
  122 |     {":heart_eyes_cat:", "­m},
      |                          ^~~~~~
emojis.h:123:21: error: converting to execution character set: Illegal byte sequence
  123 |     {":smirk_cat:", "­m},
      |                     ^~~~~~
emojis.h:124:23: error: converting to execution character set: Illegal byte sequence
  124 |     {":kissing_cat:", "­m},
      |                       ^~~~~~
emojis.h:125:22: error: converting to execution character set: Illegal byte sequence
  125 |     {":scream_cat:", "­m},
      |                      ^~~~~~
emojis.h:126:27: error: converting to execution character set: Illegal byte sequence
  126 |     {":crying_cat_face:", "­m},
      |                           ^~~~~~
emojis.h:127:23: error: converting to execution character set: Illegal byte sequence
  127 |     {":pouting_cat:", "­m},
      |                       ^~~~~~
emojis.h:128:23: error: converting to execution character set: Illegal byte sequence
  128 |     {":see_no_evil:", "­m},
      |                       ^~~~~~
emojis.h:129:24: error: converting to execution character set: Illegal byte sequence
  129 |     {":hear_no_evil:", "­m},
      |                        ^~~~~~
emojis.h:130:25: error: converting to execution character set: Illegal byte sequence
  130 |     {":speak_no_evil:", "­m},
      |                         ^~~~~~
emojis.h:131:16: error: converting to execution character set: Illegal byte sequence
  131 |     {":kiss:", "­m},
      |                ^~~~~~
emojis.h:132:23: error: converting to execution character set: Illegal byte sequence
  132 |     {":love_letter:", "­m},
      |                       ^~~~~~
emojis.h:133:17: error: converting to execution character set: Illegal byte sequence
  133 |     {":cupid:", "­m},
      |                 ^~~~~~
emojis.h:134:22: error: converting to execution character set: Illegal byte sequence
  134 |     {":gift_heart:", "­m},
      |                      ^~~~~~
emojis.h:135:27: error: converting to execution character set: Illegal byte sequence
  135 |     {":sparkling_heart:", "­m},
      |                           ^~~~~~
emojis.h:136:22: error: converting to execution character set: Illegal byte sequence
  136 |     {":heartpulse:", "­m},
      |                      ^~~~~~
emojis.h:137:21: error: converting to execution character set: Illegal byte sequence
  137 |     {":heartbeat:", "­m},
      |                     ^~~~~~
emojis.h:138:28: error: converting to execution character set: Illegal byte sequence
  138 |     {":revolving_hearts:", "­m},
      |                            ^~~~~~
emojis.h:139:22: error: converting to execution character set: Illegal byte sequence
  139 |     {":two_hearts:", "­m},
      |                      ^~~~~~
emojis.h:140:28: error: converting to execution character set: Illegal byte sequence
  140 |     {":heart_decoration:", "­m},
      |                            ^~~~~~
emojis.h:141:35: error: converting to execution character set: Illegal byte sequence
  141 |     {":heavy_heart_exclamation:", "Ôm},
      |                                   ^~~~~~~~
emojis.h:142:24: error: converting to execution character set: Illegal byte sequence
  142 |     {":broken_heart:", "­m},
      |                        ^~~~~~
emojis.h:143:17: error: converting to execution character set: Illegal byte sequence
  143 |     {":heart:", "Ôm},
      |                 ^~~~~~~~
emojis.h:144:24: error: converting to execution character set: Illegal byte sequence
  144 |     {":orange_heart:", "­m},
      |                        ^~~~~~
emojis.h:145:24: error: converting to execution character set: Illegal byte sequence
  145 |     {":yellow_heart:", "­m},
      |                        ^~~~~~
emojis.h:146:23: error: converting to execution character set: Illegal byte sequence
  146 |     {":green_heart:", "­m},
      |                       ^~~~~~
emojis.h:147:22: error: converting to execution character set: Illegal byte sequence
  147 |     {":blue_heart:", "­m},
      |                      ^~~~~~
emojis.h:148:24: error: converting to execution character set: Illegal byte sequence
  148 |     {":purple_heart:", "­m},
      |                        ^~~~~~
emojis.h:149:23: error: converting to execution character set: Illegal byte sequence
  149 |     {":brown_heart:", "­m},
      |                       ^~~~~~
emojis.h:150:23: error: converting to execution character set: Illegal byte sequence
  150 |     {":black_heart:", "­m},
      |                       ^~~~~~
emojis.h:151:23: error: converting to execution character set: Illegal byte sequence
  151 |     {":white_heart:", "­m},
      |                       ^~~~~~
emojis.h:152:15: error: converting to execution character set: Illegal byte sequence
  152 |     {":100:", "­m},
      |               ^~~~~~
emojis.h:153:17: error: converting to execution character set: Illegal byte sequence
  153 |     {":anger:", "­m},
      |                 ^~~~~~
emojis.h:154:16: error: converting to execution character set: Illegal byte sequence
  154 |     {":boom:", "­m},
      |                ^~~~~~
emojis.h:155:21: error: converting to execution character set: Illegal byte sequence
  155 |     {":collision:", "­m},
      |                     ^~~~~~
emojis.h:156:17: error: converting to execution character set: Illegal byte sequence
  156 |     {":dizzy:", "­m},
      |                 ^~~~~~
emojis.h:157:23: error: converting to execution character set: Illegal byte sequence
  157 |     {":sweat_drops:", "­m},
      |                       ^~~~~~
emojis.h:158:16: error: converting to execution character set: Illegal byte sequence
  158 |     {":dash:", "­m},
      |                ^~~~~~
emojis.h:159:16: error: converting to execution character set: Illegal byte sequence
  159 |     {":hole:", "­m},
      |                ^~~~~~~~~
emojis.h:160:16: error: converting to execution character set: Illegal byte sequence
  160 |     {":bomb:", "­m},
      |                ^~~~~~
emojis.h:161:26: error: converting to execution character set: Illegal byte sequence
  161 |     {":speech_balloon:", "­m},
      |                          ^~~~~~
emojis.h:162:29: error: converting to execution character set: Illegal byte sequence
  162 |     {":eye_speech_bubble:", "­m},
      |                             ^~~~~~~~~~~~~~~~~~~
emojis.h:163:30: error: converting to execution character set: Illegal byte sequence
  163 |     {":left_speech_bubble:", "­m},
      |                              ^~~~~~~~~
emojis.h:164:30: error: converting to execution character set: Illegal byte sequence
  164 |     {":right_anger_bubble:", "­m},
      |                              ^~~~~~~~~
emojis.h:165:27: error: converting to execution character set: Illegal byte sequence
  165 |     {":thought_balloon:", "­m},
      |                           ^~~~~~
emojis.h:166:15: error: converting to execution character set: Illegal byte sequence
  166 |     {":zzz:", "­m},
      |               ^~~~~~
emojis.h:167:16: error: converting to execution character set: Illegal byte sequence
  167 |     {":wave:", "­m},
      |                ^~~~~~
emojis.h:168:31: error: converting to execution character set: Illegal byte sequence
  168 |     {":raised_back_of_hand:", "­m},`

**Comment by doegox** [comment]
sigh.
I'll prevent compilation of that part under windows...

**Comment by iceman1001** [comment]
fixed https://github.com/RfidResearchGroup/proxmark3/pull/610

pull latest and make clean; make -j  it will be fine.
