### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#614]
Iceman you should check again this one:
https://github.com/Gator96100/ProxSpace/issues/32

https://we.tl/t-9K28w8c8JH

Please let me know if you don't care, then I'll go.

**Comment by Gator96100** [comment]
You are comparing my rrg_other-64 build (PLATFORM=PM3OTHER) to your rdv40-64 build (PLATFORM=PM3RDV4). Of cause there is a size differance. Your proplems might come from using a RDV4 firmware on a device that is not RDV4.

This can be closed.
