### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#618]
Err:
`is -data.eml`

https://github.com/RfidResearchGroup/proxmark3/blob/9a2fc52a9284980b852187221a45d2bc0cc6ee00/client/luascripts/hf-writer.lua#L131

On Linux, after choice a dump from list it's doesn't write it (can't find patch)

After ProxSpace:
```
Not found: '*data.eml'
ERROR:  Didn't find any dump files

[+] finished hf-writer
```

**Comment by iceman1001** [comment]
The dump file template for this repo is
**hf-mf-(uid)-dump.(bin/eml/json)**

So I guess you are using dumps from offical repo or old dumps.  I suggest you rename your existing dump files to match current template.

**Comment by Windslab** [comment]
No that's from you repo. I play only with it becouse it for human.

Your dumps has a view:
**hf-mf-11223344556677-data.eml**

Yeah probably `dump` will be beter of `data`

**Comment by iceman1001** [comment]
bugger, I see...,  its inconsistent implemented in the client.

Alrighty then,  pull latest.  I think I got all places changed now.

**Comment by Windslab** [comment]
Okay you changed layout file names.

Script not working to Windows. Seems it something around `find` it is only for bash? Or probably it doesen't see current dir at all.

`Not found: '*dump.eml'`

**Comment by iceman1001** [comment]
Just tested it on PS3.2  and it works just fine. 
I don't know what you are doing wrong.

**Comment by Windslab** [comment]
![image](https://user-images.githubusercontent.com/60715874/77237045-9332af80-6bd5-11ea-9a1d-465c7407c103.png)

Ofcourse the Eml files inside the dir and names are true...

**Comment by iceman1001** [comment]
its waiting for a card,  did you put a card on the pm3?

**Comment by Windslab** [comment]
Yes sure. Today afternoon at WSL has been worked. But I have back to Windows.

**Comment by Windslab** [comment]
Okay me found a bit problem to Windows platform

Find differents below:
![image](https://user-images.githubusercontent.com/60715874/77248094-f0ffdf80-6c47-11ea-963b-326e5df824c2.png)

After modify symbols `""` to `''` it's works but why your code add `----------` prefix to all found files?

![image](https://user-images.githubusercontent.com/60715874/77248034-68813f00-6c47-11ea-9467-315a325d1528.png)

They dumps are found and secusefull printed by `print(_)` but it's lenght is different after prfix that why script printing `Didn't find any dump files`. Could you tell why you have `length = 31` if they should be 29?

**Comment by Windslab** [comment]
Iceman are you alive? :)

**Comment by Ghost-Assassin** [comment]
> Iceman are you alive? :)

bro, this is rude. Iceman did not owe you anything.

**Comment by iceman1001** [comment]
Its ok,  @Windslab  is just very eager.   We have all been that,   its just me who has less time and dont see any need to discuss this particular issue.

**Comment by Windslab** [comment]
We are from different countries. I understand your reaction. That's normal.

I not talking like a programist because an engineer. I have fix that script for Windows and now it's doesn't work for Linux. Doing two scripts not a true way. Doing check of the operation system by `if` the same. As my point you can't leave it as now. That's why my asking a code optimization.

Many Thanks

**Comment by iceman1001** [comment]
Problem is that my solution works on linux,  osx, wsl2 and proxspace 3.2,  and you seem to belive your solution is better.  Hence I don't feel the need to discuss this issue any more.  For me this is a non-issue until you prove your solution is the better one.

**Comment by Windslab** [comment]
Seems we talking about different things. As I have written that's normal.

The script from your repository are not working on my machine, at all. My machine has Cyrillic language maybe that's why different results we are have. As you see I open for conversation to understend what's going on. 

Could you check it please? How I can help?
I assume possibly the answer is find files by prefix `hf-mf-`UID`-dump.eml` in list that is returned by a **find** command. Possible it is can be do more easey, like this `-`UID`-`.

Purpose of my `Pull` are to show for you differents in script, I even not hope to see it in the repo.
