### ISSUE TITLE
Incorrect key emulation

### ISSUE THREAD

**Issue by Akisame-AI** [RfidResearchGroup/proxmark3#619]
I have moved to a new apartment and this one uses simple MFC 1k keyfobs for entering. All it checks is the UID, sector 0 key and sector 1 block 0 and key. I have extracted all the keys via a hardnested attack and dumped the card completely. When writing this dump to a direct write or OTW card I can open the doors (when I write it to a magic card the readers do not respond at all). 
However when I try to simulate this dump the doors do not react at all.
A reader attack showed no response from the readers. 
Sniffing with the PM3 in between the card and the reader showed no reaction from the reader.
When I used mifare classic tools to read it using the actual keys it showed: "None of the keys were valid for reading"

I am running the following commands

hf mf eclr
hf mf eload hf-mf-<uid>-data
hf mf sim

when trying to do a reader attack I get nothing either

![image](https://user-images.githubusercontent.com/61940251/77238895-fcfe8980-6bd4-11ea-9ab7-040034738c52.png)

Sniffing with a valid tag in between only shows me this

  ```97093740 |   97094796 | Rdr |26                                                                       |     | REQA```
as well as the tag's response (its UID with an extra 31 at the end)
which looks like it is timeing out. (it explains why it took so long to authenticate)

 hf 14a sim t 1 u AD781CF8 x e v
did nothing with the reader. MCT showed it used a default key to try to authenticate (a0a1a2a3a4a5).

I also tried "hf 14A sim" but to no avail.

Can someone tell me what I am doing wrong?

![image](https://user-images.githubusercontent.com/61940251/77238870-a42ef100-6bd4-11ea-99d1-517cb91144a5.png)

![image](https://user-images.githubusercontent.com/61940251/77238877-be68cf00-6bd4-11ea-9495-fbfec82815ee.png)

Sorry for the markdown.

**Comment by iceman1001** [comment]
It seem like you are having problems not knowing how to run the commands,  rather than reporting a issue / bug with the source code. 

We use the Proxmark3 forum ( http://www.proxmark.org/forum/index.php )   for those purposes.

**Comment by Akisame-AI** [comment]
Thanks. Sorry for the trouble
