### ISSUE TITLE
hf 14a apdu: invalid option "- "

### ISSUE THREAD

**Issue by Ghost-Assassin** [RfidResearchGroup/proxmark3#627]
For Git version: https://github.com/RfidResearchGroup/proxmark3/commit/efeff2d0f68e209597e8dae07c70b029cbdf156f

**To Reproduce**
1. git clone https://github.com/RfidResearchGroup/proxmark3.git
2. cd proxmark3
3. make clean
4. make PLATFORM=PM3OTHER
5. cd client
6. sudo ./proxmark3 /dev/ttyACM0

When running commands:

`hf 14a apdu -st 00A404000E325041592E5359532E444446303100` 
or any other commands shown in the "Sample".

The hf 14a apdu feature is not working correctly, shown in the screenshot. The apdu message was not sent, and complained on some not existing "- ". 
![image](https://user-images.githubusercontent.com/25316415/77829247-cfc55480-715b-11ea-8655-4c7eff5326bd.png)

**Desktop (please complete the following information):**
 - OS: Tried on Ubuntu 16.04, Ubuntu 18.04, Kali 2019.4
 - inside proxmark3 client run the following commands and paste the output here.
 - hw version (shown above)
 - hw status
![image](https://user-images.githubusercontent.com/25316415/77829358-83c6df80-715c-11ea-8ea1-de334c04aef2.png)

 - data tune (LF antenna was removed purposely)
![image](https://user-images.githubusercontent.com/25316415/77829384-a953e900-715c-11ea-878d-5e4f3893f419.png)

Thanks in advance

**Comment by Ghost-Assassin** [comment]
Seems other commands may also have this problem. 

![image](https://user-images.githubusercontent.com/25316415/77842273-fcf91d80-71c2-11ea-9307-268514e9cbc8.png)

**Comment by iceman1001** [comment]
Try pulling latest and try again

**Comment by Ghost-Assassin** [comment]
WORK LIKE A CHARM!!! Thank you!
