### ISSUE TITLE
"hf 14a list" could not sniff traffic from card

### ISSUE THREAD

**Issue by Ghost-Assassin** [RfidResearchGroup/proxmark3#683]
**Describe the bug**
hf 14a sniff is no longer able to sniff the conversation between reader and card for my Proxmark3 Easy (256K Version). 

**To Reproduce**
I used this version, was the latest on April 14th: https://github.com/RfidResearchGroup/proxmark3/tree/0eb303c1523a4249cb046a92f2ec63c90d941f48

1. Compile the latest version of firmware both bootrom and fullimage with command "make PLATFORM=PM3OTHER", and installed successfully with built-in flasher. 
2. Restart PM3 by disconnect from the computer, and connect back to the computer.
3. Launch the client which was built by step 1.  
4. run "hf 14a sniff", place the reader under PM3, the led C is lit. 
5. place card above PM3, the led B is no lit.
6. "hf list" shows the traffic only from the reader, no traffic was captured for card. 

**Expected behavior**
"hf 14a sniff" should be able to capture both direction traffic. 

**Desktop (please complete the following information):**
 - OS: Tried on Windows 7 and Ubuntu 18.04
 - hw version and hf list 
![image](https://user-images.githubusercontent.com/25316415/79188261-22d42280-7e51-11ea-9c34-d73fb4e4ac29.png)
![image](https://user-images.githubusercontent.com/25316415/79188676-4481d980-7e52-11ea-8be7-2139c136f3dc.png)
![image](https://user-images.githubusercontent.com/25316415/79188691-5499b900-7e52-11ea-87d1-03d8e80ac63f.png)

**Additional context**
I have tried to flash to stock firmware 2.5.0 which worked as expected, so the PM3 itself should not have a hardware issue. Firmwares I tried is added in the attachment. 
[firmware_win.zip](https://github.com/RfidResearchGroup/proxmark3/files/4473304/firmware_win.zip)

**Comment by Ghost-Assassin** [comment]
PS. the stock 2.5.0 firmware would constantly capture all the traffic with or without card interaction. The latest iceman firmware seems only captures traffic if the card is already on the card reader. 

I have tested 3 scenarios: 
- If I place the card on the card reader, then start sniffing on the console, then move the PM3 near the card, I will be able to capture the traffic from both directions. 
- If I start sniffing first and place the card on top of PM3 then move the PM3 to the reader, I won't be able to capture traffic from both directions.  
- If I start sniffing first, then place the PM3 on the top of card reader, then move the card on top of PM3, I will only be able to sniff from card reader, but not from card.

**Comment by iceman1001** [comment]
Maybe if you read the helptext you find how to work with it better.   The problem with sniff is that lack of space to store the trace data.  It eats it up fast.

I have no problem with this command.

```
[usb] pm3 --> hf 14a sniff h
It get data from the field and saves it into command buffer.
Buffer accessible from command 'hf list 14a'
Usage:  hf 14a sniff [c][r]
c - triggered by first data from card
r - triggered by first 7-bit request from reader (REQ,WUP,...)
Examples:
        hf 14a sniff c r
```

**Comment by Ghost-Assassin** [comment]
thanks for your reply iceman : )
I tried the method you mentioned. Yes, it would pick up the WUPA from the reader just like the stock firmware does. But still, my PM3 did not pick up any conversation from the card. 

Just like this screenshot shows, it captured messages from the reader but missed everything from the card. 
![image](https://user-images.githubusercontent.com/25316415/79209957-b0763900-7e76-11ea-82f1-3d551164180b.png)

If I set it to trigger by first data from card, it seems will never be able to start capturing. 
![image](https://user-images.githubusercontent.com/25316415/79210893-10b9aa80-7e78-11ea-9be7-733b71757b8e.png)
 
I also tried to **start sniffing after the card is already on the reader**.
I will be able to capture conversations from both card and reader, and it seems I could capture at most 39153 bytes. 
![image](https://user-images.githubusercontent.com/25316415/79211184-7c037c80-7e78-11ea-826f-7cf43e88920c.png)

If this function worked with no problem on your PM3, I will try to find another 512K version to cross-compare if mine has any hardware issues (I hope not).

**Comment by Ghost-Assassin** [comment]
nvm, I tried on another reader. I placed the same card on my phone with the exact method, it worked no problem. 

Seems the reader has some problem caused this issue. I will try to find out what caused this problem and see if it could help anyone has this issue in the future.

**Comment by Ghost-Assassin** [comment]
wait a sec, 
you are not gonna believe it, I have to place my card around 45° to capture its traffic. 
It has to be this weird angle to make it work LOL ...
![image](https://user-images.githubusercontent.com/25316415/79216241-6e052a00-7e7f-11ea-82ef-7540e681446a.png)

**Comment by iceman1001** [comment]
Good that it resolved itself.

sniffing is picky about positions and antenna couplings vs reader field. 
the bigbuffer is 40kb,  so 39kb log data sounds like you filled it up.  Don't know what more you expected from it.
