### ISSUE TITLE
cmds.CMD_HF_MIFARE_READBL

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#706]
Seems it bug since 40 block. I cannot get from 40 to 63.

> Key check 0
> Key check 1
> Key check 2
> Key check 3
> Key check 4
> Key check 5
> Key check 6
> Key check 7
> Key check 8
> Key check 9
> Key check 10
> Key check 11
> Key check 12
> Key check 13
> Key check 14
> Key check 15
> Key check 16
> Key check 17
> Key check 18
> Key check 19
> Key check 20
> Key check 21
> Key check 22
> Key check 23
> Key check 24
> Key check 25
> Key check 26
> Key check 27
> Key check 28
> Key check 29
> Key check 30
> Key check 31
> Key check 32
> Key check 33
> Key check 34
> Key check 35
> Key check 36
> Key check 37
> Key check 38
> Key check 39
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 40
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 41
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 42
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 43
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 44
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 45
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 46
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 47
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 48
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 49
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 50
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 51
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 52
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 53
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 54
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 55
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 56
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 57
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 58
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 59
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 60
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 61
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 62
> #db# Cmd Error: 04
> #db# Read block error
> Key check error 63

**Comment by iceman1001** [comment]
Too little information to go on,  but to me it looks like you mixed the concept on HEX vs DEC in the call.
