### ISSUE TITLE
macOS/Homebrew make failure

### ISSUE THREAD

**Issue by KaitoKid** [RfidResearchGroup/proxmark3#715]
Fresh installation of Homebrew on Catalina 10.15.4 and tried to install proxmark, but running into this error on `make`
![image](https://user-images.githubusercontent.com/9055441/80254513-2ecd9a80-8630-11ea-8468-d5471ef1cb51.png)

**Comment by doegox** [comment]
The mentioned lines are not part of the Proxmark source code, it's hard to debug based on that info.

can you run 
```
make clean
make V=1 PLATFORM=PM3RDV4 2>&1 |tee catalina_log.txt
```
and provide the logfile ?
thanks!

**Comment by doegox** [comment]
I can't reproduce the issue on Catalina 10.15
Which instructions did you follow from
https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Mac-OS-X-Homebrew-Installation-Instructions.md ?

**Comment by KaitoKid** [comment]
It's strange since I was able to build it manually, but if I ran the following I would get that error:

1. `brew tap RfidResearchGroup/proxmark3`
2. `brew install --HEAD proxmark3`

This is a fresh installation of Catalina and Homebrew as well, and only seems to come up when I try to install through homebrew.

**Comment by doegox** [comment]
hmm indeed I can reproduce now.
somehow through the formula, it seems to see qt and fail linking it while manually it compiles without gui. I'll try to investigate

**Comment by doegox** [comment]
My guess is that qt in brew is currently somehow broken:
```
brew install qt
pkg-config --libs Qt5Core
Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Core' found
```
and still `/usr/local/opt/qt5/lib/pkgconfig/Qt5Core.pc` exists

**Comment by doegox** [comment]
ok some progress : indeed brew qt changed, we've now to export explictely qt path because apparently they don't expose it systematically for some cmake issue.
So now with `export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"` I can reproduce the issue manually.

**Comment by doegox** [comment]
Try again `brew install --HEAD proxmark3`
It should work now.

**Comment by KaitoKid** [comment]
Looks like ad3267c fixed it! Closing this out
