### ISSUE TITLE
[bug] WIN32 compilation issues

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#724]
WIN32 compilation issues:

> adler32.c:180:15: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>   180 | uLong ZEXPORT adler32_combine64(adler1, adler2, len2)
>       |               ^~~~~~~~~~~~~~~~~
> [-] CC trees.c

Mb this give for you some of information. That's not beautiful at least.

**Comment by doegox** [comment]
Indeed it's not nice, but it doesn't prevent compilation.
I'm testing another approach on win32test branch, I'll check if the warning disappears on Appveyor

**Comment by doegox** [comment]
@iceman1001 pushed a fix
