### ISSUE TITLE
Error in Compile proxmark3

### ISSUE THREAD

**Issue by MohammadSecure** [RfidResearchGroup/proxmark3#742]
Hi 
when i compile proxmark3 [https://github.com/RfidResearchGroup/proxmark3.git](url)
with this syntax `./proxmark3 /dev/ttyACM0 --flash --unlock-bootloader --image ../bootrom/obj/bootrom.elf --image ../armsrc/obj/fullimage.elf`
This error in last seen : 

> Error: PHDR is not contained in Flash

please help me

**Comment by iceman1001** [comment]
- Did you get some errors when you compiled the project?
- are you running the client from inside the client folder?
 - why not use the ./pm3-flash-all script?

**Comment by iceman1001** [comment]
Ping @MohammadSecure  ,

**Comment by MohammadSecure** [comment]
I run this script `./pm3-flash-all` but i this is error out put:
`oading usable ELF segments:`
`[+]    0: V 0x00102000 P 0x00102000 (0x000434f0->0x000434f0) [R X] @0x94`
`[!!] 🚨 Error: PHDR is not contained in Flash`
`[+] All done`

and when run this syntax : `./proxmark3 /dev/ttyACM0 `
output is:
`[=] Session log /home/ali/.proxmark3/logs/log_20200531.txt`
`[=] Loading Preferences...`
`[+] loaded from JSON file /home/mrg/.proxmark3/preferences.json`
`[=] Using UART port /dev/ttyACM0`
`[!!] 🚨 ERROR: cannot communicate with the Proxmark`

**Comment by iceman1001** [comment]
You didn't answer my questions.

**Comment by iceman1001** [comment]
Closing since OP doesn't answer questions or provide accurate debug information needed.
