### ISSUE TITLE
[idea] command line argument to prevent the client from logging anything

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#744]
A command line argument to prevent the client from logging anything (log or history, or creating a .proxmark3 directory in the home directory) would be nice. The only way to do that now is to unset HOME, so it doesn't know where to create the files/directory.

From http://www.proxmark.org/forum/viewtopic.php?pid=38993#p38993

**Comment by iceman1001** [comment]
are you looking for a client that would work on a R/O environment?  Since the pm3 client will produce files some times.

**Comment by iceman1001** [comment]
this one?

**Comment by doegox** [comment]
Haha yes that's what I added today, completely forgot this issue
