### ISSUE TITLE
The Err

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#751]
![image](https://user-images.githubusercontent.com/60715874/83355419-03914600-a368-11ea-85d3-3186f486bdf7.png)

Analyze

**Comment by doegox** [comment]
What is the command line you used to compile?
A quick fix is to use `make SKIPPYTHON=1`

**Comment by Windslab** [comment]
I had used autobuild-sh from this video https://youtu.be/EfSgw40w4pc

https://yev.ooo/autobuild-sh

**Comment by Windslab** [comment]
Even if I have put the libruary into the client folder the error is some about "0X000000" bla bla bla...

**Comment by Windslab** [comment]
PS: After update the ProxSpace, `pacman -Syu` new sources does not compile at all.

**Comment by doegox** [comment]
Please contact the maintainer of the script.
Best is to use the release version, it's more stable than the git repo.

**Comment by Windslab** [comment]
@doegox your `make SKIPPYTHON=1` has working as well

Better then null, but that's not deal with grace product making, that's like an Mercedes but wait a minute, just one missing screw to wheel.

Could you please fix in the root?

**Comment by doegox** [comment]
No, git master is not a product, it's our development tree.
https://github.com/RfidResearchGroup/proxmark3/releases/tag/v4.9237 is the "product".
You're using an external script we don't provide ourselves and I don't know what went wrong.
This is why I tell you to contact the script maintainer.
If the maintainer finds an issue in our repo, we'll be glad to fix it.

**Comment by Windslab** [comment]
Yeah thanks, I have had fixed them all at few clicks to my local repo.
