### ISSUE TITLE
Latest Windows (precompiled) Build seems broken for libjansson-4.dll and libpython3.8.dll

### ISSUE THREAD

**Issue by macrl2000** [RfidResearchGroup/proxmark3#754]
When i try to use the precompiled rdv40-64 windows versions from

rdv40-64-20200602-6980429bd4c01a716c9168b05dd2f805b7e35940.zip
on
https://drive.google.com/drive/folders/1SyPB8t5Vo8O0Lh7PjNm3Kv-mO4BNbxjX

i hit an error when starting proxmark3.exe missing libjansson-4.dll and libpython3.8.dll
(this does not happen on rdv40-64-20200515-a739d333982e190566906b61f89364ef8e3ba578.zip build)

**Comment by doegox** [comment]
We're not maintaining these binaries, please contact the original maintainer.

**Comment by libin-ka** [comment]
Who has these two files?
