### ISSUE TITLE
fatal error: bzlib.h: No such file or directory

### ISSUE THREAD

**Issue by nico0481** [RfidResearchGroup/proxmark3#765]
Hello,
Trying to compile last commit with:
git pull
make clean
make -j 3

I get an error: 
"src/cmdhfmfhard.c:26:10: fatal error: bzlib.h: No such file or directory #include <bzlib.h>"

What I'm doing wrong?

Thank you

Best regards

**Comment by MadMike7777** [comment]
I successfully installed and ran Iceman's Proxmark3 program on an Ubuntu computer but it will not work on a Raspberry Pi.  I get the same fatal error.

**Comment by doegox** [comment]
Please read the updated installation instructions. E.g. https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Linux-Installation-Instructions.md
Basically you need to install bzip2 developer package, the name depends on the distro you're using.
libbz2-dev on Debian-alike.
