### ISSUE TITLE
[idea] Mifare MAD - Card publisher sector enhancement

### ISSUE THREAD

**Issue by lukaskuzmiak** [RfidResearchGroup/proxmark3#766]
Now that we have the MAD database, we can perhaps enhance the Card publisher sector info:

```
[=] --- MAD Information -------------------------------
[=] ---------------------------------------------------
[+] Card publisher sector: 0x01
[=]  00 MAD 1
[=]  01 [7006] Hotel, access contr. & sec [Vingcard a.s.]
[=]  02 [7005] Energy Saving System For Hotels, Access Control [ENKOA System]
[=]  03 [7007] Hotel, access contr. & sec [Vingcard a.s.]
[=]  04 [7007] (continuation)
[=]  05 [7007] (continuation)
[=]  06 [7009] Access control data for electronic locks [Timelox AB]
[=]  07 [0000] (free)
[=]  08 [0000] (free)
[=]  09 [0000] (free)
[=]  10 [0000] (free)
[=]  11 [0000] (free)
[=]  12 [0000] (free)
[=]  13 [0000] (free)
[=]  14 [0000] (free)
[=]  15 [0000] (free)
```

Would be cool to actually read `Vingcard a.s.` from the sector1's info and list it with `Card publisher sector`.
Some refactoring might be needed as `Card publisher sector` is printed out before we know if MAD2 is supported and it *may* point into MAD2.

IMHO the best way to go about it is first parse (`MADDecode`), then print out output using the parsed data with `MAD1DecodeAndPrint` and `MAD2DecodeAndPrint`.

Feel free to assign to me if possible, I'll try to find some time for this soon.

**Comment by iceman1001** [comment]
Your wish has been granted.  Ask and you shall receive said the lord.  Bleeding edge,

I haven't studied the datasheet enough to get it.  But,  go go go.
