### ISSUE TITLE
hf snoop looks like unusable.

### ISSUE THREAD

**Issue by K7-Lenovo** [RfidResearchGroup/proxmark3#77]
always show "Trigger kicked!" when using "hf snoop". i try to snoop a key from m1 card and reader by using pm3. when i type hf snoop command then put pm3 near the reader i will receive "Trigger kicked!" immediately. And i got no valuable data by look the hex using "hf list". it do not need a RFID card, just put pm3 near a reader and you will see this .

![image](https://user-images.githubusercontent.com/43928600/50573653-32be2380-0e13-11e9-9a1b-02cff5a1b687.png)

card reader tried: android8.1 phone with NFC, PN532, a reader in an elevator
 - OS: windows 10 pro x64
`pm3 --> hw version

Proxmark3 RFID instrument

 [ CLIENT ]
 client: iceman build for RDV40 with flashmem; smartcard;

 [ ARM ]
 bootrom: iceman/master/75d0b0b0 2019-01-01 20:27:24
      os: iceman/master/75d0b0b0 2019-01-01 20:28:17

 [ FPGA ]
 LF image built for 2s30vq100 on 2018/ 9/ 8 at 13:57:51
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 240818 bytes (46%) Free: 283470 bytes (54%)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

pm3 --> hw status
#db# Memory
#db#   BIGBUF_SIZE.............40000
#db#   Available memory........40000
#db# Tracing
#db#   tracing ................1
#db#   traceLen ...............40000
#db# Currently loaded FPGA image
#db#   mode.................... HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23
#db# Flash memory
#db#   Baudrate................24MHz
#db#   Init....................OK
#db#   Memory size.............2 mbits / 256kb
#db#   Unique ID...............0xd567a882a76ec526
#db# Smart card module (ISO 7816)
#db#   version.................v2.06
#db# LF Sampling config
#db#   [q] divisor.............95 (125 KHz)
#db#   [b] bps.................8
#db#   [d] decimation..........1
#db#   [a] averaging...........Yes
#db#   [t] trigger threshold...0
#db# LF T55XX config
#db#   [a] startgap............29*8 (232)
#db#   [b] writegap............17*8 (136)
#db#   [c] write_0.............15*8 (120)
#db#   [d] write_1.............47*8 (376)
#db#   [e] readgap.............15*8 (120)
#db# USB Speed
#db#   Sending USB packets to client...
#db#   Time elapsed............1500ms
#db#   Bytes transferred.......740352
#db#   USB Transfer Speed PM3 -> Client = 493568 Bytes/s
#db# Various
#db#   MF_DBGLEVEL.............1
#db#   ToSendMax...............-1
#db#   ToSendBit...............0
#db#   ToSend BUFFERSIZE.......2308
#db# Installed StandAlone Mode
#db#    LF HID26 standalone - aka SamyRun (Samy Kamkar)
pm3 --> data tune

[=] measuring antenna characteristics, please wait...

....

[!] LF antenna is UNUSABLE

[+] HF antenna: 36.18 V - 13.56 MHz
[+] HF antenna is OK

[-] Not showing LF tuning graph since all values is zero.`

**Comment by iceman1001** [comment]
you know that you are looking at raw HF signal data?

If you want to sniff 14a / Mifare with demodulation of signal then you need to use designated commands

**Comment by K7-Lenovo** [comment]
> you know that you are looking at raw HF signal data?
> 
> If you want to sniff 14a / Mifare with demodulation of signal then you need to use designated commands

OK, i see, i try use "hf 14a sniff".thanks iceman
