### ISSUE TITLE
pm3.sh -  more than 10 comports.

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#777]
**Describe the bug**
when finding a comport larger than 10,   com10 etc,  it reports it as  com1.

**To Reproduce**
1. assign a bluetooth comport above 10
2. ./pm3 --list

**Expected behavior**
More than 10comports 
and the comports above 10 should have correct numbering.

**Comment by doegox** [comment]
Can you show me a sample of
```
powershell.exe -command "Get-CimInstance -ClassName Win32_PnPEntity | Where-Object Caption -like 'Standard Serial over Bluetooth link (COM*' | Select Name" 2> /dev/null 
```

We need to fix the `| awk '$0 ~ /COM/{print substr($6,2,4)}'`

**Comment by iceman1001** [comment]
```
PS C:\Users\User> powershell.exe -command "Get-CimInstance -ClassName Win32_PnPEntity | Where-Object Caption -like 'Standard Serial over Bluetooth link (COM*' | Select Name"

Name
----
Standard Serial over Bluetooth link (COM10)


```
