### ISSUE TITLE
[Bug] Founded bugs

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#780]
1. No smiles: :snowflake:/:coffee: to Windows client. Yes CMD not supporting graphical as I know. Maybe better to remove it at all? It looks like graphity at the wall.
2. No colors to Windows client. Maybe better to remove it from *nix to? Or make some of preset for Windows Terminal, not make shure that's right way.
3. `hw tune` GUI for me is notworking, no reaction for changing lifts.
4. `hf plot` GUI is the same.
![image](https://user-images.githubusercontent.com/60715874/84444848-54981880-ac4b-11ea-8134-6b1b8a45d4f0.png)
Some themes the picture is hiding(missing)
![image](https://user-images.githubusercontent.com/60715874/84446058-611d7080-ac4d-11ea-8b0d-ef1d39bab10a.png)
5. `hf 14b sniff` and `hf sniff` are not working at all, looks like a commands going to /dev/null! The `hf 14a sniff` working.
6. `hf mf pref` if I choice any command it always return me a it list again. Maybe I not get how its works, but in any case it return list again.

**Comment by iceman1001** [comment]
Use the provided template as seen in the screen clip below to fill in one bug at the time with all details.  This issue doesn't fullfill the requirments and will be closed.

![image](https://user-images.githubusercontent.com/8577004/84494131-3e20aa00-aca9-11ea-820f-130e44205159.png)

**Comment by Windslab** [comment]
Thank you.


I will do that next time, but also wishing to improve your template.


But could you plase take a look at the bugs?

**Comment by doegox** [comment]
Please read carefully https://instabug.com/blog/how-to-write-a-bug-report-the-ideal-bug-report/
* title => you do it wrong
* description => you do it wrong
* no more than one bug in your report. => you do it wrong
etc

**Comment by Windslab** [comment]
> Please read carefully https://instabug.com/blog/how-to-write-a-bug-report-the-ideal-bug-report/
> * title => you do it wrong
> * description => you do it wrong
> * no more than one bug in your report. => you do it wrong
> etc
> 

Okay. Thanks for tips.
