### ISSUE TITLE
latest build error

### ISSUE THREAD

**Issue by anyuser007** [RfidResearchGroup/proxmark3#793]
Latest commit
8f4db5e

~/proxmark3$ make clean && make all

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH -DRDV4 LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF HFPLOT
Standalone mode:   LF_EM4100RWC
===================================================================
[*] MAKE client/clean
===================================================================
Client platform:   Linux
GUI support:       QT5 found, enabled
native BT support: Bluez not found, disabled
Jansson library:   system library not found, using local library
Lua library:       system library not found, using local library
Python3 library:   Python3 v3.6 found, enabled
Readline library:  enabled
Whereami library:  system library not found, using local library
compiler version:  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
===================================================================
[*] MAKE bootrom/clean
[*] MAKE fpga_compress/clean
[*] MAKE armsrc/clean
[*] MAKE recovery/clean
[*] MAKE mfkey/clean
[*] MAKE nonce2key/clean
[*] MAKE mf_nonce_brute/clean

===================================================================
Platform name:     Proxmark3 rdv4
PLATFORM:          PM3RDV4
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH -DRDV4 LF HITAG ISO15693 LEGICRF ISO14443b ISO14443a ICLASS FELICA NFCBARCODE HFSNIFF HFPLOT
Standalone mode:   LF_EM4100RWC
===================================================================
[*] MAKE client/all
===================================================================
Client platform:   Linux
GUI support:       QT5 found, enabled
native BT support: Bluez not found, disabled
Jansson library:   system library not found, using local library
Lua library:       system library not found, using local library
Python3 library:   Python3 v3.6 found, enabled
Readline library:  enabled
Whereami library:  system library not found, using local library
compiler version:  gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
===================================================================
[-] CC src/aidsearch.c
[-] CC src/cmdanalyse.c
[-] CC src/cmdcrc.c
[-] CC src/cmddata.c
[-] CC src/cmdflashmem.c
[-] CC src/cmdflashmemspiffs.c
[-] CC src/cmdhf.c
[-] CC src/cmdhf14a.c
[-] CC src/cmdhf14b.c
[-] CC src/cmdhf15.c
[-] CC src/cmdhfcryptorf.c
[-] CC src/cmdhfepa.c
[-] CC src/cmdhffelica.c
[-] CC src/cmdhffido.c
[-] CC src/cmdhficlass.c
[-] CC src/cmdhflegic.c
[-] CC src/cmdhflist.c
[-] CC src/cmdhflto.c
[-] CC src/cmdhfmf.c
[-] CC src/cmdhfmfdes.c
[-] CC src/cmdhfmfhard.c
src/cmdhfmfhard.c:26:10: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
          ^~~~~~~~~
compilation terminated.
Makefile:703: recipe for target 'obj/cmdhfmfhard.o' failed
make[1]: *** [obj/cmdhfmfhard.o] Error 1
Makefile:136: recipe for target 'client/all' failed
make: *** [client/all] Error 2

**Comment by iceman1001** [comment]
Duplicate,    #765
