### ISSUE TITLE
hf iclass chk - need for default keys

### ISSUE THREAD

**Issue by RfidResearchGroup** [RfidResearchGroup/proxmark3#8]
As found here a link below, to the new default keys file for iClass.
Now we need to fill it with keys.

Sharing is caring!

https://github.com/iceman1001/proxmark3/blob/master/client/default_iclass_keys.dic

**Comment by TomHarkness** [comment]
If we have some mifare keys to add just do PR?

**Comment by RfidResearchGroup** [comment]
Mifare keys?   that would be for the default_keys.dic   the mifare classic keys dictionary.

 And yes,  if you have some keys, put them in the right dictionary file and PR  :)
