### ISSUE TITLE
[Bug] hf sniff

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#800]
**Describe the bug**
When I write `hf sniff` to console with no/card I got nothing at all

**To Reproduce**
1. Go to 'pm3 folder'
2. Click on 'proxmark.exe'
3. Scroll down to 'end'

![image](https://user-images.githubusercontent.com/60715874/85115823-f956bf00-b224-11ea-95c8-a12b3bc8101d.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win 10 x64]
 - inside proxmark3 client run the following commands and paste the output here.
 - hw HF image built for 2s30vq100 on 2020-01-12 at 15:31:16
 - hw status OK
 - data tune -89 dB

**Additional context**
I not wont to obtain a nothing. Right?

**Comment by iceman1001** [comment]
This is no bug,  if you want to ask how the proxmark3 client works you should use the forum to ask your questions.

**Comment by iceman1001** [comment]
remade this command to work with NG and new dynmic stack.

**Comment by Windslab** [comment]
Now it's much more better! But... But... I not see data. I think It's need's to show me any way Sinus>01010>HEX. What you think?

![image](https://user-images.githubusercontent.com/60715874/85274581-cf510700-b487-11ea-972e-55df115e63e8.png)

**Comment by iceman1001** [comment]
You seem not to understand what the command does.
It captures raw signal data.  Nothing else.  You can look at the captured signal using the plot window. 

For decoded sniffs, you need to use the other sniff commands.

**Comment by Windslab** [comment]
Oh, okay I got that. I was used it wrong. Yeah I see the sinus. Thank you.

Please hold on I have also one tip for you.

When I 'stop' sniff by Enter the `hf 14a list` exception any way and looks like this:

![image](https://user-images.githubusercontent.com/60715874/85276083-ed1f6b80-b489-11ea-963d-6b6bd4197998.png)

If I use pm3 button, seems it's works:

![image](https://user-images.githubusercontent.com/60715874/85276178-0fb18480-b48a-11ea-9289-bd04bcb9ae4f.png)

As my opinion key `Enter` must stop a stiff, like a PM3 button. At the moment it's actions looks like it stop sniff but going to exception. Do you support this idea?

**Comment by iceman1001** [comment]
This issue is about `hf sniff`  and closed.
