### ISSUE TITLE
[Bug] hw tune

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#803]
**Describe the bug**
As my opinion the `hw tune` is doesen't work and the graphic is dead. I not see any changers when mooving resizes

**To Reproduce**
1. Go to 'pm3 folder'
2. Click on 'proxmark.exe'
3. Scroll down to 'end'

![1](https://user-images.githubusercontent.com/60715874/85117632-d11c8f80-b227-11ea-9135-1303001736e9.png)
![2](https://user-images.githubusercontent.com/60715874/85117636-d24dbc80-b227-11ea-8064-b77f4912fa32.png)
![3](https://user-images.githubusercontent.com/60715874/85117637-d24dbc80-b227-11ea-9785-9454fe00c149.png)
![4](https://user-images.githubusercontent.com/60715874/85117638-d24dbc80-b227-11ea-8914-91497573f9bc.png)
![5](https://user-images.githubusercontent.com/60715874/85117640-d2e65300-b227-11ea-9c50-62e4e825f7a4.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: [Win 10 x64]
- inside proxmark3 client run the following commands and paste the output here.
- hw HF image built for 2s30vq100 on 2020-01-12 at 15:31:16
- hw status OK
- data tune -89 dB

**Additional context**
I would like to get any response from graph when doing resize of the signal windows, yes?
Also I think the sinus line must bee more bold and digit's a bit more size.

And I not wishing to see line `[-] no repeating pattern found, try increasing window size` at the console when I am doing adjustments.

**Comment by iceman1001** [comment]
This is no bug.   If you want to ask questions about how the proxmark3 client works, you should use the proxmark forum.

**Comment by Windslab** [comment]
> This is no bug. If you want to ask questions about how the proxmark3 client works, you should use the proxmark forum.

Yes this is not bug just useless thing, it's does't work for me, yes? :)
The forum will be after your SSL certificate :)

**Comment by iceman1001** [comment]
Good luck with finding someone to help you.
