### ISSUE TITLE
Broken client logging for DESFire -  Max key number and type

### ISSUE THREAD

**Issue by aaronmaxlevy** [RfidResearchGroup/proxmark3#812]
See https://github.com/RfidResearchGroup/proxmark3/blob/b545109800a2d2aa68af1951c56c340cc252ac67/client/src/cmdhfmfdes.c#L1249

In lines 1249 - 1251 the code is currently trying to format a string that takes two arguments (an integer and a string) but we are only passing in a string.

This causes `hf mfdes enum` to error out on my client.

**Comment by aaronmaxlevy** [comment]
CC @bkerler since it looks like this was broken by your PR #787 unfortunately :(

**Comment by bkerler** [comment]
Yeah, thanks for pointing that nasty one out. Should be fixed with PR #813.

**Comment by iceman1001** [comment]
merged
