### ISSUE TITLE
[idea] Recovery of ECDSA keys

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#82]
**Recovery of ECDSA keys,**

Now, question is how many ECDSA keys are there...  I see in Amiibo that they seem to use eliptic curve signatures. 

See:
https://github.com/tintinweb/ecdsa-private-key-recovery

**Comment by merlokk** [comment]
Needs to have a card with this.
Visa Master UnionPay by now have only RSA keys(

**Comment by iceman1001** [comment]
Maybe @aczid have an solution for this?

**Comment by aczid** [comment]
It's like the PS3 signatures right? I'm not sure I have anything to add @iceman1001

**Comment by iceman1001** [comment]
yeah.  Something like PS3 hack.
Don't be shy! 

How did it go with hashcat?

**Comment by iceman1001** [comment]
We can retried public keys from signatures now. 
Don't know if we will get any further any time soon.  
I am closing this one meanwhile.
