### ISSUE TITLE
make clean && make all fail

### ISSUE THREAD

**Issue by anyuser007** [RfidResearchGroup/proxmark3#823]
src/cmdlfio.c: In function ‘CmdIOProxDemod’:
src/cmdlfio.c:177:44: error: ‘%02X’ directive output may be truncated writing between 2 and 8 bytes into a region of size 4 [-Werror=format-truncation=]
         snprintf(crc_str, sizeof(crc_str), "(" _RED_("fail") ") 0x%02X != 0x%02X", crc, calccrc);
                                            ^~~
src/cmdlfio.c:177:77: note: format string is defined here
         snprintf(crc_str, sizeof(crc_str), "(" _RED_("fail") ") 0x%02X != 0x%02X", crc, calccrc);
                                                                             ^~~~
src/cmdlfio.c:177:44: note: directive argument in the range [0, 2147483647]
         snprintf(crc_str, sizeof(crc_str), "(" _RED_("fail") ") 0x%02X != 0x%02X", crc, calccrc);
                                            ^~~
In file included from /usr/include/stdio.h:862:0,
                 from src/cmdlfio.c:13:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 29 and 35 bytes into a destination of size 30
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:704: recipe for target 'obj/cmdlfio.o' failed
make[1]: *** [obj/cmdlfio.o] Error 1
Makefile:136: recipe for target 'client/all' failed
make: *** [client/all] Error 2

**Comment by iceman1001** [comment]
try pulling latest and see if it still fails
