### ISSUE TITLE
lz4 decompress - coverity warning

### ISSUE THREAD

**Issue by iceman1001** [RfidResearchGroup/proxmark3#824]
**Describe the bug**
Coverity warning about lz4 decompress in fpgaload.  A memcpy uses 4bytes while we feed it with 1byte.
@slurdge  :)

**Expected behavior**
No warning in Coverity

![image](https://user-images.githubusercontent.com/8577004/85997939-7692e880-ba0a-11ea-9bb9-e3ea072aaa83.png)

**Comment by slurdge** [comment]
Actually @doegox had to put a memcpy here because some compilers (I believe yours included) complained about the manual copy that was done instead (a pointer problem IIRC).
->next_in has more than one byte in it, I don't know why it complains...

**Comment by iceman1001** [comment]
Seems like a start to understand what is going on

**Comment by iceman1001** [comment]
I updated the lz4 to the latest source from their repo.  Coverity didn't becpme happier...

**Comment by slurdge** [comment]
Yeah probably there are some patches to put again ?

**Comment by doegox** [comment]
I ported our current patches to that last version: removing the INLINE on the decompression fct and adding fct prototype

**Comment by iceman1001** [comment]
closing since I don't see anything will change for the future.
