### ISSUE TITLE
T55X7_NORALSY_CONFIG_BLOCK constant name change

### ISSUE THREAD

**Issue by moonlightelite** [RfidResearchGroup/proxmark3#833]
https://github.com/RfidResearchGroup/proxmark3/blob/c56245d1aaf35dd2c0e3d803d123344bc328aacb/client/src/cmdlft55xx.c#L1354

Hello,

I think the variable name T55X7_NORALYS_CONFIG_BLOCK needs to be change to T55X7_NORALSY_CONFIG_BLOCK here as well. Thanks.

**Comment by iceman1001** [comment]
Thanks, I missed one and fix is pushed
