### ISSUE TITLE
hf 15 redesign

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#838]

**Comment by iceman1001** [comment]
Even if branch FPGA touches this problem,  the main issue that 15 commands isn't designed as 14a,14b, etc on the proxmark.
The solution is indeed to send some switch_off commands and map how the flow of each command is.

**Comment by iceman1001** [comment]
try https://github.com/RfidResearchGroup/proxmark3/commit/8d0b41a911ca308eac990cc6bdb21d3fd073ef1c  and see if this works better.
