### ISSUE TITLE
Documentation: JTAG procedures

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#847]
Today doc is spread here & there

- [x] https://github.com/Proxmark/proxmark3/wiki/De-Bricking-Segger
- [x] https://github.com/Proxmark/proxmark3/wiki/Debricking-Proxmark3-with-buspirate
- [x] http://wiki.yobi.be/wiki/Proxmark
- [ ] https://ninja.style/post/unbrickpm3/
- [x] ../doc/Compiling Proxmark source and firmware upgrading v1.pdf
- [ ] unpublished personal notes?

**Comment by iceman1001** [comment]
I can't find the ninja.style link any longer,   but added the pdf,   to our  JTAG_NOTES.md  document.

Is there much more to add? Or can we close this one now?
