### ISSUE TITLE
Merge code from matt's Gallagher research

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#888]
Seen by @iceman1001 :
https://github.com/megabug/gallagher-research

**Comment by iceman1001** [comment]
Current status: 

- [x]  lf gallagher, OK
- [ ]  MFC
- [ ]  MF DESfire

**Comment by iceman1001** [comment]
@DarkMatterMatt    ... Now that the desfire is added,   will you also have a go with the MFC?

**Comment by DarkMatterMatt** [comment]
Unfortunately I don't have access to a system that uses MFC cards, so I wouldn't be able to test it (unless MFDES systems also accept classic card... I haven't tried that before?)

**Comment by iceman1001** [comment]
Thank you the nice contribution so far!  
I will close this now.
