### ISSUE TITLE
Capture script interactions in logs

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#891]
Is there a way to log Lua script interactions in the logfiles ?
At the moment we only see
```
[^A^Busb^A^B] pm3 --> script run foobar
[+] executing lua ...client/luascripts/foobar.lua.
[+] args ''.

[+] finished foobar.
```

**Comment by iceman1001** [comment]
We have lua colors already :)

and it would be nice to redirect the lua built-in print to our `PrintAndLogEx`
How does this affect the LIBPM3 idea?

**Comment by doegox** [comment]
it will only help I guess

**Comment by iceman1001** [comment]
I think this was all that was needed:

https://github.com/RfidResearchGroup/proxmark3/commit/ff5f5656193e4b7cbd3693137b3c94f52c6bc6e9

**Comment by doegox** [comment]
Works fine, great!
