### ISSUE TITLE
Add AppVeyor job for WSL

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#892]
Mingw is a thing of the past
It would be nice to have also a job with WSL, which is now supported by AppVeyor
https://www.appveyor.com/blog/2019/10/11/vs2019-image-with-docker-wsl-preheated/

**Comment by iceman1001** [comment]
@Gator96100   so we can close this one now?

**Comment by Gator96100** [comment]
Done #962
