### ISSUE TITLE
Iclass Chk command & dump & Hf mf staticnested

### ISSUE THREAD

**Issue by AlienDennis** [RfidResearchGroup/proxmark3#903]
staticnested

Problem: Hangs when the card is a combination of static and nested.

Solution: Selecting sectors that require staticnest (similar to hardnest)

Iclass chk command

Problem 1: Iclass chk keys don't work on RRG but works on official and iceman.

Iclass dump command

Problem 1: When dumping, the sector will only be shown till sector 5. Full dump is not possible.

Tested on legacy card

**Comment by iceman1001** [comment]
First of all,  not a very good bug report.
We can't use this information to debug the problem.

However, problem 1 should be solved with merging of FPGA branch into master.

**Comment by iceman1001** [comment]
I am closing and suggest you make a proper bug report.
