### ISSUE TITLE
'hf lto dump' macOS Illegal instruction: 4

### ISSUE THREAD

**Issue by Kevin-Nakamoto** [RfidResearchGroup/proxmark3#905]
**Describe the bug**
Sending 'hf lto dump' from MacBook, Proxmark3 starts to read each data block of LTO-CM without any problems.
However, at the end of the reading, the error message below shows up.

`./pm3: line 215: 33004 Illegal instruction: 4  $CLIENT "$@"`

**To Reproduce**
1. Place LTO cartridge on Proxmark3
2. Run the client
3. Send 'hf lto dump' from MacBook

**Expected behavior**
Dump files shall be stored on storage device. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.5 (19F101)
 - hw version

 [ Proxmark3 RFID instrument ]

 [ CLIENT ]
  client: RRG/Iceman/master/v4.9237-607-g3a39a9b6 2020-07-15 23:48:05
  compiled with Clang/LLVM 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62) OS:OSX ARCH:x86_64

 [ PROXMARK3 RDV4 ]
  external flash:                  present
  smartcard reader:                present

 [ PROXMARK3 RDV4 Extras ]
  FPC USART for BT add-on support: absent

 [ ARM ]
  bootrom: RRG/Iceman/master/v4.9237-607-g3a39a9b6 2020-07-15 23:48:42
       os: RRG/Iceman/master/v4.9237-607-g3a39a9b6 2020-07-15 23:49:01
  compiled with GCC 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

 [ FPGA ]
  LF image built for 2s30vq100 on 2020-02-22 at 12:51:14
  HF image built for 2s30vq100 on 2020-01-12 at 15:31:16

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 259976 bytes (50%) Free: 264312 bytes (50%)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

 - hw status
[#] Memory
[#]   BigBuf_size.............42056
[#]   Available memory........42000
[#] Tracing
[#]   tracing ................1
[#]   traceLen ...............20730
[#] Current FPGA image
[#]   mode.................... HF image built for 2s30vq100 on 2020-01-12 at 15:31:16
[#] Flash memory
[#]   Baudrate................24 MHz
[#]   Init....................OK
[#]   Memory size.............2 mbits / 256 kb
[#]   Unique ID...............0xD5690C23DF68082A
[#] Smart card module (ISO 7816)
[#]   version.................v3.10
[#] LF Sampling config
[#]   [q] divisor.............95 ( 125.00 kHz )
[#]   [b] bits per sample.....8
[#]   [d] decimation..........1
[#]   [a] averaging...........Yes
[#]   [t] trigger threshold...0
[#]   [s] samples to skip.....0 
[#] LF Sampling Stack
[#]   Max stack usage.........3944 / 8480 bytes
[#] LF T55XX config
[#]            [r]               [a]   [b]   [c]   [d]   [e]   [f]   [g]
[#]            mode            |start|write|write|write| read|write|write
[#]                            | gap | gap |  0  |  1  | gap |  2  |  3
[#] ---------------------------+-----+-----+-----+-----+-----+-----+------
[#] fixed bit length (default) |  29 |  17 |  15 |  47 |  15 | N/A | N/A | 
[#]     long leading reference |  31 |  20 |  18 |  50 |  15 | N/A | N/A | 
[#]               leading zero |  31 |  20 |  18 |  40 |  15 | N/A | N/A | 
[#]    1 of 4 coding reference |  29 |  17 |  15 |  31 |  15 |  47 |  63 | 
[#] 
[#] Transfer Speed
[#]   Sending packets to client...
[#]   Time elapsed............500ms
[#]   Bytes transferred.......295936
[#]   Transfer Speed PM3 -> Client = 591872 bytes/s
[#] Various
[#]   Max stack usage.........4088 / 8480 bytes
[#]   DBGLEVEL................1
[#]   ToSendMax...............12
[#]   ToSendBit...............8
[#]   ToSend BUFFERSIZE.......2308
[#]   Slow clock..............31361 Hz
[#] Installed StandAlone Mode
[#]   HF - Reading Visa cards & Emulating a Visa MSD Transaction(ISO14443) - (Salvador Mendoza)
[#] Flash memory dictionary loaded
[#]   Mifare..................865 keys
[#]   T55x7...................109 keys
[#]   iClass..................7 keys

 - data tune
[=] ---------- LF Antenna ----------
[+] LF antenna: 70.88 V - 125.00 kHz
[+] LF antenna: 37.67 V - 134.83 kHz
[+] LF optimal: 73.72 V - 126.32 kHz
[+] LF antenna is OK
[=] ---------- HF Antenna ----------
[+] HF antenna: 42.46 V - 13.56 MHz
[+] HF antenna is OK

**Additional context**
'hf lto info' command works fine. 
Also, 'hf lto dump' works under WSL environment.

**Comment by iceman1001** [comment]
Pull latest.
