### ISSUE TITLE
CLI - > JSON/XML

### ISSUE THREAD

**Issue by modemmike** [RfidResearchGroup/proxmark3#916]
I'm not sure how to word this but is there a way to run a command like pm3 -> hf search with the response in JSON or XML? Basically, someway to automate commands from the shell without user input.

**Comment by iceman1001** [comment]
run from shell and pipe?  
```sh
user@user1:~/iceman$   ./pm3 -h
user@user1:~/iceman$   ./pm3 -c 'hf search' > mylog.txt
```

**Comment by modemmike** [comment]
Perfect, thats exactly what I was logging for.  Thank you!
