### ISSUE TITLE
LTO-6 past 255

### ISSUE THREAD

**Issue by modemmike** [RfidResearchGroup/proxmark3#917]
Any pointers on how to read past line 255? Basically, anyway to get all the blocks from 16kB tapes?

**Comment by iceman1001** [comment]
not without any kind of datasheet....

**Comment by modemmike** [comment]
I was afraid that was going to be the answer, ty for clarification. So, we all need an LTO-6/7 datasheet. Not that I could but IF I had a contact somewhere, what specifically would I ask for?

**Comment by iceman1001** [comment]
IF you had a contact somewhere,  I would have asked if I could get a copy of a full datasheet for LTO-6  / specs.  And if there was an issue with that,  I would say image copies of the  rfid protocol pages would do just fine

**Comment by iceman1001** [comment]
Some progress in getting your hands on a datasheet?

**Comment by modemmike** [comment]
Possibly but not as of yet. It's on the radar but the client has been busy.

**Comment by iceman1001** [comment]
Feel free to join the discord server and discuss it even more...

**Comment by iceman1001** [comment]
closing because of lack of needed information
