### ISSUE TITLE
Iclass clone command and restore command inconsistent.

### ISSUE THREAD

**Issue by AlienDennis** [RfidResearchGroup/proxmark3#926]
With the right elite key, restore/clone function is unable to run as per normal. 

<img width="524" alt="Iclass Problem" src="https://user-images.githubusercontent.com/18269358/90890106-e8285b00-e3eb-11ea-9e28-1b6d0f968d70.png">

Typo Problem

<img width="662" alt="Iclass Problem png 2" src="https://user-images.githubusercontent.com/18269358/90890111-e9598800-e3eb-11ea-866e-701338b0087e.png">

**Comment by iceman1001** [comment]
fix: 
https://github.com/RfidResearchGroup/proxmark3/commit/53c7e47e75eb1503bb93a66a1300a08ec5dc2e84

**Comment by iceman1001** [comment]
pull latest and test
