### ISSUE TITLE
[idea]PM3 shell scripts

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#929]
Hi to all. Can you please corect the sysntacs of the .sh scripts for the do some of commands? It's does't work. Problems with cd/r and git not see the .git

Arch Linux the scripts for i3blocks:

```
#!/bin/sh

cd ~/proxmark3
git fetch
git pull
make clean && make all
pm3-flash-all
```
and

```
#!/bin/sh

cd ~/proxmark3
cd client
proxmark3 /dev/ttyACM0
```

**Comment by doegox** [comment]
* Your scripts assume the repo is already cloned in ~/proxmark3, right ?
* `git fetch` + `git pull` is redundant. Actually `git pull` == `git fetch` + `git merge`
* if you chain make clean && make all, better to chain also the flashing, so you don't attempt to flash if the compilation failed.
* when you call a command from the local directory, you need to write it with "./" : `./pm3-flash-all`

So my guess is that you need something like this
```
#!/bin/sh

[ -d ~/proxmark3 ] || git clone https://github.com/RfidResearchGroup/proxmark3.git
cd ~/proxmark3
git pull
make clean && make -j && ./pm3-flash-all
```

and 

```
cd ~/proxmark3/client
./proxmark3 /dev/ttyACM0
```

Or just
```
cd ~/proxmark3
./pm3
```

**Comment by Windslab** [comment]
> * Your scripts assume the repo is already cloned in ~/proxmark3, right ?

Yes

You can take a look to the pic and see that's problem in in \r and other WTF moments. Some thimes Linux make me cry...

See on i3blocks two links, now it's more clear for you, why me asking and .sh scripts. Mayme for you that's will be cool also :)

![image](https://user-images.githubusercontent.com/60715874/91595588-72cd0500-e96c-11ea-80a8-764f035fd125.png)

Why it's not working?

**Comment by doegox** [comment]
It seems you're using a windows editor, try convert your scripts with `dos2unix`

**Comment by Windslab** [comment]
> using a windows editor

Exactly! Thx to encoding...
