### ISSUE TITLE
[BUG] Full screen mode freeze

### ISSUE THREAD

**Issue by Windslab** [RfidResearchGroup/proxmark3#931]
Working excelent in the urxvt terminal mode:
![image](https://user-images.githubusercontent.com/60715874/91642693-0b7b8780-ea36-11ea-9754-74c9c5232576.png)

Not working at all in fullscreen mode by i3 etc:
![image](https://user-images.githubusercontent.com/60715874/91642696-159d8600-ea36-11ea-9af6-15a526ca8860.png)

It looks like totally freezes, even a cursor. After you have backed to non full screen mode, all of you has been did will displayed in the command =>

The clear Arch system so that's your bug 👍 

PS: We need more colors in syntax highlight. Will work on this way?

**Comment by iceman1001** [comment]
Closed by lacking of relevant information to debug.

**Comment by Windslab** [comment]
Wery radically!
I`ll give you it, could you please tell with one you need? Command? Grep? Logs?

Sorry I am not professional user of linux...

**Comment by Windslab** [comment]
@iceman1001 How are you doing
