### ISSUE TITLE
hf mf auto * 4  produces "fantom" trailer sectors in extended data sectors

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#948]
Using a blank MFC 4k, content checked with TagInfo as well
```
hf mf auto * 4
hf mf eview 4
```
![image](https://user-images.githubusercontent.com/60773/92370226-49de0a00-f0fa-11ea-8988-a630a3c2a569.png)

Blocks 131 and 147 are supposed to be empty
Same error in the dump files

**Comment by iceman1001** [comment]
looks like sector loop is off by one, before trigger the larger sectors

**Comment by doegox** [comment]
Fixed it 974e9d8bb
