### ISSUE TITLE
lf hitag reader needs to send its command much earlier

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/proxmark3#961]
`lf hitag reader 26` fails at talking to a HT2 if the HT2 is in emulation mode. We need to send the command much quicker after powering the field. 

Let's illustrate with some captures done with a second proxmark, to capture the command part as well

Here is a tag without emulation, read works fine:
![image](https://user-images.githubusercontent.com/60773/93513521-45012d80-f926-11ea-8205-fcea4c4cb3d3.png)

But here is a tag configured to emulate a EM4100:
![image](https://user-images.githubusercontent.com/60773/93513578-577b6700-f926-11ea-8254-c3dc292bce5e.png)

We see that it already started its emulation mode before the command is sent, and so the command fails.

Finally, here is an example of what should be done, here done manually with `lf cmdread d 50 z 116 o 166 e W 3000 c W11000`
![image](https://user-images.githubusercontent.com/60773/93513715-8db8e680-f926-11ea-892f-85d48a0f3770.png)

**Comment by doegox** [comment]
@iceman1001 with https://github.com/RfidResearchGroup/proxmark3/commit/8f2b9b9d66a74871f7d814c6b41443fe66629ccb
still too late, actually I see only very little difference:
![image](https://user-images.githubusercontent.com/60773/93603639-93650980-f9c4-11ea-9d5a-a4016bba3cc6.png)

**Comment by iceman1001** [comment]
Hard to make out from your picture but how many samples before tag starts?

**Comment by doegox** [comment]
Fixed 59976aa5881592c335bf125ba268f4b3718664f2
